Import wiredtiger: be1725260027ca435e6d3b3c964e4c942db0f425 from branch mongodb-master
ref: 5d5980c6f1..be17252600
for: 6.0.0-rc0

WT-9081       Reintroduce PPC tests

diff --git a/src/third_party/wiredtiger/test/evergreen.yml b/src/third_party/wiredtiger/test/evergreen.yml
--- a/src/third_party/wiredtiger/test/evergreen.yml
+++ b/src/third_party/wiredtiger/test/evergreen.yml
@@ -173,6 +173,29 @@ functions:
               -G "${cmake_generator|Ninja}" ../.
           fi
     - *make_wiredtiger
+  # FIXME-WT-8981 - Ubuntu PPC tests have been replaced by RHEL8 tests as of WT-8688, but the RHEL8 tests are currently disabled 
+  # due to platform issues. On completion of WT-8981 this can be deleted.
+  "compile wiredtiger address sanitizer ppc ubuntu":
+    - command: shell.exec
+      params:
+        working_dir: "wiredtiger"
+        shell: bash
+        script: |
+          set -o errexit
+          set -o verbose
+          if [ "$OS" != "Windows_NT" ]; then
+            . test/evergreen/find_cmake.sh
+            if [ -d cmake_build ]; then rm -r cmake_build; fi
+            mkdir -p cmake_build
+            cd cmake_build
+            # CC is set to the system default "clang" binary here as a workaround to mongo toolchains not supporting ASAN on Ubuntu PPC.
+            $CMAKE -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/clang.cmake -DCMAKE_C_FLAGS="-ggdb" -DWITH_PIC=1 \
+              -DHAVE_DIAGNOSTIC=1 ${NON_BARRIER_DIAGNOSTIC_YIELDS|} -DCMAKE_BUILD_TYPE=ASan \
+              -DHAVE_BUILTIN_EXTENSION_LZ4=1 -DHAVE_BUILTIN_EXTENSION_SNAPPY=1 -DHAVE_BUILTIN_EXTENSION_ZLIB=1 ${configure_python_setting|} \
+              -G "${cmake_generator|Ninja}" ../.
+          fi
+    - *make_wiredtiger
+
   "compile wiredtiger with builtins":
     - command: shell.exec
       params:
@@ -701,6 +724,20 @@ variables:
     commands:
       - func: "get project"
       - func: "compile wiredtiger address sanitizer"
+      - func: "format test script"
+        vars:
+          format_test_script_args: -t 360
+          test_env_vars:
+            ASAN_OPTIONS="detect_leaks=1:abort_on_error=1:disable_coredump=0:unmap_shadow_on_exit=1"
+            ASAN_SYMBOLIZER_PATH=/opt/mongodbtoolchain/v4/bin/llvm-symbolizer
+
+  # FIXME-WT-8981 - Ubuntu PPC tests have been replaced by RHEL8 tests as of WT-8688, but the RHEL8 tests are currently disabled 
+  # due to platform issues. On completion of WT-8981 this can be deleted.
+  - &format-stress-sanitizer-test-ppc-ubuntu
+    exec_timeout_secs: 25200
+    commands:
+      - func: "get project"
+      - func: "compile wiredtiger address sanitizer ppc ubuntu"
       - func: "format test script"
         vars:
           format_test_script_args: -t 360
@@ -2399,6 +2436,27 @@ tasks:
             ASAN_SYMBOLIZER_PATH=/opt/mongodbtoolchain/v4/bin/llvm-symbolizer
           format_test_script_args: -S
 
+  # FIXME-WT-8981 - Ubuntu PPC tests have been replaced by RHEL8 tests as of WT-8688, but the RHEL8 tests are currently disabled 
+  # due to platform issues. On completion of WT-8981 this can be deleted.
+  - name: format-asan-smoke-ppc-test
+    commands:
+      - func: "get project"
+      - func: "compile wiredtiger"
+        vars:
+          posix_configure_flags:
+            -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/clang.cmake
+            -DHAVE_DIAGNOSTIC=1
+            -DWITH_PIC=1
+            -DCMAKE_BUILD_TYPE=ASan
+            -DHAVE_BUILTIN_EXTENSION_LZ4=1 -DHAVE_BUILTIN_EXTENSION_SNAPPY=1 -DHAVE_BUILTIN_EXTENSION_ZLIB=1
+      - func: "format test script"
+        # Run smoke tests, don't stop at failed tests, use default config
+        vars:
+          test_env_vars:
+            ASAN_OPTIONS="detect_leaks=1:abort_on_error=1:disable_coredump=0:unmap_shadow_on_exit=1"
+            ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-6.0/bin/llvm-symbolizer
+          format_test_script_args: -S
+
   - name: format-wtperf-test
     commands:
       - func: "get project"
@@ -2646,7 +2704,7 @@ tasks:
 
   # The task name is ppc-zseries because this task will be used in both buildVariants
   - name: format-stress-ppc-zseries-test
-    tags: ["stress-test-ppc-1", "stress-test-zseries-1"]
+    tags: ["stress-test-ppc-1", "stress-test-zseries-1", "stress-test-ppc-ubuntu"]
     # Set 2.5 hours timeout (60 * 60 * 2.5)
     exec_timeout_secs: 9000
     commands:
@@ -2656,6 +2714,33 @@ tasks:
         vars:
           #run for 2 hours ( 2 * 60 = 120 minutes), use default config
           format_test_script_args: -e "SEGFAULT_SIGNALS=all" -b "catchsegv ./t" -t 120
+
+  # FIXME-WT-8981 - Ubuntu PPC tests have been replaced by RHEL8 tests as of WT-8688, but the RHEL8 tests are currently disabled
+  # due to platform issues. On completion of WT-8981 this can be deleted.
+  - name: format-stress-sanitizer-ppc-test
+    tags: ["stress-test-ppc-ubuntu"]
+    # Set 2.5 hours timeout (60 * 60 * 2.5)
+    exec_timeout_secs: 9000
+    commands:
+      - func: "get project"
+      - func: "compile wiredtiger"
+        vars:
+          # CC is set to the system default "clang" binary here as a workaround to mongo toolchains not supporting ASAN on Ubuntu PPC.
+          posix_configure_flags:
+            -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/clang.cmake
+            -DHAVE_DIAGNOSTIC=1
+            -DWITH_PIC=1
+            -DHAVE_BUILTIN_EXTENSION_LZ4=1
+            -DHAVE_BUILTIN_EXTENSION_SNAPPY=1
+            -DHAVE_BUILTIN_EXTENSION_ZLIB=1
+            -DCMAKE_BUILD_TYPE=ASan
+      - func: "format test script"
+        vars:
+          test_env_vars:
+            ASAN_OPTIONS="detect_leaks=1:abort_on_error=1:disable_coredump=0:unmap_shadow_on_exit=1"
+            ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-6.0/bin/llvm-symbolizer
+          # Run for 2 hours (2 * 60 = 120 minutes), don't stop at failed tests, use default config
+          format_test_script_args: -t 120
 
   - <<: *format-stress-test
     name: format-stress-test-1
@@ -2669,6 +2754,9 @@ tasks:
   - <<: *format-stress-test
     name: format-stress-test-4
     tags: ["stress-test-4"]
+  - <<: *format-stress-sanitizer-test-ppc-ubuntu
+    name: format-stress-sanitizer-test-ppc-ubuntu
+    tags: ["stress-test-ppc-ubuntu"]
   - <<: *format-stress-sanitizer-test
     name: format-stress-sanitizer-test-1
     tags: ["stress-test-1", "stress-test-ppc-1"]
@@ -4275,6 +4363,40 @@ buildvariants:
     - name: generate-datafile-big-endian
     - name: verify-datafile-big-endian
     - name: verify-datafile-from-little-endian
+
+# FIXME-WT-8981 - Ubuntu PPC tests have been replaced by RHEL8 tests as of WT-8688, but the RHEL8 tests are currently disabled
+# due to platform issues. On completion of WT-8981 this can be deleted.
+- name: ubuntu1804-ppc
+  display_name: "~ Ubuntu 18.04 PPC"
+  run_on:
+  - ubuntu1804-power8-test
+  batchtime: 120 # 2 hours
+  expansions:
+    format_test_setting: ulimit -c unlimited
+    test_env_vars:
+      WT_BUILDDIR=$(git rev-parse --show-toplevel)/cmake_build
+      LD_LIBRARY_PATH=$WT_BUILDDIR
+    posix_configure_flags:
+      -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/mongodbtoolchain_v3_gcc.cmake
+      -DCMAKE_C_FLAGS="-ggdb"
+      -DHAVE_DIAGNOSTIC=1
+      -DENABLE_PYTHON=1
+      -DENABLE_ZLIB=1
+      -DENABLE_SNAPPY=1
+      -DENABLE_STRICT=1
+      -DCMAKE_INSTALL_PREFIX=$(pwd)/LOCAL_INSTALL
+    python_binary: '/opt/mongodbtoolchain/v3/bin/python3'
+    # Use half number of vCPU to avoid OOM kill failure
+    smp_command: -j $(echo $(grep -c ^processor /proc/cpuinfo) / 2 | bc)
+    cmake_generator: Ninja
+    make_command: ninja
+  tasks:
+    - name: compile
+    - name: unit-test
+    - name: format-smoke-test
+    - name: format-asan-smoke-ppc-test
+    - name: format-wtperf-test
+    - name: ".stress-test-ppc-ubuntu"
 
 - name: rhel8-ppc
   display_name: "~ RHEL8 PPC"
