Import wiredtiger: 9536107f701eb0355d23e97863e821beea2d6c48 from branch mongodb-master (#34051)
Co-authored-by: wt-vendoring-bot <wt-vendoring-bot@mongodb.com>
GitOrigin-RevId: 72f37d8cf6dee623aaf4f2b40661f5044f957993

diff --git a/src/third_party/wiredtiger/test/evergreen.yml b/src/third_party/wiredtiger/test/evergreen.yml
--- a/src/third_party/wiredtiger/test/evergreen.yml
+++ b/src/third_party/wiredtiger/test/evergreen.yml
@@ -154,7 +154,7 @@ functions:
     params:
       aws_key: ${aws_key}
       aws_secret: ${aws_secret}
-      remote_file: wiredtiger/${build_variant}/${revision}/artifacts/${dependent_task|compile}_${build_id}.tgz
+      remote_file: wiredtiger/${build_variant}/${revision}/artifacts/${dependent_task|compile}_${build_id}${postfix|}.tgz
       bucket: build_external
       extract_to: ${destination|wiredtiger}
   "fetch endian format artifacts" :
@@ -825,11 +825,13 @@ functions:
           echo "Using num_jobs '-j ${num_jobs}' for 'unit test'"
           threads_command="-j ${num_jobs}"
         fi
-        if [ ${check_coverage|false} = true ]; then
-            ${python_binary|python3} ../test/suite/run.py ${ignore_stdout} ${unit_test_args|-v 2} ${unit_test_variant_args} $threads_command 2>&1 || echo "Ignoring failed test as we are checking test coverage"
-        else
-            ${python_binary|python3} ../test/suite/run.py ${ignore_stdout} ${unit_test_args|-v 2} ${unit_test_variant_args} $threads_command 2>&1
-        fi
+        for i in $(seq ${times|1}); do
+            if [ ${check_coverage|false} = true ]; then
+                ${python_binary|python3} ../test/suite/run.py ${ignore_stdout} ${unit_test_args|-v 2} ${unit_test_variant_args} $threads_command 2>&1 || echo "Ignoring failed test as we are checking test coverage"
+            else
+                ${python_binary|python3} ../test/suite/run.py ${ignore_stdout} ${unit_test_args|-v 2} ${unit_test_variant_args} $threads_command 2>&1
+            fi
+        done
 
   "code coverage analysis":
     command: shell.exec
@@ -2547,6 +2549,62 @@ tasks:
             set -o verbose
             ${PREPARE_TEST_ENV}
             ../test/live_restore/long_test.sh
+
+  # The following tests are temporary so we can heavily test live restore in the final weeks of the project.
+  # They should be deleted when on project completion.
+  # FIXME-WT-14312
+
+  - name: live-restore-short-heavy-testing
+    depends_on:
+    - name: compile
+    commands:
+      - func: "fetch artifacts"
+      - command: shell.exec
+        params:
+          working_dir: "wiredtiger/cmake_build/"
+          script: |
+            set -o errexit
+            set -o verbose
+            ${PREPARE_TEST_ENV}
+
+            # Runtime is approx 20 seconds under ASan. Run for 1 hour
+            for i in $(seq 180); do
+                ../test/live_restore/short_test.sh
+            done
+
+  # Runtime is already 1 hour under ASan. Create a second task to double the testing time.
+  - name: live-restore-long-heavy-testing
+    depends_on:
+    - name: compile
+    commands:
+      - func: "fetch artifacts"
+      - command: shell.exec
+        params:
+          working_dir: "wiredtiger/cmake_build/"
+          script: |
+            set -o errexit
+            set -o verbose
+            ${PREPARE_TEST_ENV}
+            ../test/live_restore/long_test.sh
+
+  - name: unit-test-live-restore-heavy-testing
+    depends_on:
+    - name: compile
+    commands:
+      - func: "fetch artifacts"
+      - func: "unit test"
+        vars:
+          unit_test_args: live_restore
+          times: 60 # Run time is approx 10 seconds. Loops it for 10 minutes
+
+  - name: format-live-restore-heavy-testing
+    commands:
+      - func: "get project"
+      - func: "compile wiredtiger"
+      - func: "format test script"
+        vars:
+          # 2 hours using a custom config to maximally test live restore
+          format_test_script_args: "-c ../../../test/format/CONFIG.live_restore -t 120"
 
   # End of live restore tests
 
@@ -4948,6 +5006,21 @@ tasks:
         vars:
           upload_filename: WT_TEST.tgz
           upload_source_dir: wiredtiger/cmake_build/bench/wtperf/WT_TEST_0_0/
+      # Now take and upload a backup. We use this as the source in our live restore perf tests.
+      - command: shell.exec
+        params:
+          working_dir: "wiredtiger/cmake_build/bench/wtperf"
+          shell: bash
+          script: |
+            set -o errexit
+            set -o verbose
+            ${PREPARE_TEST_ENV}
+            ${python_binary|python3} ../../../test/live_restore/take_backup.py
+      - func: "upload artifact"
+        vars:
+          upload_filename: WT_TEST_backup.tgz
+          upload_source_dir: wiredtiger/cmake_build/bench/wtperf/WT_TEST_0_0_backup/
+          postfix: "_backup"
       # Call cleanup function to avoid duplicated artifact upload in the post-task stage.
       - func: "cleanup"
 
@@ -5106,6 +5179,7 @@ tasks:
         vars:
           dependent_task: perf-test-long-500m-btree-populate
           destination: "wiredtiger/cmake_build/bench/wtperf/SOURCE"
+          postfix: "_backup"
       # Create an empty home directory to be used as the destination for live restore.
       - command: shell.exec
         params:
@@ -5146,6 +5220,7 @@ tasks:
         vars:
           dependent_task: perf-test-long-500m-btree-populate
           destination: "wiredtiger/cmake_build/bench/wtperf/SOURCE"
+          postfix: "_backup"
       # Create an empty home directory to be used as the destination for live restore.
       - command: shell.exec
         params:
@@ -5417,6 +5492,10 @@ buildvariants:
     - name: csuite-long-running
       batchtime: 1440 # once a day
     - name: live-restore-long
+    - name: live-restore-short-heavy-testing
+    - name: live-restore-long-heavy-testing
+    - name: unit-test-live-restore-heavy-testing
+    - name: format-live-restore-heavy-testing
 
 - name: ubuntu2004-asan
   display_name: "! Ubuntu 20.04 ASAN"
@@ -5440,6 +5519,9 @@ buildvariants:
     - name: model-test-long-random-config
       batchtime: 1440 # once a day
     - name: live-restore-long
+    - name: live-restore-short-heavy-testing
+    - name: live-restore-long-heavy-testing
+    - name: format-live-restore-heavy-testing
 
 - name: ubuntu2004-tsan
   display_name: "! Ubuntu 20.04 TSAN"
@@ -5828,6 +5910,10 @@ buildvariants:
       distros: ubuntu2004-arm64-large
     - name: unit-test-zstd
     - name: wtperf-test
+    - name: live-restore-short-heavy-testing
+    - name: live-restore-long-heavy-testing
+    - name: unit-test-live-restore-heavy-testing
+    - name: format-live-restore-heavy-testing
 
 - name: amazon2-arm64
   display_name: "Amazon Linux 2 ARM64"
@@ -5901,6 +5987,10 @@ buildvariants:
     - name: configure-combinations
     - name: format-smoke-test
     - name: s3-tiered-storage-extensions-test
+    - name: live-restore-short-heavy-testing
+    - name: live-restore-long-heavy-testing
+    - name: unit-test-live-restore-heavy-testing
+    - name: format-live-restore-heavy-testing
 
 - name: ubuntu2004-release-arm64
   display_name: "~ Ubuntu 20.04 (ARM64, Release Build)"
@@ -6159,6 +6249,10 @@ buildvariants:
       distros: amazon2023-arm64-latest-large-m8g
     - name: format-smoke-test
     - name: s3-tiered-storage-extensions-test
+    - name: live-restore-short-heavy-testing
+    - name: live-restore-long-heavy-testing
+    - name: unit-test-live-restore-heavy-testing
+    - name: format-live-restore-heavy-testing
 
 - name: amazon2023-armv9
   display_name: "(ARMV9) Amazon Linux 2023 ARM64"
