Import wiredtiger: 039cc949e442a69f072984ce625cb6cd2983cfa3 from branch mongodb-master
ref: 9318c8f5ae..039cc949e4
for: 7.1.0-rc0

WT-7401 Fix silent failures in evergreen

diff --git a/src/third_party/wiredtiger/test/evergreen.yml b/src/third_party/wiredtiger/test/evergreen.yml
--- a/src/third_party/wiredtiger/test/evergreen.yml
+++ b/src/third_party/wiredtiger/test/evergreen.yml
@@ -52,6 +52,7 @@ functions:
   "fetch mongo-tests repo" :
     command: shell.exec
     params:
+      shell: bash
       script: |
         set -o errexit
         set -o verbose
@@ -74,6 +75,7 @@ functions:
   "import wiredtiger into mongo" :
     command: shell.exec
     params:
+      shell: bash
       script: |
         set -o errexit
         set -o verbose
@@ -249,6 +251,7 @@ functions:
     command: shell.exec
     params:
       working_dir: "wiredtiger/cmake_build"
+      shell: bash
       script: |
         set -o errexit
         set -o verbose
@@ -427,6 +430,7 @@ functions:
     command: shell.exec
     params:
       working_dir: "wiredtiger"
+      shell: bash
       script: |
         set -o errexit
         set -o verbose
@@ -437,6 +441,7 @@ functions:
     command: shell.exec
     params:
       working_dir: "wiredtiger"
+      shell: bash
       script: |
         set -o errexit
         set -o verbose
@@ -474,6 +479,7 @@ functions:
     # Delete unnecessary data from the upload.
     - command: shell.exec
       params:
+        shell: bash
         script: |
           rm -rf wiredtiger/cmake_build/examples
           rm -rf wiredtiger/cmake_build/bench
@@ -515,6 +521,7 @@ functions:
     command: shell.exec
     params:
       working_dir: "wiredtiger/cmake_build/bench/wt2853_perf"
+      shell: bash
       script: |
         set -o errexit
         set -o verbose
@@ -524,6 +531,7 @@ functions:
     command: shell.exec
     params:
       working_dir: "wiredtiger/cmake_build"
+      shell: bash
       script: |
         set -o errexit
         set -o verbose
@@ -533,6 +541,7 @@ functions:
     command: shell.exec
     params:
       working_dir: "wiredtiger"
+      shell: bash
       script: |
         set -o errexit
         set -o verbose
@@ -546,16 +555,25 @@ functions:
     command: shell.exec
     params:
       working_dir: "wiredtiger/cmake_build/test/format"
+      shell: bash
       script: |
         set -o errexit
         set -o verbose
+        # Fail, show the configuration file.
+        fail() {
+          echo "======= FAILURE =========="
+          [ -f RUNDIR/CONFIG ] && cat RUNDIR/CONFIG
+          exit 1
+        }
+
         for i in $(seq ${times|1}); do
-          ./t -c ${config|../../../test/format/CONFIG.stress} ${trace_args|-T bulk,txn,retain=50} ${extra_args|} || ( [ -f RUNDIR/CONFIG ] && cat RUNDIR/CONFIG ) 2>&1
+          ./t -c ${config|../../../test/format/CONFIG.stress} ${trace_args|-T bulk,txn,retain=50} ${extra_args|} || fail
         done
   "format test predictable":
     command: shell.exec
     params:
       working_dir: "wiredtiger/cmake_build/test/format"
+      shell: bash
       script: |
         # To test predictable replay, we run test/format three times with the same data seed
         # each time, and compare the keys and values found in the WT home directories.
@@ -608,6 +626,7 @@ functions:
     command: shell.exec
     params:
       working_dir: "wiredtiger/cmake_build/test/format"
+      shell: bash
       script: |
         set -o errexit
         set -o verbose
@@ -619,6 +638,7 @@ functions:
     command: shell.exec
     params:
       working_dir: "wiredtiger/cmake_build/test/format"
+      shell: bash
       script: |
         # To make sure we have plenty of flush_tier calls, we set the flush frequency high
         # and the time between checkpoints low. We specify only using tables, as that's the
@@ -635,6 +655,7 @@ functions:
     command: shell.exec
     params:
       working_dir: "wiredtiger/cmake_build/test/manydbs"
+      shell: bash
       script: |
         set -o errexit
         set -o verbose
@@ -643,6 +664,7 @@ functions:
     command: shell.exec
     params:
       working_dir: "wiredtiger/cmake_build/test/thread"
+      shell: bash
       script: |
         set -o errexit
         set -o verbose
@@ -651,6 +673,7 @@ functions:
     command: shell.exec
     params:
       working_dir: "wiredtiger/cmake_build/test/csuite"
+      shell: bash
       script: |
         set -o errexit
         set -o verbose
@@ -689,6 +712,7 @@ functions:
     command: shell.exec
     params:
       working_dir: "wiredtiger/cmake_build/test/csuite/schema_abort"
+      shell: bash
       script: |
         # Get a random value with leading zeroes removed, /bin/sh version.
         rando() {
@@ -771,6 +795,7 @@ functions:
   "cleanup":
     command: shell.exec
     params:
+      shell: bash
       script: |
         rm -rf "wiredtiger"
         rm -rf "wiredtiger.tgz"
@@ -779,6 +804,7 @@ functions:
     command: shell.exec
     params:
       working_dir: "wiredtiger/cmake_build"
+      shell: bash
       script: |
         set -o verbose
 
@@ -812,6 +838,7 @@ functions:
     command: shell.exec
     params:
       working_dir: "wiredtiger/cmake_build"
+      shell: bash
       script: |
         set -o errexit
         set -o verbose
@@ -825,6 +852,7 @@ functions:
     command: shell.exec
     params:
       working_dir: "wiredtiger/cmake_build/test/checkpoint"
+      shell: bash
       script: |
         set -o errexit
         set -o verbose
@@ -834,6 +862,7 @@ functions:
     command: shell.exec
     params:
       working_dir: "wiredtiger/cmake_build/test/checkpoint"
+      shell: bash
       script: |
         # Get a random value with leading zeroes removed, /bin/sh version.
         rando() {
@@ -939,6 +968,7 @@ functions:
     command: shell.exec
     params:
       working_dir: "wiredtiger"
+      shell: bash
       script: |
         set -o errexit
         set -o verbose
@@ -952,6 +982,7 @@ functions:
   "convert-to-atlas-evergreen-format":
     - command: shell.exec
       params:
+        shell: bash
         script: |
           set -o errexit
           set -o verbose
@@ -1003,6 +1034,7 @@ functions:
     - command: shell.exec
       params:
         working_dir: "wiredtiger"
+        shell: bash
         script: |
           set -o errexit
           set -o verbose
@@ -1022,6 +1054,7 @@ functions:
     command: shell.exec
     params:
       working_dir: "wiredtiger/bench/workgen/runner"
+      shell: bash
       script: |
         set -o errexit
         set -o verbose
@@ -1465,6 +1498,7 @@ tasks:
       - command: shell.exec
         params:
           working_dir: "wiredtiger/cmake_build"
+          shell: bash
           script: |
             set -o errexit
             set -o verbose
@@ -1479,6 +1513,7 @@ tasks:
       - command: shell.exec
         params:
           working_dir: "wiredtiger/cmake_build"
+          shell: bash
           script: |
             set -o errexit
             set -o verbose
@@ -2800,6 +2835,7 @@ tasks:
       - command: shell.exec
         params:
           working_dir: "wiredtiger/dist"
+          shell: bash
           script: |
             set -o errexit
             set -o verbose
@@ -2818,6 +2854,7 @@ tasks:
       - command: shell.exec
         params:
           working_dir: "wiredtiger/dist"
+          shell: bash
           script: |
             set -o errexit
             set -o verbose
@@ -2832,6 +2869,7 @@ tasks:
       - command: shell.exec
         params:
           working_dir: "wiredtiger/cmake_build/bench/wtperf"
+          shell: bash
           script: |
             set -o errexit
             set -o verbose
@@ -2847,6 +2885,7 @@ tasks:
       - command: shell.exec
         params:
           working_dir: "wiredtiger/cmake_build/test/fops"
+          shell: bash
           script: |
             set -o errexit
             set -o verbose
@@ -2883,6 +2922,7 @@ tasks:
       - command: shell.exec
         params:
           working_dir: "wiredtiger/cmake_build/bench/tiered"
+          shell: bash
           script: |
             set -o errexit
             set -o verbose
@@ -2917,6 +2957,7 @@ tasks:
       - command: shell.exec
         params:
           working_dir: "wiredtiger"
+          shell: bash
           script: |
             set -o errexit
             set -o verbose
@@ -2935,6 +2976,7 @@ tasks:
       - command: shell.exec
         params:
           working_dir: "wiredtiger"
+          shell: bash
           script: |
             set -o errexit
             set -o verbose
@@ -3051,6 +3093,7 @@ tasks:
       - command: shell.exec
         params:
           working_dir: "wiredtiger"
+          shell: bash
           script: |
             set -o errexit
             set -o verbose
@@ -3062,6 +3105,7 @@ tasks:
       - command: shell.exec
         params:
           working_dir: "wiredtiger"
+          shell: bash
           script: |
             set -o errexit
             set -o verbose
@@ -3101,6 +3145,7 @@ tasks:
       - command: shell.exec
         params:
           working_dir: "wiredtiger/dist"
+          shell: bash
           script: |
             set -o errexit
             set -o verbose
@@ -3128,6 +3173,7 @@ tasks:
       - command: shell.exec
         params:
           working_dir: "wiredtiger/test/syscall"
+          shell: bash
           script: |
             set -o errexit
             set -o verbose
@@ -3169,14 +3215,15 @@ tasks:
       - command: shell.exec
         params:
           working_dir: "wiredtiger/cmake_build"
+          shell: bash
           script: |
             set -o errexit
             set -o verbose
             ${test_env_vars|} test/unittest/unittests
       - command: shell.exec
         params:
-          shell: bash
           working_dir: "wiredtiger/cmake_build"
+          shell: bash
           script: |
             set -o errexit
             set -o verbose
@@ -3359,6 +3406,7 @@ tasks:
       - command: shell.exec
         params:
           working_dir: "wiredtiger/cmake_build"
+          shell: bash
           script: |
             set -o errexit
             set -o verbose
@@ -3491,6 +3539,7 @@ tasks:
       - command: shell.exec
         params:
           working_dir: "wiredtiger/test/csuite"
+          shell: bash
           script: |
             set -o errexit
             set -o verbose
@@ -3557,6 +3606,7 @@ tasks:
       - command: shell.exec
         params:
           working_dir: "wiredtiger/cmake_build/bench/wtperf"
+          shell: bash
           script: |
             set -o errexit
             set -o verbose
@@ -3585,6 +3635,7 @@ tasks:
       - command: shell.exec
         params:
           working_dir: "wiredtiger/tools/memory-model-test"
+          shell: bash
           script: |
             set -o errexit
             set -o verbose
@@ -3826,6 +3877,7 @@ tasks:
       - command: shell.exec
         params:
           working_dir: "wiredtiger/test/evergreen"
+          shell: bash
           script: |
             set -o errexit
             set -o verbose
@@ -3922,6 +3974,7 @@ tasks:
       - command: shell.exec
         params:
           working_dir: "wiredtiger/bench/workgen/runner"
+          shell: bash
           script: |
             set -o errexit
             set -o verbose
@@ -3941,6 +3994,7 @@ tasks:
       - command: shell.exec
         params:
           working_dir: "wiredtiger/bench/workgen/runner"
+          shell: bash
           script: |
             set -o errexit
             set -o verbose
