Import wiredtiger: 38c058b832db0ae9e6ed50ae8068bbf17e0518d1 from branch mongodb-master (#58639)
Co-authored-by: wt-vendoring-bot <wt-vendoring-bot@mongodb.com>
GitOrigin-RevId: 4abc17989ff551070b18ccabc569b966383d0359

diff --git a/src/third_party/wiredtiger/test/evergreen_disagg.yml b/src/third_party/wiredtiger/test/evergreen_disagg.yml
--- a/src/third_party/wiredtiger/test/evergreen_disagg.yml
+++ b/src/third_party/wiredtiger/test/evergreen_disagg.yml
@@ -635,6 +635,27 @@ variables:
         vars:
           times: 50
 
+  - &schema-disagg-abort-test-disagg
+    depends_on:
+        - name: compile
+    exec_timeout_secs: 7200
+    commands:
+      - func: "fetch artifacts"
+      - command: shell.exec
+        params:
+          working_dir: "wiredtiger/cmake_build/test/csuite/schema_disagg_abort"
+          shell: bash
+          script: |
+            set -o errexit
+            set -o verbose
+            ${PREPARE_TEST_ENV}
+            build_dir=$(cd ../../../ && pwd)
+            for i in $(seq ${times|10}); do
+              echo "Iteration $i/${times|10}"
+              # Max out pool size (-s) and schema threads (-T) for maximum schema churn.
+              ./test_schema_disagg_abort -b "$build_dir" -s 64 -T 12 -t 300
+            done
+
   # Configure flags for builtins.
   - &configure_flags_with_builtins
     HAVE_BUILTIN_EXTENSION_LZ4: -DHAVE_BUILTIN_EXTENSION_LZ4=1
@@ -699,6 +720,10 @@ tasks:
   - <<: *timestamp-abort-test-disagg
     name: timestamp-abort-test-disagg-2
     tags: ["stress-test-disagg-fail"]
+
+  - <<: *schema-disagg-abort-test-disagg
+    name: schema-disagg-abort-test-disagg-1
+    tags: ["stress-test-disagg-fail", "stress-test-disagg-san-fail"]
 
 #######################################
 #            Buildvariants            #
