Import wiredtiger: c6962452f2c3469c039edfcafb7702450bf14c3b from branch mongodb-4.4
ref: 5bd9fdfc0b..c6962452f2
for: 4.3.3

WT-4886       Avoid depending on particular error message text for test_bug018
WT-5003       Migrate Jenkins “wiredtiger-test-race-condition-stress-sanitizer” job to Evergreen
WT-5024       Migrate Jenkins “wiredtiger-compatibility” job to Evergreen
WT-5081       Add support for ASan builds in the Python test suite
WT-5119       Birthmark records can be read as normal updates if reads race with checkpoints
WT-5165       Add cursor copy debug mode
WT-5199       Adding correctness tasks into rhel80 Evergreen build variant
WT-5261       coverage-report task timed out in Evergreen
WT-5334       Add testing coverage for static wt build
WT-5379       Missing varargs cleanup
WT-5410       WiredTiger formatted timestamp string buffer size is too small

diff --git a/src/third_party/wiredtiger/test/evergreen.yml b/src/third_party/wiredtiger/test/evergreen.yml
--- a/src/third_party/wiredtiger/test/evergreen.yml
+++ b/src/third_party/wiredtiger/test/evergreen.yml
@@ -1723,7 +1723,7 @@ tasks:
           extra_args: checkpoints=1 leak_memory=0 mmap=1 file_type=row alter=1 backups=1 compaction=1 data_extend=1 prepare=1 rebalance=1 salvage=1 statistics=1 statistics_server=1 verify=1
       - func: "format test"
         vars:
-          extra_args: checkpoints=1 leak_memory=0 mmap=1 file_type=row direct_io=1 firstfit=1 internal_key_truncation=1
+          extra_args: checkpoints=1 leak_memory=0 mmap=1 file_type=row firstfit=1 internal_key_truncation=1
       - func: "format test"
         vars:
           extra_args: leak_memory=0 mmap=1 file_type=row checkpoints=0 in_memory=1 reverse=1 truncate=1
@@ -1954,6 +1954,21 @@ tasks:
           format_test_script_args: -S
           times: 16
 
+  - name: race-condition-stress-sanitizer-test
+    # set an evergreen timeout of 25 hours
+    exec_timeout_secs: 90000
+    commands:
+      - func: "get project"
+      - func: "compile wiredtiger"
+        vars:
+          configure_env_vars: CC="/opt/mongodbtoolchain/v3/bin/clang -fsanitize=address" PATH=/opt/mongodbtoolchain/v3/bin:$PATH CFLAGS="-ggdb -fPIC -fno-omit-frame-pointer"
+          posix_configure_flags: --enable-diagnostic --with-builtins=lz4,snappy,zlib
+      - func: "format test script"
+        vars:
+          # set a format.sh timeout of 24 hours
+          format_test_script_args: -R -t 1440
+          test_env_vars: ASAN_OPTIONS="detect_leaks=1:abort_on_error=1:disable_coredump=0" ASAN_SYMBOLIZER_PATH=/opt/mongodbtoolchain/v3/bin/llvm-symbolizer
+
   - name: recovery-stress-test
     #set a 25 hours timeout
     exec_timeout_secs: 90000
@@ -2067,6 +2082,47 @@ tasks:
             cp ../../../bench/wtperf/split_heavy.wtperf .
             ./wtperf -O ./split_heavy.wtperf -o verbose=2
 
+  - name: static-wt-build-test
+    commands:
+      - func: "get project"
+      - func: "compile wiredtiger"
+        vars:
+          posix_configure_flags: --disable-shared --with-builtins=snappy,zlib
+      - command: shell.exec
+        params:
+          working_dir: "wiredtiger/build_posix"
+          shell: bash
+          script: |
+            set -o errexit
+            set -o verbose
+
+            # Delete wt util
+            rm -f wt
+            # Build static wt util
+            make CC='eval "g++ -static"' ${smp_command|}
+            # -V option displays Wiredtiger library version
+            ./wt -V
+
+            if [ $? -ne 0 ]; then
+              echo "Error, WT util is not generated or is not functioning"
+              exit 1
+            fi
+
+            ldd wt || wt_static_build=1
+
+            if [ $wt_static_build -ne 1 ]; then
+              echo "Error, WT util is not statically linked"
+              exit 1
+            fi
+
+  - name: compatibility-test-for-wiredtiger-releases
+    commands:
+      - func: "get project"
+      - command: subprocess.exec
+        params:
+          working_dir: "wiredtiger"
+          command: bash test/evergreen/compatibility_test_for_wiredtiger_releases.sh
+
 buildvariants:
 - name: ubuntu1804
   display_name: Ubuntu 18.04
@@ -2102,7 +2158,9 @@ buildvariants:
     - name: split-stress-test
     - name: format-stress-test
     - name: format-stress-smoke-test
+    - name: race-condition-stress-sanitizer-test
     - name: checkpoint-stress-test
+    - name: static-wt-build-test
 
 - name: ubuntu1804-compilers
   display_name: Ubuntu 18.04 Compilers
@@ -2168,6 +2226,22 @@ buildvariants:
     - name: unit-test
     - name: fops
     - name: time-shift-sensitivity-test
+    - name: compile-msan
+    - name: make-check-msan-test
+    - name: compile-ubsan
+    - name: ubsan-test
+    - name: linux-directio
+    - name: syscall-linux
+    - name: compile-asan
+    - name: make-check-asan-test
+    - name: checkpoint-filetypes-test
+    - name: unit-test-long
+    - name: spinlock-gcc-test
+    - name: spinlock-pthread-adaptive-test
+    - name: compile-wtperf
+    - name: wtperf-test
+    - name: ftruncate-test
+    - name: long-test
 
 - name: large-scale-test
   display_name: Large scale testing
@@ -2184,6 +2258,7 @@ buildvariants:
   - ubuntu1804-test
   tasks:
     - name: compatibility-test-for-mongodb-releases
+    - name: compatibility-test-for-wiredtiger-releases
 
 - name: windows-64
   display_name: Windows 64-bit
