Import wiredtiger: 2ed5785a5a17fe3397a86a3341c04ea057f9e3c9 from branch mongodb-master
ref: d9f9b08dfc..2ed5785a5a
for: 6.1.0-rc0

WT-8640       Upgrading the variant for cppsuite stress tests and tuning some configurations

diff --git a/src/third_party/wiredtiger/test/evergreen.yml b/src/third_party/wiredtiger/test/evergreen.yml
--- a/src/third_party/wiredtiger/test/evergreen.yml
+++ b/src/third_party/wiredtiger/test/evergreen.yml
@@ -347,15 +347,58 @@ functions:
         ${test_env_vars|} $CTEST -L check ${smp_command|} --output-on-failure ${check_args|} 2>&1
 
   "cppsuite test":
-    command: shell.exec
-    params:
-      # The tests need to be executed in the cppsuite directory as some required libraries have
-      # their paths defined relative to this directory.
-      working_dir: "wiredtiger/cmake_build/test/cppsuite"
-      script: |
-        set -o errexit
-        set -o verbose
-        ${test_env_vars|} ./run -t ${test_name} -C '${test_config}' -f ${test_config_filename} -l 2
+    - command: shell.exec
+      params:
+        # The tests need to be executed in the cppsuite directory as some required libraries have
+        # their paths defined relative to this directory.
+        # The below script saves the exit code from the test to use it later in this function. By
+        # doing this we can define our own custom artifact upload task without it being cancelled by
+        # the test failing.
+        # Additionally if the test fails perf statistics won't be uploaded as they may be invalid
+        # due to the test failure.
+        working_dir: "wiredtiger/cmake_build/test/cppsuite"
+        shell: bash
+        script: |
+          set -o verbose
+          ${test_env_vars|} ./run -t ${test_name} -C '${test_config}' -f ${test_config_filename} -l 2
+          exit_code=$?
+          echo "$exit_code" > cppsuite_exit_code
+          if [ "$exit_code" != 0 ]; then
+            echo "[{\"info\":{\"test_name\": \"${test_name}\"},\"metrics\": []}]" > ${test_name}.json
+          fi
+          exit 0
+    - command: perf.send
+      params:
+        file: ./wiredtiger/cmake_build/test/cppsuite/${test_name}.json
+    - command: archive.targz_pack
+      params:
+        target: archive.tgz
+        source_dir: wiredtiger/cmake_build/test/cppsuite
+        include:
+          - "./**"
+    - command: s3.put
+      params:
+        aws_secret: ${aws_secret}
+        aws_key: ${aws_key}
+        local_file: archive.tgz
+        bucket: build_external
+        permissions: public-read
+        content_type: application/tar
+        display_name: cppsuite-test
+        remote_file: wiredtiger/${build_variant}/${revision}/artifacts/${task_name}_${build_id}${postfix|}.tgz
+    # We remove the wiredtiger directory here to avoid to getting archived again by post tasks.
+    - command: shell.exec
+      params:
+        shell: bash
+        script: |
+          set -o verbose
+          if [ -f wiredtiger/cmake_build/test/cppsuite/cppsuite_exit_code ]; then
+            exit_code=`cat wiredtiger/cmake_build/test/cppsuite/cppsuite_exit_code`
+          else
+            exit_code=0
+          fi
+          rm -rf wiredtiger
+          exit "$exit_code"
 
   "wt2853_perf test":
     command: shell.exec
@@ -1065,9 +1108,6 @@ tasks:
           test_config: debug_mode=(cursor_copy=true)
           test_config_filename: configs/operations_test_default.txt
           test_name: operations_test
-      - func: "upload test stats"
-        vars:
-          test_path: test/cppsuite/operations_test
 
   - name: cppsuite-hs-cleanup-default
     tags: ["pull_request"]
@@ -1080,9 +1120,18 @@ tasks:
           test_config: debug_mode=(cursor_copy=true)
           test_config_filename: configs/hs_cleanup_default.txt
           test_name: hs_cleanup
-      - func: "upload test stats"
+
+  - name: cppsuite-burst-inserts-default
+    tags: ["pull_request"]
+    depends_on:
+      - name: compile
+    commands:
+      - func: "fetch artifacts"
+      - func: "cppsuite test"
         vars:
-          test_path: test/cppsuite/hs_cleanup
+          test_config: debug_mode=(cursor_copy=true)
+          test_config_filename: configs/burst_inserts_default.txt
+          test_name: burst_inserts
 
   - name: cppsuite-search-near-01-default
     tags: ["pull_request"]
@@ -1094,9 +1143,6 @@ tasks:
         vars:
           test_config_filename: configs/search_near_01_default.txt
           test_name: search_near_01
-      - func: "upload test stats"
-        vars:
-          test_path: test/cppsuite/search_near_01
 
   - name: cppsuite-search-near-02-default
     tags: ["pull_request"]
@@ -1108,9 +1154,6 @@ tasks:
         vars:
           test_config_filename: configs/search_near_02_default.txt
           test_name: search_near_02
-      - func: "upload test stats"
-        vars:
-          test_path: test/cppsuite/search_near_02
 
   - name: cppsuite-search-near-03-default
     tags: ["pull_request"]
@@ -1122,9 +1165,6 @@ tasks:
         vars:
           test_config_filename: configs/search_near_03_default.txt
           test_name: search_near_03
-      - func: "upload test stats"
-        vars:
-          test_path: test/cppsuite/search_near_03
 
   - name: cppsuite-bounded-cursor-perf-default
     tags: ["pull_request"]
@@ -1146,9 +1186,6 @@ tasks:
         vars:
           test_config_filename: configs/operations_test_stress.txt
           test_name: operations_test
-      - func: "upload test stats"
-        vars:
-          test_path: test/cppsuite/operations_test
 
   - name: cppsuite-hs-cleanup-stress
     depends_on:
@@ -1159,9 +1196,16 @@ tasks:
         vars:
           test_config_filename: configs/hs_cleanup_stress.txt
           test_name: hs_cleanup
-      - func: "upload test stats"
+
+  - name: cppsuite-burst-inserts-stress
+    depends_on:
+      - name: compile
+    commands:
+      - func: "fetch artifacts"
+      - func: "cppsuite test"
         vars:
-          test_path: test/cppsuite/hs_cleanup
+          test_config_filename: configs/burst_inserts_stress.txt
+          test_name: burst_inserts
 
   - name: cppsuite-search-near-01-stress
     depends_on:
@@ -1172,9 +1216,6 @@ tasks:
         vars:
           test_config_filename: configs/search_near_01_stress.txt
           test_name: search_near_01
-      - func: "upload test stats"
-        vars:
-          test_path: test/cppsuite/search_near_01
 
   - name: cppsuite-search-near-02-stress
     depends_on:
@@ -1185,9 +1226,6 @@ tasks:
         vars:
           test_config_filename: configs/search_near_02_stress.txt
           test_name: search_near_02
-      - func: "upload test stats"
-        vars:
-          test_path: test/cppsuite/search_near_02
 
   - name: cppsuite-search-near-03-stress
     depends_on:
@@ -1198,9 +1236,6 @@ tasks:
         vars:
           test_config_filename: configs/search_near_03_stress.txt
           test_name: search_near_03
-      - func: "upload test stats"
-        vars:
-          test_path: test/cppsuite/search_near_03
 
   - name: cppsuite-bounded-cursor-perf-stress
     depends_on:
@@ -1211,9 +1246,6 @@ tasks:
         vars:
           test_config_filename: configs/bounded_cursor_perf_stress.txt
           test_name: bounded_cursor_perf
-      - func: "upload test stats"
-        vars:
-          test_path: test/cppsuite/bounded_cursor_perf
 
   # End of cppsuite test tasks.
   # Start of csuite test tasks
@@ -4188,9 +4220,9 @@ buildvariants:
 
 - name: cppsuite-stress-tests
   display_name: "Cppsuite Stress Tests"
-  batchtime: 480 # 3 times a day
+  batchtime: 960 # Twice a day
   run_on:
-  - ubuntu2004-test
+  - ubuntu2004-medium
   expansions:
     test_env_vars:
       WT_TOPDIR=$(git rev-parse --show-toplevel)
@@ -4211,6 +4243,7 @@ buildvariants:
   tasks:
     - name: compile
     - name: cppsuite-operations-test-stress
+    - name: cppsuite-burst-inserts-stress
     - name: cppsuite-hs-cleanup-stress
     - name: cppsuite-search-near-01-stress
     - name: cppsuite-search-near-02-stress
