SERVER-35472 Avoid falling back to stderr in resmoke.py.
Instead a special return code of 75 is used to indicate that the log
output would otherwise be incomplete. The incomplete log output state is
ignored if all tests passed.

(cherry picked from commit 6ad26a359f7bc366da13d433ed612ff22f69d323)
(cherry picked from commit 8fae595c44b14aa61951ba413e293449c2b49866)

diff --git a/etc/evergreen.yml b/etc/evergreen.yml
--- a/etc/evergreen.yml
+++ b/etc/evergreen.yml
@@ -600,6 +600,7 @@ functions:
       type: test
       params:
         working_dir: src
+        shell: bash
         script: |
           set -o errexit
           set -o verbose
@@ -695,6 +696,7 @@ functions:
           # The "resmoke_wrapper" expansion is used by the 'burn_in_tests' task to wrap the resmoke.py
           # invocation. It doesn't set any environment variables and should therefore come last in
           # this list of expansions.
+          set +o errexit
           PATH="$path_value"                              \
               AWS_PROFILE=${aws_profile_remote}           \
               ${gcov_environment}                         \
@@ -720,8 +722,33 @@ functions:
                   --archiveFile=archive.json              \
                   --reportFile=report.json                \
                   --perfReportFile=perf.json
+          resmoke_exit_code=$?
+          set -o errexit
 
+          # 74 is exit code for IOError on POSIX systems, which is raised when the machine is
+          # shutting down.
+          #
+          # 75 is exit code resmoke.py uses when the log output would be incomplete due to failing
+          # to communicate with logkeeper.
+          if [[ $resmoke_exit_code = 74 || $resmoke_exit_code = 75 ]]; then
+            echo $resmoke_exit_code > run_tests_infrastructure_failure
+            exit 0
+          fi
+          exit $resmoke_exit_code
           fi # end if ${disable_unit_tests}
+
+      # The existence of the "run_tests_infrastructure_failure" file indicates this failure isn't
+      # directly actionable. We use type=setup rather than type=system or type=test for this command
+      # because we don't intend for any human to look at this failure.
+    - command: shell.exec
+      type: setup
+      params:
+        working_dir: src
+        script: |
+          set -o verbose
+          if [ -f run_tests_infrastructure_failure ]; then
+            exit $(cat run_tests_infrastructure_failure)
+          fi
 
   "scons compile" :
     command: shell.exec
