SERVER-28222 Add Jepsen read-concern-majority test to evergreen

diff --git a/etc/evergreen.yml b/etc/evergreen.yml
--- a/etc/evergreen.yml
+++ b/etc/evergreen.yml
@@ -624,27 +624,30 @@ functions:
           end_time=$(date +%s)
           elapsed_secs=$((end_time-start_time))
           # Since we cannot use PIPESTATUS to get the exit code from the "lein run ..." pipe in dash shell,
-          # we will check the output for success, failure or setup error.
+          # we will check the output for success, failure or setup error. Note that 'grep' returns with exit code
+          # 0 if it finds a match, and exit code 1 if no match is found.
           grep -q "Everything looks good" jepsen_${task_name}_${execution}.log
-          exit_code=$?
-          if [ $exit_code -eq 0 ]; then
+          grep_exit_code=$?
+          if [ $grep_exit_code -eq 0 ]; then
             status='"pass"'
             failures=0
+            final_exit_code=0
           else
             grep -q "Analysis invalid" jepsen_${task_name}_${execution}.log
-            exit_code=$?
-            if [ $exit_code -eq 0 ]; then
+            grep_exit_code=$?
+            if [ $grep_exit_code -eq 0 ]; then
               status='"fail"'
               failures=1
+              final_exit_code=1
             else
               # If the failure is due to setup, then this is considered a system failure.
-              echo $exit_code > jepsen_system_failure_${task_name}_${execution}
+              echo $grep_exit_code > jepsen_system_failure_${task_name}_${execution}
               exit 0
             fi
           fi
           # Create report.json
-          echo "{\"failures\": $failures, \"results\": [{\"status\": $status, \"exit_code\": $exit_code, \"test_file\": \"${task_name}\", \"start\": $start_time, \"end\": $end_time, \"elapsed\": $elapsed_secs}]}" > ../../report.json
-          exit $exit_code
+          echo "{\"failures\": $failures, \"results\": [{\"status\": $status, \"exit_code\": $exit_code, \"test_file\": \"${task_name}\", \"start\": $start_time, \"end\": $end_time, \"elapsed\": $elapsed_secs}]}" > ../report.json
+          exit $final_exit_code
     - command: shell.exec
       params:
         working_dir: src/jepsen-mongodb
@@ -1487,6 +1490,31 @@ tasks:
       jepsen_read_concern: --read-concern linearizable
       jepsen_storage_engine: --storage-engine wiredTiger
       jepsen_test_name: set
+
+- <<: *run_jepsen_template
+  # We only run this test on wiredTiger since MMAPv1 doesn't support majority read concern.
+  name: jepsen_read-concern-majority_WT
+  commands:
+  - func: "do setup"
+  - func: "do jepsen setup"
+  - func: "run jepsen test"
+    vars:
+      <<: *jepsen_config_vars
+      jepsen_storage_engine: --storage-engine wiredTiger
+      jepsen_test_name: read-concern-majority
+
+- <<: *run_jepsen_template
+  # We only run this test on wiredTiger since MMAPv1 doesn't support majority read concern.
+  name: jepsen_read-concern-majority_w1_WT
+  commands:
+  - func: "do setup"
+  - func: "do jepsen setup"
+  - func: "run jepsen test"
+    vars:
+      <<: *jepsen_config_vars
+      jepsen_storage_engine: --storage-engine wiredTiger
+      jepsen_test_name: read-concern-majority
+      jepsen_write_concern: --write-concern w1
 
 ## jstestfuzz mmapv1 ##
 - <<: *jstestfuzz_template
@@ -4093,6 +4121,12 @@ buildvariants:
     distros:
     - ubuntu1404-jepsen
   - name: jepsen_set_linearizableRead_WT
+    distros:
+    - ubuntu1404-jepsen
+  - name: jepsen_read-concern-majority_WT
+    distros:
+    - ubuntu1404-jepsen
+  - name: jepsen_read-concern-majority_w1_WT
     distros:
     - ubuntu1404-jepsen
   - name: jsCore
@@ -6785,6 +6819,12 @@ buildvariants:
     distros:
     - ubuntu1404-jepsen
   - name: jepsen_set_linearizableRead_WT
+    distros:
+    - ubuntu1404-jepsen
+  - name: jepsen_read-concern-majority_WT
+    distros:
+    - ubuntu1404-jepsen
+  - name: jepsen_read-concern-majority_w1_WT
     distros:
     - ubuntu1404-jepsen
   - name: jsCore
