SERVER-33009 AWS credential profiles in evergreen.yml

diff --git a/etc/evergreen.yml b/etc/evergreen.yml
--- a/etc/evergreen.yml
+++ b/etc/evergreen.yml
@@ -367,7 +367,7 @@ functions:
           sleep 60
         done
 
-  "setup credentials" : &setup_credentials
+  "set up credentials" : &set_up_credentials
     command: shell.exec
     params:
       working_dir: src
@@ -380,6 +380,53 @@ functions:
         build_num=${builder_num}
         build_phase='${task_name}_${execution}'
         END_OF_CREDS
+
+  "set up remote credentials": &set_up_remote_credentials
+    command: shell.exec
+    params:
+      silent: true
+      script: |
+        set -o errexit
+
+        # Since the macros 'private_key_remote' and 'private_key_file' are not always defined
+        # we default to /dev/null to avoid syntax errors of an empty expansion.
+        if [ ! -z "${private_key_remote}" ] && [ ! -z "${private_key_file}" ] ; then
+          mkdir -p ~/.ssh
+          echo -n "${private_key_remote}" > ${private_key_file|/dev/null}
+          chmod 0600 ${private_key_file|/dev/null}
+        fi
+
+        if [ ! -d ~.aws ]; then
+          mkdir -p ~/.aws
+        fi
+
+        # If ${aws_profile_remote} is not specified then the config & credentials are
+        # stored in the 'default' profile.
+        aws_profile="${aws_profile_remote|default}"
+
+        # The profile in the config file is specified as [profile <profile>], except
+        # for [default], see http://boto3.readthedocs.io/en/latest/guide/configuration.html
+        if [ $aws_profile = "default" ] ; then
+          aws_profile_config="[default]"
+        else
+          aws_profile_config="[profile $aws_profile]"
+        fi
+        cat <<EOF >> ~/.aws/config
+        $aws_profile_config
+        region = us-east-1
+        EOF
+
+        # The profile in the credentials file is specified as [<profile>].
+        cat <<EOF >> ~/.aws/credentials
+        [$aws_profile]
+        aws_access_key_id = ${aws_key_remote}
+        aws_secret_access_key = ${aws_secret_remote}
+        EOF
+
+        cat <<EOF > ~/.boto
+        [Boto]
+        https_validate_certificates = False
+        EOF
 
   "upload debugsymbols" : &upload_debugsymbols
     command: s3.put
@@ -490,7 +537,7 @@ functions:
   - *extract_binaries
   - *check_binary_version
   - *get_buildnumber
-  - *setup_credentials
+  - *set_up_credentials
   - *run_diskstats
   - *monitor_process_threads
   - *collect_system_resource_info
@@ -498,7 +545,7 @@ functions:
   "do benchmark setup" :
   - *git_get_project
   - *get_buildnumber
-  - *setup_credentials
+  - *set_up_credentials
   - *fetch_benchmarks
 
   "set up virtualenv" :
@@ -518,126 +565,137 @@ functions:
           virtualenv --python $python_loc --system-site-packages ./venv
 
   "run tests" :
-    command: shell.exec
-    type: test
-    params:
-      working_dir: src
-      script: |
-        set -o errexit
-        set -o verbose
+    - command: expansions.update
+      params:
+        updates:
+        - key: aws_key_remote
+          value: ${mongodatafiles_aws_key}
+        - key: aws_profile_remote
+          value: mongodata_aws
+        - key: aws_secret_remote
+          value: ${mongodatafiles_aws_secret}
+    - *set_up_remote_credentials
+    - command: shell.exec
+      type: test
+      params:
+        working_dir: src
+        script: |
+          set -o errexit
+          set -o verbose
 
-        # Set the TMPDIR environment variable to be a directory in the task's working
-        # directory so that temporary files created by processes spawned by resmoke.py get
-        # cleaned up after the task completes. This also ensures the spawned processes
-        # aren't impacted by limited space in the mount point for the /tmp directory.
-        export TMPDIR="${workdir}/tmp"
-        mkdir -p $TMPDIR
+          # Set the TMPDIR environment variable to be a directory in the task's working
+          # directory so that temporary files created by processes spawned by resmoke.py get
+          # cleaned up after the task completes. This also ensures the spawned processes
+          # aren't impacted by limited space in the mount point for the /tmp directory.
+          export TMPDIR="${workdir}/tmp"
+          mkdir -p $TMPDIR
 
-        if [ ${disable_unit_tests|false} = "false" ]; then
+          if [ ${disable_unit_tests|false} = "false" ]; then
 
-        # activate the virtualenv if it has been set up
-        ${activate_virtualenv}
+          # activate the virtualenv if it has been set up
+          ${activate_virtualenv}
 
-        if [ -f /proc/self/coredump_filter ]; then
-          # Set the shell process (and its children processes) to dump ELF headers (bit 4),
-          # anonymous shared mappings (bit 1), and anonymous private mappings (bit 0).
-          echo 0x13 > /proc/self/coredump_filter
+          if [ -f /proc/self/coredump_filter ]; then
+            # Set the shell process (and its children processes) to dump ELF headers (bit 4),
+            # anonymous shared mappings (bit 1), and anonymous private mappings (bit 0).
+            echo 0x13 > /proc/self/coredump_filter
 
-          if [ -f /sbin/sysctl ]; then
-            # Check that the core pattern is set explicitly on our distro image instead
-            # of being the OS's default value. This ensures that coredump names are consistent
-            # across distros and can be picked up by Evergreen.
-            core_pattern=$(/sbin/sysctl -n "kernel.core_pattern")
-            if [ "$core_pattern" = "dump_%e.%p.core" ]; then
-              echo "Enabling coredumps"
-              ulimit -c unlimited
+            if [ -f /sbin/sysctl ]; then
+              # Check that the core pattern is set explicitly on our distro image instead
+              # of being the OS's default value. This ensures that coredump names are consistent
+              # across distros and can be picked up by Evergreen.
+              core_pattern=$(/sbin/sysctl -n "kernel.core_pattern")
+              if [ "$core_pattern" = "dump_%e.%p.core" ]; then
+                echo "Enabling coredumps"
+                ulimit -c unlimited
+              fi
             fi
           fi
-        fi
 
-        extra_args=""
-        if [ ${run_multiple_jobs|false} = true ]; then
-          processor_architecture=$(uname -m)
-          num_jobs_available=${num_jobs_available|1}
-          # Reduce the number of available jobs by half when running any sharding*, replica_sets*
-          # and select jsCore passthrough tasks on Windows and ARM to avoid overwhelming test hosts.
-          if [ "Windows_NT" = "$OS" ] || [ "aarch64" = $processor_architecture ]; then
-            case "${task_name}" in
-            replica_sets_initsync_jscore_passthrough          \
-            |replica_sets_initsync_static_jscore_passthrough  \
-            |replica_sets_resync_static_jscore_passthrough    \
-            |replica_sets*                           \
-            |sharding*                              \
-            )
-              num_jobs_available=$((${num_jobs_available|2} / 2))
-              echo "Reducing jobs from ${num_jobs_available|1} to $num_jobs_available"
-              ;;
-            esac
+          extra_args=""
+          if [ ${run_multiple_jobs|false} = true ]; then
+            processor_architecture=$(uname -m)
+            num_jobs_available=${num_jobs_available|1}
+            # Reduce the number of available jobs by half when running any sharding*, replica_sets*
+            # and select jsCore passthrough tasks on Windows and ARM to avoid overwhelming test hosts.
+            if [ "Windows_NT" = "$OS" ] || [ "aarch64" = $processor_architecture ]; then
+              case "${task_name}" in
+              replica_sets_initsync_jscore_passthrough          \
+              |replica_sets_initsync_static_jscore_passthrough  \
+              |replica_sets_resync_static_jscore_passthrough    \
+              |replica_sets*                           \
+              |sharding*                              \
+              )
+                num_jobs_available=$((${num_jobs_available|2} / 2))
+                echo "Reducing jobs from ${num_jobs_available|1} to $num_jobs_available"
+                ;;
+              esac
+            fi
+
+            if [ ${max_jobs|0} -gt 0 ] && [ ${max_jobs|0} -lt $num_jobs_available ]; then
+              extra_args="$extra_args --jobs=${max_jobs}"
+            else
+              extra_args="$extra_args --jobs=$num_jobs_available"
+            fi
           fi
 
-          if [ ${max_jobs|0} -gt 0 ] && [ ${max_jobs|0} -lt $num_jobs_available ]; then
-            extra_args="$extra_args --jobs=${max_jobs}"
+          if [ ${should_shuffle|true} = true ]; then
+            extra_args="$extra_args --shuffle"
+          fi
+
+          if [ ${continue_on_failure|true} = true ]; then
+            extra_args="$extra_args --continueOnFailure"
+          fi
+
+          # Default storageEngineCacheSizeGB to 1. Override on individual test config if needed.
+          # resmoke will assign to the appropriate parameter on storage engines that support it.
+          set +o errexit
+          echo "${resmoke_args}" | grep -q storageEngineCacheSizeGB
+          if [ $? -eq 1 ]; then
+            extra_args="$extra_args --storageEngineCacheSizeGB=1"
+          fi
+          set -o errexit
+
+          path_value="$PATH"
+          if [ ${variant_path_suffix} ]; then
+            path_value="$path_value:${variant_path_suffix}"
+          fi
+          if [ ${task_path_suffix} ]; then
+            path_value="$path_value:${task_path_suffix}"
+          fi
+
+          if [ "${is_patch|}" = "true" ]; then
+            extra_args="$extra_args --tagFile=etc/test_lifecycle.yml --patchBuild"
           else
-            extra_args="$extra_args --jobs=$num_jobs_available"
+            extra_args="$extra_args --tagFile=etc/test_retrial.yml"
           fi
-        fi
 
-        if [ ${should_shuffle|true} = true ]; then
-          extra_args="$extra_args --shuffle"
-        fi
+          # The "resmoke_wrapper" expansion is used by the 'burn_in_tests' task to wrap the resmoke.py
+          # invocation. It doesn't set any environment variables and should therefore come last in
+          # this list of expansions.
+          PATH="$path_value"                              \
+              AWS_PROFILE=${aws_profile_remote}           \
+              ${gcov_environment}                         \
+              ${rlp_environment}                          \
+              ${lang_environment}                         \
+              ${san_options}                              \
+              ${san_symbolizer}                           \
+              ${snmp_config_path}                         \
+              ${resmoke_wrapper}                          \
+              $python buildscripts/evergreen_run_tests.py \
+                  ${resmoke_args}                         \
+                  $extra_args                             \
+                  ${test_flags}                           \
+                  --log=buildlogger                       \
+                  --staggerJobs=on                        \
+                  --taskId=${task_id}                     \
+                  --taskName=${task_name}                 \
+                  --variantName=${build_variant}          \
+                  --distroId=${distro_id}                 \
+                  --reportFile=report.json                \
+                  --perfReportFile=perf.json
 
-        if [ ${continue_on_failure|true} = true ]; then
-          extra_args="$extra_args --continueOnFailure"
-        fi
-
-        # Default storageEngineCacheSizeGB to 1. Override on individual test config if needed.
-        # resmoke will assign to the appropriate parameter on storage engines that support it.
-        set +o errexit
-        echo "${resmoke_args}" | grep -q storageEngineCacheSizeGB
-        if [ $? -eq 1 ]; then
-          extra_args="$extra_args --storageEngineCacheSizeGB=1"
-        fi
-        set -o errexit
-
-        path_value="$PATH"
-        if [ ${variant_path_suffix} ]; then
-          path_value="$path_value:${variant_path_suffix}"
-        fi
-        if [ ${task_path_suffix} ]; then
-          path_value="$path_value:${task_path_suffix}"
-        fi
-
-        if [ "${is_patch|}" = "true" ]; then
-          extra_args="$extra_args --tagFile=etc/test_lifecycle.yml --patchBuild"
-        else
-          extra_args="$extra_args --tagFile=etc/test_retrial.yml"
-        fi
-
-        # The "resmoke_wrapper" expansion is used by the 'burn_in_tests' task to wrap the resmoke.py
-        # invocation. It doesn't set any environment variables and should therefore come last in
-        # this list of expansions.
-        PATH="$path_value"                              \
-            ${gcov_environment}                         \
-            ${rlp_environment}                          \
-            ${lang_environment}                         \
-            ${san_options}                              \
-            ${san_symbolizer}                           \
-            ${snmp_config_path}                         \
-            ${resmoke_wrapper}                          \
-            $python buildscripts/evergreen_run_tests.py \
-                ${resmoke_args}                         \
-                $extra_args                             \
-                ${test_flags}                           \
-                --log=buildlogger                       \
-                --staggerJobs=on                        \
-                --taskId=${task_id}                     \
-                --taskName=${task_name}                 \
-                --variantName=${build_variant}          \
-                --distroId=${distro_id}                 \
-                --reportFile=report.json                \
-                --perfReportFile=perf.json
-
-        fi # end if ${disable_unit_tests}
+          fi # end if ${disable_unit_tests}
 
   "scons compile" :
     command: shell.exec
@@ -759,7 +817,7 @@ functions:
           end_time=$(date +%s)
           elapsed_secs=$((end_time-start_time))
           # Since we cannot use PIPESTATUS to get the exit code from the "lein run ..." pipe in dash shell,
-          # we will check the output for success, failure or setup error. Note that 'grep' returns with exit code
+          # we will check the output for success, failure or set up error. Note that 'grep' returns with exit code
           # 0 if it finds a match, and exit code 1 if no match is found.
           grep -q "Everything looks good" jepsen_${task_name}_${execution}.log
           grep_exit_code=$?
@@ -1092,38 +1150,6 @@ functions:
           kill_process "$process"
         done
 
-  "set up remote credentials":
-    command: shell.exec
-    params:
-      silent: true
-      script: |
-        set -o errexit
-
-        # Since the macros 'private_key_remote' and 'private_key_file' are not always defined
-        # we default to /dev/null to avoid syntax errors of an empty expansion.
-        if [ ! -z "${private_key_remote}" ] && [ ! -z "${private_key_file}" ] ; then
-          mkdir -p ~/.ssh
-          echo -n "${private_key_remote}" > ${private_key_file|/dev/null}
-          chmod 0600 ${private_key_file|/dev/null}
-        fi
-
-        mkdir -p ~/.aws
-        cat <<EOF > ~/.aws/config
-        [default]
-        region = us-east-1
-        EOF
-
-        cat <<EOF > ~/.aws/credentials
-        [default]
-        aws_access_key_id = ${aws_key_remote}
-        aws_secret_access_key = ${aws_secret_remote}
-        EOF
-
-        cat <<EOF > ~/.boto
-        [Boto]
-        https_validate_certificates = False
-        EOF
-
   "run kitchen":
     command: shell.exec
     type: test
@@ -1132,13 +1158,6 @@ functions:
       working_dir: src/buildscripts/package_test
       script: |
         set -o errexit
-
-        # Override the aws credentials with the kitchen specific credentials
-        cat <<EOF > ~/.aws/credentials
-        [default]
-        aws_access_key_id = ${kitchen_aws_key}
-        aws_secret_access_key = ${kitchen_aws_secret}
-        EOF
 
         export KITCHEN_ARTIFACTS_URL="https://s3.amazonaws.com/mciuploads/${project}/${build_variant}/${revision}/artifacts/${build_id}.tgz"
         export KITCHEN_SECURITY_GROUP="${kitchen_security_group}"
@@ -1377,7 +1396,7 @@ functions:
         working_dir: src
         script: |
           set -o errexit
-          # Setup virtualenv and install python modules on remote, if required
+          # Set up virtualenv and install python modules on remote, if required
           if [ ! -z "${virtualenv_requirements}" ]; then
             cmds="python_loc=\$(which ${python|/opt/mongodbtoolchain/v2/bin/python2})"
             cmds="$cmds; if [ \"Windows_NT\" = \"$OS\" ]; then python_loc=\$(cygpath -w \$python_loc); fi"
@@ -1401,7 +1420,7 @@ functions:
         script: |
           set -o errexit
           ${set_sudo}
-          # Setup curator to collect system & process stats on remote.
+          # Set up curator to collect system & process stats on remote.
           if [ "Windows_NT" = "$OS" ]; then
              variant=windows-64
           else
@@ -2208,7 +2227,7 @@ tasks:
     - command: manifest.load
     - func: "git get project"
     - func: "get buildnumber"
-    - func: "setup credentials"
+    - func: "set up credentials"
     - func: "fetch and build OpenSSL"
     - func: "build new tools" # noop if ${newtools} is not "true"
     - func: "build rocksdb" # noop if ${build_rocksdb} is not "true"
@@ -2353,7 +2372,7 @@ tasks:
     - command: manifest.load
     - func: "git get project"
     - func: "get buildnumber"
-    - func: "setup credentials"
+    - func: "set up credentials"
     - func: "fetch and build OpenSSL"
     - func: "build new tools" # noop if ${newtools} is not "true"
     - func: "build rocksdb" # noop if ${build_rocksdb} is not "true"
@@ -2393,7 +2412,7 @@ tasks:
     - command: manifest.load
     - func: "git get project"
     - func: "get buildnumber"
-    - func: "setup credentials"
+    - func: "set up credentials"
     - func: "fetch and build OpenSSL"
     - func: "generate compile expansions"
     # Then we load the generated version data into the agent so we can use it in task definitions
@@ -5218,7 +5237,7 @@ tasks:
       script: |
         set -o errexit
 
-        # Setup the git ssh private key
+        # Set up the git ssh private key
         mkdir -p ~/.ssh
         echo -n "${testlifecycle_ssh_key}" > ~/.ssh/test_lifecycle.pem
         chmod 0600 ~/.ssh/test_lifecycle.pem
