SERVER-27234 Evergreen task disk statistics improvement

diff --git a/etc/evergreen.yml b/etc/evergreen.yml
--- a/etc/evergreen.yml
+++ b/etc/evergreen.yml
@@ -254,12 +254,29 @@ functions:
         if [ "Windows_NT" = "$OS" ]; then
             typeperf -qx PhysicalDisk | grep Disk | grep -v _Total > disk_counters.txt
             typeperf -cf disk_counters.txt -si 5 -o mongo-diskstats
-        # See if iostat is available.
-        elif which iostat 2>&1 > /dev/null; then
-            iostat -d 5 > mongo-diskstats
-        # Fall back to vmstat if iostat is not available.
+        # Solaris: iostat -T d option for timestamp.
+        elif iostat -T d > /dev/null 2>&1; then
+            iostat -T d -Mx 5 > mongo-diskstats
+        # Linux: iostat -t option for timestamp.
+        elif iostat -tdmx > /dev/null 2>&1; then
+            iostat -tdmx 5 > mongo-diskstats
+        # OSX: Simulate the iostat timestamp.
+        elif iostat -d > /dev/null 2>&1; then
+            while [ 1 ]
+            do
+                date +'%m/%d/%Y %I:%M:%S %p' >> mongo-diskstats
+                iostat -d >> mongo-diskstats
+                printf "/n" >> mongo-diskstats
+                sleep 5
+            done
+        # Check if vmstat -t is available.
+        elif vmstat -td  > /dev/null 2>&1; then
+            vmstat -td 5 > mongo-diskstats
+        # Check if vmstat -T d is available.
+        elif vmstat -T d > /dev/null 2>&1; then
+            vmstat -T d 5 > mongo-diskstats
         else
-            vmstat -d 5 > mongo-diskstats
+            printf "Cannot collect mongo-diskstats on this platform\n"
         fi
 
   # Run a monitor process as a background, system task to periodically
@@ -727,13 +744,13 @@ functions:
         cp -f src/mongo/db/modules/enterprise/docs/mongod.conf.master snmpconf/mongod.conf
 
   "cleanup environment" :
-    - command: shell.exec
-      params:
-        script: |
-          set -o errexit
-          set -o verbose
+    command: shell.exec
+    params:
+      script: |
+        set -o errexit
+        set -o verbose
 
-          rm -rf src /data/db/* mongo-coredumps.tgz ~/.aws
+        rm -rf src /data/db/* mongo-diskstats* mongo-coredumps.tgz ~/.aws
 
   "kill processes" :
     command: shell.exec
