SERVER-24236 Add report.json from Jepsen test task

diff --git a/etc/evergreen.yml b/etc/evergreen.yml
--- a/etc/evergreen.yml
+++ b/etc/evergreen.yml
@@ -380,10 +380,22 @@ functions:
         working_dir: src/jepsen/mongodb
         script: |
           set -o verbose
+          start_time=$(date +%s)
           lein run --tarball "file:///root/mongo-binaries.tgz" ${jepsen_protocol_version} ${jepsen_read_concern} ${jepsen_read_with_find_and_modify} ${jepsen_storage_engine} ${jepsen_time_limit} ${jepsen_write_concern}
-          status=$?
-          # Create status file, so we can signal an error, after the archive/put steps have run.
-          echo $status > ../../jepsen-status-${task_id}-${execution}.txt
+          exit_code=$?
+          # Create exit_code file, so we can signal an error, after the archive/put steps have run.
+          echo $exit_code > ../../jepsen-exit_code-${task_id}-${execution}.txt
+          end_time=$(date +%s)
+          elapsed_secs=$((end_time-start_time))
+          if [ $exit_code -eq 0 ]; then
+            status='"pass"'
+            failures=0
+          else
+            status='"fail"'
+            failures=1
+          fi
+          # Create report.json
+          echo "{\"failures\": $failures, \"results\": [{\"status\": $status, \"exit_code\": $exit_code, \"test_file\": \"${task_name}\", \"start\": $start_time, \"end\": $end_time, \"elapsed\": $elapsed_secs}]}" > ../../report.json
     - command: archive.targz_pack
       params:
         target: "src/jepsen-results.tgz"
@@ -405,7 +417,7 @@ functions:
       params:
         working_dir: src
         script: |
-          exit $(cat jepsen-status-${task_id}-${execution}.txt)
+          exit $(cat jepsen-exit_code-${task_id}-${execution}.txt)
 
   "run jstestfuzz":
     - command: shell.exec
