Revert "SERVER-55300 Implement expansions handling for standalone shell"
This reverts commit 24aa56a6ed096a470f1380709b87084ff74106b5.

diff --git a/etc/evergreen.yml b/etc/evergreen.yml
--- a/etc/evergreen.yml
+++ b/etc/evergreen.yml
@@ -382,6 +382,7 @@ variables:
 #######################################
 
 functions:
+
   "remove files": &remove_files
     command: shell.exec
     params:
@@ -432,7 +433,7 @@ functions:
   "git get project": &git_get_project
     command: git.get_project
     params:
-      directory: src
+      directory: ${git_project_directory|src}
       revisions: # for each module include revision as <module_name> : ${<module_name>_rev}
         enterprise: ${enterprise_rev}
         wtdevelop: ${wtdevelop_rev}
@@ -1096,6 +1097,8 @@ functions:
           # exit immediately if virtualenv is not found
           set -o errexit
 
+          virtualenv_loc=$(which ${virtualenv|virtualenv})
+
           python_loc=$(which ${python|/opt/mongodbtoolchain/v3/bin/python3})
           venv_dir="${workdir}/venv"
           "$python_loc" -m venv --system-site-packages "$venv_dir"
@@ -1709,32 +1712,112 @@ functions:
           - "./src/evergreen/check_run_tests_infrastructure_failure.sh"
 
   "scons lint":
-    - command: expansions.write
-      params:
-        file: expansions.yml
-    - command: subprocess.exec
+    - command: shell.exec
       type: test
       params:
-        binary: bash
-        args:
-          - "src/evergreen/scons_lint.sh"
-        env:
-          python: ${python}
-          workdir: ${workdir}
+        working_dir: src
+        shell: bash
+        script: |
+          set -o errexit
+          set -o verbose
+
+          ${activate_virtualenv}
+          export MYPY="$(
+            if which cygpath 2>/dev/null; then
+                PATH+=":$(cypath "${workdir}")/venv_3/Scripts"
+            else
+                PATH+=":${workdir}/venv_3/bin"
+            fi
+            PATH+=':/opt/mongodbtoolchain/v3/bin'
+            which mypy
+          )"
+          echo "Found mypy executable at '$MYPY'"
+          export extra_flags=""
+          if [[ ${is_patch|false} == "true" ]]; then
+            extra_flags="--lint-scope=changed"
+          fi
+
+          ${compile_env|} python3 ./buildscripts/scons.py ${compile_flags|} $extra_flags --stack-size=1024 GITDIFFFLAGS="${revision}" REVISION="${revision|}" ENTERPRISE_REV="${enterprise_rev|}" ${targets}
 
   "scons compile":
-    - command: expansions.write
-      params:
-        file: expansions.yml
-    - command: subprocess.exec
-      type: test
-      params:
-        binary: bash
-        args:
-          - "src/evergreen/scons_compile.sh"
-        env:
-          python: ${python}
-          workdir: ${workdir}
+    command: shell.exec
+    type: test
+    params:
+      working_dir: src
+      shell: bash
+      script: |
+        set -o errexit
+        set -o verbose
+
+        rm -rf ${install_directory|/data/mongo-install-directory}
+
+        # Use hardlinks to reduce the disk space impact of installing
+        # all of the binaries and associated debug info.
+
+        # The expansion here is a workaround to let us set a different install-action
+        # for tasks that don't support the one we set here. A better plan would be
+        # to support install-action for Ninja builds directly.
+        # TODO: https://jira.mongodb.org/browse/SERVER-48203
+        extra_args="--install-action=${task_install_action|hardlink}"
+
+        # By default, limit link jobs to one quarter of our overall -j
+        # concurrency unless locally overridden. We do this because in
+        # static link environments, the memory consumption of each
+        # link job is so high that without constraining the number of
+        # links we are likely to OOM or thrash the machine. Dynamic
+        # builds, where htis is not a concern, override this value.
+        echo "Changing SCons to run with --jlink=${num_scons_link_jobs_available|0.25}"
+        extra_args="$extra_args --jlink=${num_scons_link_jobs_available|0.25}"
+
+        if [ "${scons_cache_scope|}" = "shared" ]; then
+          extra_args="$extra_args --cache-debug=scons_cache.log"
+        fi
+
+        # Conditionally enable scons time debugging
+        if [ "${show_scons_timings|true}" = "true" ]; then
+          extra_args="$extra_args --debug=time"
+        fi
+
+        # Build packages where the upload tasks expect them
+        if [ -n "${git_project_directory|}" ]; then
+            extra_args="$extra_args PKGDIR=${git_project_directory}"
+        else
+            extra_args="$extra_args PKGDIR=${workdir}/src"
+        fi
+
+        # If we are doing a patch build or we are building a non-push
+        # build on the waterfall, then we don't need the --release
+        # flag. Otherwise, this is potentially a build that "leaves
+        # the building", so we do want that flag. The non --release
+        # case should auto enale the faster decider when
+        # applicable. Furthermore, for the non --release cases we can
+        # accelerate the build slightly for situations where we invoke
+        # SCons multiple times on the same machine by allowing SCons
+        # to assume that implicit dependencies are cacheable across
+        # runs.
+        if [ "${is_patch|false}" = "true" ] || [ -z "${push_bucket|}" ] || [ "${compiling_for_test|false}" = "true" ]; then
+          extra_args="$extra_args --implicit-cache --build-fast-and-loose=on"
+        else
+          extra_args="$extra_args --release"
+        fi
+
+        if [ "Windows_NT" = "$OS" ]; then
+          vcvars="$(vswhere -latest -property installationPath | tr '\\' '/' | dos2unix.exe)/VC/Auxiliary/Build/"
+          export PATH="$(echo "$(cd "$vcvars" && cmd /C "vcvarsall.bat amd64 && C:/cygwin/bin/bash -c 'echo \$PATH'")" | tail -n +6)":$PATH
+        fi
+
+        ${activate_virtualenv}
+
+        ${compile_env|} $python ./buildscripts/scons.py                                     \
+            ${compile_flags|} ${task_compile_flags|} ${task_compile_flags_extra|}           \
+            ${scons_cache_args|} $extra_args                                                \
+            ${targets} MONGO_VERSION=${version} ${patch_compile_flags|} || exit_status=$?
+
+        # If compile fails we do not run any tests
+        if [[ $exit_status -ne 0 ]]; then
+          touch ${skip_tests}
+        fi
+        exit $exit_status
 
   "generate compile expansions":
     command: shell.exec
