SERVER-25318: remove perf task dependency

diff --git a/etc/system_perf.yml b/etc/system_perf.yml
--- a/etc/system_perf.yml
+++ b/etc/system_perf.yml
@@ -9,19 +9,6 @@ post:
       params:
         file_location: work/report.json
     - command: shell.cleanup
-    - command: shell.exec
-      # destroy the cluster
-      params:
-        working_dir: work
-        script: |
-          set -e
-          set -o verbose
-          source ./dsienv.sh
-          if [ ! -f "test.success" ]; then
-            yes yes | ./terraform destroy
-            if [ $? != 0 ]; then yes yes | ./terraform destroy; fi
-            echo "Cluster DESTROYED."
-          fi
 
 functions:
   "prepare environment":
@@ -79,57 +66,80 @@ functions:
       params:
         working_dir: work
         script: |
-           set -v
-           ./terraform get --update
-  "bring up cluster":
+          set -v
+          ./terraform get --update
     - command: shell.exec
-      # bring up the cluster
+      # set up $HOME/infrastructure_provisioning to keep track of resources,
+      # and allow Evergreen to release resources from there
       params:
-        working_dir: work
         script: |
-          # to create a mongod EC2 cluster
-          set -e
           set -o verbose
-          pwd
-          ls
-          cat dsienv.sh
-          source ./dsienv.sh
-          # create all resources and instances
-          $DSI_PATH/bin/setup-cluster.sh ${cluster} ../terraform
-    - command: shell.exec # End on setup-cluster.sh so it's error code is scripts error code
-      # After cluster up
-      params:
-        working_dir: work
-        script: |
-          echo "EC2 Cluster CREATED."
-          tar -czvf cluster_config.tgz infrastructure_provisioning.out.yml ips.sh ips.py terraform.tfstate cluster.tf terraform.tfvars variables.tf
-    - command: s3.put
-      params:
-        aws_key: ${aws_key}
-        aws_secret: ${aws_secret}
-        local_file: "work/cluster_config.tgz"
-        remote_file: dsi/${build_variant}/${revision}/cluster_configs/cluster_config-${build_id}.tgz
-        bucket: mciuploads
-        permissions: public-read
-        content_type: ${content_type|application/x-gzip}
-        display_name: ${cluster}-cluster-config
+          if [ ! -d "$HOME/infrastructure_provisioning" ]; then
+            echo "copying terraform to Evergreen host"
+            mkdir $HOME/infrastructure_provisioning
+            cp -r terraform $HOME/infrastructure_provisioning/.
+            cp -r modules $HOME/infrastructure_provisioning/.
+            echo "copying infrastructure_teardown.sh to Evergreen host"
+            cp src/dsi/dsi/bin/destroy_cluster.sh $HOME/infrastructure_provisioning/terraform/infrastructure_teardown.sh
+          fi
+          ls -l $HOME/infrastructure_provisioning
 
-  "restore cluster":
-    - command: s3.get
-      params:
-        aws_key: ${aws_key}
-        aws_secret: ${aws_secret}
-        remote_file: dsi/${build_variant}/${revision}/cluster_configs/cluster_config-${build_id}.tgz
-        bucket: mciuploads
-        local_file: "work/cluster_config.tgz"
+  "infrastructure provisioning":
     - command: shell.exec
+      # if $HOME/infrastructure_provisioning exists, get info about provisioned resources
+      # from there otherwise provision resources from the cloud
       params:
         working_dir: work
-        silent: true
         script: |
-          set -e
+          set -e 
           set -o verbose
-          tar -xf cluster_config.tgz
+          if [ -e "$HOME/infrastructure_provisioning/terraform/terraform.tfstate" ]; then
+            echo "Restrieving info for existing resources"
+            cp $HOME/infrastructure_provisioning/terraform/terraform.tfstate .
+          else
+            echo "No existing resources found"
+          fi
+    - command: shell.exec
+      # call setup-cluster.sh, in most cases this only updates expire-on tag
+      params:
+        working_dir: work
+        script: |
+          # don't run this with "set -e" so we can set up properly for the teardown.sh
+          set -o verbose
+          source ./dsienv.sh
+          if [ ! -e $HOME/infrastructure_provisioning/terraform/provisioned.${cluster} ]; then
+            echo "Provisinging new resources."
+            $DSI_PATH/bin/setup-cluster.sh ${cluster} ../terraform
+          else
+            # on host with pre-existing resources, call terraform directly to 
+            # avoid recreating instances due to terraform apply concurrency limitation
+            echo "Update expire-on tag for existing resources."
+            ./terraform apply -var-file=cluster.json
+            # call env.sh to generate ips.sh, etc. for downstream modules
+            $DSI_PATH/bin/env.sh
+          fi
+          # handle the case when setup-cluster.sh fail
+          if [ $? -eq 0 ]; then
+            echo "Resource provisioned/updated."
+            # copy terraform information needed for teardown
+            cp {terraform.tfstate,cluster.tf,terraform.tfvars,security.tf,variables.tf} $HOME/infrastructure_provisioning/terraform/.
+            rsync -vr ../modules $HOME/infrastructure_provisioning/modules
+            cd $HOME/infrastructure_provisioning/terraform
+            ./terraform get
+            # use provisioned.${shard} to indicate the type of clusters held by EVG host
+            # remove previous information and keep the latest cluster type
+            rm provisioned.*
+            touch provisioned.${cluster}
+            echo "Provisioning state updated on Evergreen host."            
+          else
+            echo "Failed to provision resources. Cleaning up partial state."
+            yes yes | ./terraform destroy
+            if [ $? != 0 ]; then yes yes | ./terraform destroy; fi
+            echo "Resource released."
+            rm -r $HOME/infrastructure_provisioning
+            echo "Cleaned up provisioning state on Evergreen host. Exiting test."
+            exit
+          fi
 
   "configure mongodb cluster":
     - command: shell.exec
@@ -165,28 +175,6 @@ functions:
       params:
          name: "perf"
          file: "work/perf.json"
-    - command: shell.exec
-      params:
-        working_dir: work
-        script: |
-          set -e
-          set -v
-          touch test.success
-
-  "destroy cluster":
-    - command: shell.exec
-      # destroy the cluster
-      params:
-        working_dir: work
-        script: |
-          set -e
-          set -o verbose
-          source ./dsienv.sh
-          # destroy the EC2 cluster
-          yes yes | ./terraform destroy; true
-          # make sure we destroy the cluster in case of AWS API timing issue
-          yes yes | ./terraform destroy; true
-          echo "Cluster DESTROYED."
 
   "make test log artifact":
     - command: shell.exec
@@ -350,21 +338,13 @@ tasks:
         content_type: ${content_type|application/x-gzip}
         display_name: mongodb.tar.gz
 
-
-# The industry_benchmarks_WT task runs the "bring up cluster" task and is
-# the only one to do so - all other tasks run "restore cluster".  As such,
-# all buildvariants must run industry_benchmarks_WT and run it first.
-
-# When adding or removing tasks, you also must ensure that the final task
-# and only the final task runs the "destroy cluster" function.
-
 - name: industry_benchmarks_WT
   depends_on:
     - name: compile
       variant: linux-standalone
   commands:
     - func: "prepare environment"
-    - func: "bring up cluster"
+    - func: "infrastructure provisioning"
     - func: "configure mongodb cluster"
       vars:
         storageEngine: "wiredTiger"
@@ -381,11 +361,11 @@ tasks:
 
 - name: industry_benchmarks_MMAPv1
   depends_on:
-    - name: core_workloads_WT
-      status : "*"
+    - name: compile
+      variant: linux-standalone
   commands:
     - func: "prepare environment"
-    - func: "restore cluster"
+    - func: "infrastructure provisioning"
     - func: "configure mongodb cluster"
       vars:
         storageEngine: "mmapv1"
@@ -402,11 +382,11 @@ tasks:
 
 - name: core_workloads_WT
   depends_on:
-    - name: industry_benchmarks_WT
-      status : "*"
+    - name: compile
+      variant: linux-standalone
   commands:
     - func: "prepare environment"
-    - func: "restore cluster"
+    - func: "infrastructure provisioning"
     - func: "configure mongodb cluster"
       vars:
         storageEngine: "wiredTiger"
@@ -423,11 +403,11 @@ tasks:
 
 - name: core_workloads_MMAPv1
   depends_on:
-    - name: industry_benchmarks_MMAPv1
-      status : "*"
+    - name: compile
+      variant: linux-standalone
   commands:
     - func: "prepare environment"
-    - func: "restore cluster"
+    - func: "infrastructure provisioning"
     - func: "configure mongodb cluster"
       vars:
         storageEngine: "mmapv1"
@@ -440,7 +420,6 @@ tasks:
     - func: "upload log file"
       vars:
         test: "core_workloads_MMAPv1"
-    - func: "destroy cluster"
     - func: "analyze"
 
 - name: industry_benchmarks_WT_oplog_comp
@@ -519,7 +498,7 @@ tasks:
       variant: linux-standalone
   commands:
     - func: "prepare environment"
-    - func: "bring up cluster"
+    - func: "infrastructure provisioning"
     - func: "configure mongodb cluster"
       vars:
         storageEngine: "wiredTiger"
@@ -536,11 +515,11 @@ tasks:
 
 - name: initialsync_MMAPv1
   depends_on:
-    - name: initialsync_WT
-      status : "*"
+    - name: compile
+      variant : linux-standalone
   commands:
     - func: "prepare environment"
-    - func: "restore cluster"
+    - func: "infrastructure provisioning"
     - func: "configure mongodb cluster"
       vars:
         storageEngine: "mmapv1"
@@ -557,11 +536,11 @@ tasks:
 
 - name: initialsync_WT_dr
   depends_on:
-    - name: initialsync_MMAPv1
-      status : "*"
+    - name: compile
+      variant: linux-standalone
   commands:
     - func: "prepare environment"
-    - func: "restore cluster"
+    - func: "infrastructure provisioning"
     - func: "configure mongodb cluster"
       vars:
         storageEngine: "wiredTiger"
@@ -575,7 +554,6 @@ tasks:
     - func: "upload log file"
       vars:
         test: "initialsync_WT"
-    - func: "destroy cluster"
     - func: "analyze"
 
 - name: initialsync_MMAPv1_dr
@@ -584,11 +562,10 @@ tasks:
       variant: linux-standalone
   commands:
     - func: "prepare environment"
-    - func: "restore cluster"
+    - func: "infrastructure provisioning"
     - func: "configure mongodb cluster"
       vars:
         storageEngine: "mmapv1"
-        setup: replica-2node.dr
     - func: "run test"
       vars:
         storageEngine: "mmapv1"
@@ -599,6 +576,7 @@ tasks:
       vars:
         test: "initialsync_MMAPv1"
     - func: "analyze"
+
 
 #######################################
 #               Modules               #
@@ -641,7 +619,7 @@ buildvariants:
     cluster: single
     platform: linux
   run_on:
-      - "rhel70-perf-standalone"
+      - "rhel70-perf-single"
   tasks:
     - name: industry_benchmarks_WT
     - name: core_workloads_WT
@@ -658,45 +636,11 @@ buildvariants:
     cluster: single
     platform: linux
   run_on:
-      - "rhel70-perf-standalone"
+      - "rhel70-perf-single"
   tasks:
     - name: compile
       distros:
       - rhel70
-    - name: industry_benchmarks_WT
-    - name: core_workloads_WT
-    - name: industry_benchmarks_MMAPv1
-    - name: core_workloads_MMAPv1
-
-- name: linux-standalone-c3-4xlarge
-  display_name: Linux Standalone (c3.4xlarge trial)
-  batchtime: 480 # 8 hours
-  disabled: true
-  modules: *modules
-  expansions:
-    setup: standalone
-    cluster: single-c3-4xlarge
-    platform: linux
-  run_on:
-      - "rhel70-perf-standalone"
-  tasks:
-    - name: industry_benchmarks_WT
-    - name: core_workloads_WT
-    - name: industry_benchmarks_MMAPv1
-    - name: core_workloads_MMAPv1
-
-- name: linux-standalone-c3-2xlarge
-  display_name: Linux Standalone (c3.2xlarge trial)
-  batchtime: 480 # 8 hours
-  modules: *modules
-  disabled: true
-  expansions:
-    setup: standalone
-    cluster: single-c3-2xlarge
-    platform: linux
-  run_on:
-      - "rhel70-perf-standalone"
-  tasks:
     - name: industry_benchmarks_WT
     - name: core_workloads_WT
     - name: industry_benchmarks_MMAPv1
@@ -712,7 +656,7 @@ buildvariants:
     cluster: shard
     platform: linux
   run_on:
-      - "rhel70-perf-standalone"
+      - "rhel70-perf-shard"
   tasks:
     - name: industry_benchmarks_WT
     - name: core_workloads_WT
@@ -729,7 +673,7 @@ buildvariants:
     cluster: replica
     platform: linux
   run_on:
-      - "rhel70-perf-standalone"
+      - "rhel70-perf-replset"
   tasks:
     - name: industry_benchmarks_WT
     - name: core_workloads_WT
@@ -742,75 +686,24 @@ buildvariants:
   modules: *modules
   expansions:
     compile_flags: -j$(grep -c ^processor /proc/cpuinfo) CC=/opt/mongodbtoolchain/v2/bin/gcc CXX=/opt/mongodbtoolchain/v2/bin/g++ OBJCOPY=/opt/mongodbtoolchain/v2/bin/objcopy --release
-    setup: replica-2node
+    setup: replica
     cluster: replica
     platform: linux
   run_on:
-      - "rhel70-perf-standalone"
+      - "rhel70-perf-replset"
   tasks:
     - name: initialsync_WT
     - name: initialsync_MMAPv1
-    - name: initialsync_WT_dr
 
 - name: linux-oplog-compare
   display_name: Linux Oplog Compare
   batchtime: 1440 # 24 hours
   modules: *modules
   run_on:
-      - "rhel70-perf-standalone"
+      - "rhel70-perf-single"
   tasks:
     - name: industry_benchmarks_WT_oplog_comp
     - name: core_workloads_WT_oplog_comp
     - name: industry_benchmarks_MMAPv1_oplog_comp
     - name: core_workloads_MMAPv1_oplog_comp
 
-
-#######################################
-#        Windows Buildvariants        #
-#######################################
-
-- name: windows-standalone
-  display_name: Windows Standalone (trial)
-  batchtime: 480 # 8 hours
-  modules: *modules
-  disabled: true
-  expansions:
-    setup: standalone-win
-    cluster: windows-single
-    extension: ".exe"
-    compile_flags: --release --win-version-min=ws08r2 -j$(grep -c ^processor /proc/cpuinfo) MONGO_DISTMOD=2008plus VARIANT_DIR=win32
-    platform: windows
-  run_on:
-      - "rhel70-perf-standalone"
-  tasks:
-    - name: compile
-      distros:
-      - windows-64-vs2015-compile
-    - name: industry_benchmarks_WT
-      depends_on:
-        - name: compile
-    - name: core_workloads_WT
-    - name: industry_benchmarks_MMAPv1
-    - name: core_workloads_MMAPv1
-
-- name: windows-1-node-replSet
-  display_name: Windows 1-node ReplSet (trial)
-  batchtime: 480 # 8 hours
-  modules: *modules
-  disabled: true
-  expansions:
-    setup: replica-win
-    cluster: windows-single
-    numShard: 0
-    extension: ".exe"
-    platform: windows
-  run_on:
-      - "rhel70-perf-standalone"
-  tasks:
-    - name: industry_benchmarks_WT
-      depends_on:
-        - name: compile
-          variant: windows-standalone
-    - name: core_workloads_WT
-    - name: industry_benchmarks_MMAPv1
-    - name: core_workloads_MMAPv1
