SERVER-84232 Make reuse_compile_from an alias of build_patch_id
GitOrigin-RevId: 5170ac808d7d3e204f6b84aea296a3b1403205d8

diff --git a/etc/system_perf.yml b/etc/system_perf.yml
--- a/etc/system_perf.yml
+++ b/etc/system_perf.yml
@@ -344,6 +344,74 @@ functions:
       params:
         working_dir: src
         script: |
+          set -o errexit
+          set -o verbose
+
+          source "${workdir}/compile_venv/bin/activate"
+
+          # We get the raw version string (r1.2.3-45-gabcdef) from git
+          # And append "-sys-perf" at the end
+          export MONGO_VERSION=$(git describe --abbrev=7)
+          MONGO_VERSION="$MONGO_VERSION-sys-perf"
+
+          # If this is a patch build, we add the patch version id to the version string so we know
+          # this build was a patch, and which evergreen task it came from
+          if [ "${is_patch|false}" = "true" ]; then
+            MONGO_VERSION="$MONGO_VERSION-patch-${version_id}"
+          fi
+
+          # This script handles sanitizing the version string for use during SCons build
+          # and when pushing artifacts up to S3.
+          IS_PATCH=${is_patch|false} IS_COMMIT_QUEUE=${is_commit_queue|false} \
+            buildscripts/generate_version_expansions.py --out version_expansions.yml
+    - command: expansions.update
+      params:
+        file: src/version_expansions.yml
+    - command: shell.exec
+      params:
+        working_dir: src
+        script: |
+          set -o errexit
+          set -o verbose
+
+          # This script handles whether the SCons cache should be used
+          source "${workdir}/compile_venv/bin/activate"
+          SCONS_CACHE_MODE=${scons_cache_mode|} USE_SCONS_CACHE=${use_scons_cache|false} \
+            IS_PATCH=${is_patch|false} IS_COMMIT_QUEUE=${is_commit_queue|false} \
+            python buildscripts/generate_compile_expansions.py --out compile_expansions.yml
+    - command: expansions.update
+      params:
+        file: src/compile_expansions.yml
+  compile prep old:
+    # We create a virtual environment with the Python dependencies for compiling the server
+    # installed.
+    - command: shell.exec
+      params:
+        working_dir: src
+        script: |
+          set -o errexit
+          set -o verbose
+
+          mkdir -p mongodb/bin
+
+          # This is copied from evergreen/functions/venv_setup.sh
+          # Consider consolidating this in the future
+          /opt/mongodbtoolchain/v4/bin/python3 -m venv "${workdir}/compile_venv"
+          source "${workdir}/compile_venv/bin/activate"
+
+          python -m pip install "poetry==1.5.1"
+          # See BF-29897 / https://github.com/python-poetry/poetry/issues/7584
+          poetry config installer.max-workers 10
+          # Trying poetry install due to https://github.com/python-poetry/poetry/issues/7611
+          python -m poetry install --no-root --sync || python -m poetry install --no-root --sync
+    - command: expansions.write
+      params:
+        file: expansions.yml
+        redacted: true
+    - command: shell.exec
+      params:
+        working_dir: src
+        script: |
           if [ -z "${reuse_compile_from}" ] || [ "${is_patch|false}" = "false" ]; then
             set -o errexit
             set -o verbose
@@ -399,6 +467,50 @@ functions:
       params:
         working_dir: src/mongo-tools/src/github.com/mongodb/mongo-tools
         script: |
+          set -o verbose
+          set -o errexit
+
+          # make sure newlines in the scripts are handled correctly by windows
+          if [ "Windows_NT" = "$OS" ]; then
+            set -o igncr
+          fi;
+
+          export cleanup=false
+
+          # install go for tools if required (al2023 for now).
+          if [ ! -d "/opt/golang/go1.19" ]; then
+            cleanup=true
+            echo -n "go-lang missing downloading ..."
+            go_file=./go1.19.8.tar.gz
+            wget --quiet https://go.dev/dl/go1.19.8.linux$(echo ${compile_variant} | sed 's/^-al202.//').tar.gz -O "$go_file"
+            echo -n " installing ..."
+            sudo mkdir -p /opt/golang/go1.19
+            sudo tar -C /opt/golang/go1.19 -xzf "$go_file" --strip-components=1
+            [ -e "$go_file" ] && rm -f "$go_file"
+            echo  "done"
+          fi
+
+          # set_goenv provides set_goenv()
+          . ./set_goenv.sh
+          GOROOT="" set_goenv || exit
+          go version
+
+          build_tools="bsondump mongostat mongofiles mongoexport mongoimport mongorestore mongodump mongotop"
+          if [ "${build_mongoreplay}" = "true" ]; then
+              build_tools="$build_tools mongoreplay"
+          fi
+          for i in $build_tools; do
+              go build -o "../../../../../mongodb/bin/$i${exe|}" $i/main/$i.go
+              "../../../../../mongodb/bin/$i${exe|}" --version
+          done
+          if "$cleanup"; then
+            sudo rm -rf "/opt/golang/go1.19"
+          fi
+  compile mongo tools old:
+    - command: shell.exec
+      params:
+        working_dir: src/mongo-tools/src/github.com/mongodb/mongo-tools
+        script: |
           if [ -z "${reuse_compile_from}" ] || [ "${is_patch|false}" = "false" ]; then
             set -o verbose
             set -o errexit
@@ -445,6 +557,17 @@ functions:
       params:
         working_dir: src
         script: |
+          set -o errexit
+          set -o verbose
+          source "${workdir}/compile_venv/bin/activate"
+          python ./buildscripts/idl/gen_all_feature_flag_list.py
+          mkdir -p mongodb/feature_flags
+          cp ./all_feature_flags.txt mongodb/feature_flags
+  generate feature flag list old:
+    - command: shell.exec
+      params:
+        working_dir: src
+        script: |
           if [ -z "${reuse_compile_from}" ] || [ "${is_patch|false}" = "false" ]; then
             set -o errexit
             set -o verbose
@@ -454,6 +577,17 @@ functions:
             cp ./all_feature_flags.txt mongodb/feature_flags
           fi
   generate server params list:
+    - command: shell.exec
+      params:
+        working_dir: src
+        script: |
+          set -o errexit
+          set -o verbose
+          source "${workdir}/compile_venv/bin/activate"
+          python ./buildscripts/idl/gen_all_server_params_list.py
+          mkdir -p mongodb/server_params
+          cp ./all_server_params.txt mongodb/server_params
+  generate server params list old:
     - command: shell.exec
       params:
         working_dir: src
@@ -482,6 +616,19 @@ functions:
       params:
         working_dir: src
         script: |
+            set -o errexit
+            set -o verbose
+            wget --quiet https://s3.amazonaws.com/mciuploads/${project}/${compile_variant}/${version_id}/binaries/mongo-${revision_order_id}.${ext|tgz}
+            tar -xvf mongo-${revision_order_id}.${ext|tgz}
+            mv ./dist-test/bin/mongo mongodb/bin
+            mv ./dist-test/bin/mongos mongodb/bin
+            mv ./dist-test/bin/mongod mongodb/bin
+            mv ./dist-test/bin/mongocryptd mongodb/bin
+  download mongodb old:
+    - command: shell.exec
+      params:
+        working_dir: src
+        script: |
           if [ -z "${reuse_compile_from}" ] || [ "${is_patch|false}" = "false" ]; then
             set -o errexit
             set -o verbose
@@ -493,6 +640,28 @@ functions:
             mv ./dist-test/bin/mongocryptd mongodb/bin
           fi
   download jstests:
+    - command: shell.exec
+      params:
+        working_dir: src
+        script: |
+          set -o errexit
+          set -o verbose
+          mkdir -p mongodb/jstests/hooks
+          if [ -d jstests/hooks ]
+          then
+            echo "Fetching JS test DB correctness checks from directory jstests"
+            cp -a jstests/* mongodb/jstests
+
+            echo "Now adding our own special run_validate_collections.js wrapper"
+            mv mongodb/jstests/hooks/run_validate_collections.js mongodb/jstests/hooks/run_validate_collections.actual.js
+
+            cat << EOF > mongodb/jstests/hooks/run_validate_collections.js
+            print("NOTE: run_validate_collections.js will skip the oplog!");
+            TestData = { skipValidationNamespaces: ['local.oplog.rs'] };
+            await import("jstests/hooks/run_validate_collections.actual.js");
+          EOF
+          fi
+  download jstests old:
     - command: shell.exec
       params:
         working_dir: src
@@ -517,6 +686,12 @@ functions:
             fi
           fi
   package binary:
+    - command: shell.exec
+      params:
+        working_dir: src
+        script: |
+          tar czf mongodb${compile_variant|}.tar.gz mongodb
+  package binary old:
     - command: shell.exec
       params:
         working_dir: src
@@ -625,13 +800,13 @@ tasks:
           revisions:
             enterprise: ${enterprise_rev}
             mongo-tools: ${mongo-tools_rev}
-      - func: "compile prep"
-      - func: "compile mongo tools"
-      - func: "generate feature flag list"
-      - func: "generate server params list"
+      - func: "compile prep old"
+      - func: "compile mongo tools old"
+      - func: "generate feature flag list old"
+      - func: "generate server params list old"
       - func: "compile mongodb"
-      - func: "download jstests"
-      - func: "package binary"
+      - func: "download jstests old"
+      - func: "package binary old"
       - func: "upload binary"
       - func: "package old debugsymbols"
       - func: "upload old debugsymbols"
