SERVER-88676: Backport build_patch_id/reuse_compile_from to 7.0. (#20542)
GitOrigin-RevId: 5627c3e8dbad4588800d27ee79bbc8335de66b06

diff --git a/etc/system_perf.yml b/etc/system_perf.yml
--- a/etc/system_perf.yml
+++ b/etc/system_perf.yml
@@ -353,30 +353,26 @@ functions:
       params:
         working_dir: src
         script: |
-          if [ -z "${reuse_compile_from}" ] || [ "${is_patch|false}" = "false" ]; then
-            set -o errexit
-            set -o verbose
+          set -o errexit
+          set -o verbose
 
-            source "${workdir}/compile_venv/bin/activate"
+          source "${workdir}/compile_venv/bin/activate"
 
-            # We get the raw version string (r1.2.3-45-gabcdef) from git
-            # And append "-sys-perf" at the end
-            export MONGO_VERSION=$(git describe --abbrev=7)
-            MONGO_VERSION="$MONGO_VERSION-sys-perf"
+          # We get the raw version string (r1.2.3-45-gabcdef) from git
+          # And append "-sys-perf" at the end
+          export MONGO_VERSION=$(git describe --abbrev=7)
+          MONGO_VERSION="$MONGO_VERSION-sys-perf"
 
-            # If this is a patch build, we add the patch version id to the version string so we know
-            # this build was a patch, and which evergreen task it came from
-            if [ "${is_patch|false}" = "true" ]; then
-              MONGO_VERSION="$MONGO_VERSION-patch-${version_id}"
-            fi
-
-            # This script handles sanitizing the version string for use during SCons build
-            # and when pushing artifacts up to S3.
-            IS_PATCH=${is_patch|false} IS_COMMIT_QUEUE=${is_commit_queue|false} \
-              buildscripts/generate_version_expansions.py --out version_expansions.yml
-          else
-            touch version_expansions.yml
+          # If this is a patch build, we add the patch version id to the version string so we know
+          # this build was a patch, and which evergreen task it came from
+          if [ "${is_patch|false}" = "true" ]; then
+            MONGO_VERSION="$MONGO_VERSION-patch-${version_id}"
           fi
+
+          # This script handles sanitizing the version string for use during SCons build
+          # and when pushing artifacts up to S3.
+          IS_PATCH=${is_patch|false} IS_COMMIT_QUEUE=${is_commit_queue|false} \
+            buildscripts/generate_version_expansions.py --out version_expansions.yml
     - command: expansions.update
       params:
         file: src/version_expansions.yml
@@ -408,59 +404,67 @@ functions:
       params:
         working_dir: src/mongo-tools/src/github.com/mongodb/mongo-tools
         script: |
-          if [ -z "${reuse_compile_from}" ] || [ "${is_patch|false}" = "false" ]; then
-            set -o verbose
-            set -o errexit
+          set -o verbose
+          set -o errexit
 
-            # make sure newlines in the scripts are handled correctly by windows
-            if [ "Windows_NT" = "$OS" ]; then
-              set -o igncr
-            fi;
+          # make sure newlines in the scripts are handled correctly by windows
+          if [ "Windows_NT" = "$OS" ]; then
+            set -o igncr
+          fi;
 
-            # set_goenv provides set_goenv()
-            . ./set_goenv.sh
-            GOROOT="" set_goenv || exit
-            go version
+          export cleanup=false
 
-            build_tools="bsondump mongostat mongofiles mongoexport mongoimport mongorestore mongodump mongotop"
-            if [ "${build_mongoreplay}" = "true" ]; then
-                build_tools="$build_tools mongoreplay"
-            fi
-            for i in $build_tools; do
-                go build -o "../../../../../mongodb/bin/$i${exe|}" $i/main/$i.go
-                "../../../../../mongodb/bin/$i${exe|}" --version
-            done
+          # install go for tools if required (al2023 for now).
+          if [ ! -d "/opt/golang/go1.19" ]; then
+            cleanup=true
+            echo -n "go-lang missing downloading ..."
+            go_file=./go1.19.8.tar.gz
+            wget --quiet https://go.dev/dl/go1.19.8.linux$(echo ${compile_variant} | sed 's/^-al202.//').tar.gz -O "$go_file"
+            echo -n " installing ..."
+            sudo mkdir -p /opt/golang/go1.19
+            sudo tar -C /opt/golang/go1.19 -xzf "$go_file" --strip-components=1
+            [ -e "$go_file" ] && rm -f "$go_file"
+            echo  "done"
+          fi
+
+          # set_goenv provides set_goenv()
+          . ./set_goenv.sh
+          GOROOT="" set_goenv || exit
+          go version
+
+          build_tools="bsondump mongostat mongofiles mongoexport mongoimport mongorestore mongodump mongotop"
+          if [ "${build_mongoreplay}" = "true" ]; then
+              build_tools="$build_tools mongoreplay"
           fi
           for i in $build_tools; do
-              go build -ldflags "$(print_ldflags)" ${args} -tags "$(print_tags ${tooltags})" -o "../../../../../mongodb/bin/$i${exe|}" $i/main/$i.go
+              go build -o "../../../../../mongodb/bin/$i${exe|}" $i/main/$i.go
               "../../../../../mongodb/bin/$i${exe|}" --version
           done
+          if "$cleanup"; then
+            sudo rm -rf "/opt/golang/go1.19"
+          fi
   generate feature flag list:
     - command: shell.exec
       params:
         working_dir: src
         script: |
-          if [ -z "${reuse_compile_from}" ] || [ "${is_patch|false}" = "false" ]; then
-            set -o errexit
-            set -o verbose
-            source "${workdir}/compile_venv/bin/activate"
-            python ./buildscripts/idl/gen_all_feature_flag_list.py
-            mkdir -p mongodb/feature_flags
-            cp ./all_feature_flags.txt mongodb/feature_flags
-          fi
+          set -o errexit
+          set -o verbose
+          source "${workdir}/compile_venv/bin/activate"
+          python ./buildscripts/idl/gen_all_feature_flag_list.py
+          mkdir -p mongodb/feature_flags
+          cp ./all_feature_flags.txt mongodb/feature_flags
   generate server params list:
     - command: shell.exec
       params:
         working_dir: src
         script: |
-          if [ -z "${reuse_compile_from}" ] || [ "${is_patch|false}" = "false" ]; then
-            set -o errexit
-            set -o verbose
-            source "${workdir}/compile_venv/bin/activate"
-            python ./buildscripts/idl/gen_all_server_params_list.py
-            mkdir -p mongodb/server_params
-            cp ./all_server_params.txt mongodb/server_params
-          fi
+          set -o errexit
+          set -o verbose
+          source "${workdir}/compile_venv/bin/activate"
+          python ./buildscripts/idl/gen_all_server_params_list.py
+          mkdir -p mongodb/server_params
+          cp ./all_server_params.txt mongodb/server_params
   compile mongodb:
     - command: shell.exec
       params:
@@ -477,7 +481,6 @@ functions:
       params:
         working_dir: src
         script: |
-          if [ -z "${reuse_compile_from}" ] || [ "${is_patch|false}" = "false" ]; then
             set -o errexit
             set -o verbose
             wget --quiet https://s3.amazonaws.com/mciuploads/${project}/${compile_variant}/${version_id}/binaries/mongo-${revision_order_id}.${ext|tgz}
@@ -486,63 +489,36 @@ functions:
             mv ./dist-test/bin/mongos mongodb/bin
             mv ./dist-test/bin/mongod mongodb/bin
             mv ./dist-test/bin/mongocryptd mongodb/bin
-          fi
+            # Copy libs folder if it exists
+            [ ! -d ./dist-test/lib ] || mv ./dist-test/lib mongodb
   download jstests:
     - command: shell.exec
       params:
         working_dir: src
         script: |
-          if [ -z "${reuse_compile_from}" ] || [ "${is_patch|false}" = "false" ]; then
-            set -o errexit
-            set -o verbose
-            mkdir -p mongodb/jstests/hooks
-            if [ -d jstests/hooks ]
-            then
-              echo "Fetching JS test DB correctness checks from directory jstests"
-              cp -a jstests/* mongodb/jstests
+          set -o errexit
+          set -o verbose
+          mkdir -p mongodb/jstests/hooks
+          if [ -d jstests/hooks ]
+          then
+            echo "Fetching JS test DB correctness checks from directory jstests"
+            cp -a jstests/* mongodb/jstests
 
-              echo "Now adding our own special run_validate_collections.js wrapper"
-              mv mongodb/jstests/hooks/run_validate_collections.js mongodb/jstests/hooks/run_validate_collections.actual.js
+            echo "Now adding our own special run_validate_collections.js wrapper"
+            mv mongodb/jstests/hooks/run_validate_collections.js mongodb/jstests/hooks/run_validate_collections.actual.js
 
-              cat << EOF > mongodb/jstests/hooks/run_validate_collections.js
-              print("NOTE: run_validate_collections.js will skip the oplog!");
-              TestData = { skipValidationNamespaces: ['local.oplog.rs'] };
-              await import("jstests/hooks/run_validate_collections.actual.js");
+            cat << EOF > mongodb/jstests/hooks/run_validate_collections.js
+            print("NOTE: run_validate_collections.js will skip the oplog!");
+            TestData = { skipValidationNamespaces: ['local.oplog.rs'] };
+            await import("jstests/hooks/run_validate_collections.actual.js");
           EOF
-            fi
           fi
   package binary:
     - command: shell.exec
       params:
         working_dir: src
         script: |
-          if [ -z "${reuse_compile_from}" ] || [ "${is_patch|false}" = "false" ]; then
-            tar czf mongodb${compile_variant|}.tar.gz mongodb
-          fi
-    - command: shell.exec
-      params:
-        working_dir: src
-        script: |
-          if [ -n "${reuse_compile_from}" ] && [ "${is_patch|false}" = "true" ]; then
-            set -o errexit
-            set -o verbose
-
-            source "${workdir}/compile_venv/bin/activate"
-            python buildscripts/download_sys_perf_binaries.py -v ${reuse_compile_from} -b ${build_variant} -u ${evergreen_api_user} -k ${evergreen_api_key}
-            mv binary.tar.gz mongodb${compile_variant|}.tar.gz
-          fi
-  package old debugsymbols:
-    - command: shell.exec
-      params:
-        working_dir: src
-        script: |
-          if [ -z "${reuse_compile_from}" ] || [ "${is_patch|false}" = "false" ]; then
-            set -o errexit
-            set -o verbose
-            # Put all matching mongo debug from the build directory in an archive in the same location
-            # as the library archive (i.e. mongodb/bin).
-            tar czvf mongodb${compile_variant|}-debugsymbols.tar.gz $(find ./build/cached -name mongo\*.debug -type f) --xform 's:^.*/:mongodb/bin/:'
-          fi
+          tar czf mongodb${compile_variant|}.tar.gz mongodb
   upload binary:
     - command: s3.put
       params:
@@ -554,18 +530,6 @@ functions:
         permissions: public-read
         content_type: ${content_type|application/x-gzip}
         display_name: mongodb${compile_variant|}.tar.gz
-  upload old debugsymbols:
-    - command: s3.put
-      params:
-        aws_key: ${aws_key}
-        aws_secret: ${aws_secret}
-        local_file: src/mongodb${compile_variant|}-debugsymbols.tar.gz
-        remote_file: ${project_dir}/${version_id}/${revision}/${platform}/mongodb${compile_variant|}-${version_id}-debugsymbols.tar.gz
-        bucket: mciuploads
-        permissions: public-read
-        optional: true
-        content_type: ${content_type|application/x-gzip}
-        display_name: mongo-debugsymbols.tgz
   ###
 
   ###
@@ -710,25 +674,6 @@ tasks:
           infrastructure_provisioning: shard-lite
 
   ###
-
-  - name: compile
-    commands:
-      - command: manifest.load
-      - command: git.get_project
-        params:
-          directory: src
-          revisions:
-            mongo-tools: ${mongo-tools_rev}
-      - func: "compile prep"
-      - func: "compile mongo tools"
-      - func: "generate feature flag list"
-      - func: "generate server params list"
-      - func: "compile mongodb"
-      - func: "download jstests"
-      - func: "package binary"
-      - func: "upload binary"
-      - func: "package old debugsymbols"
-      - func: "upload old debugsymbols"
 
   - name: package_new_compile
     commands:
