WT-2380 Add option to s_all to return an error code when tests fail (#2839)

diff --git a/dist/s_all b/dist/s_all
--- a/dist/s_all
+++ b/dist/s_all
@@ -15,6 +15,10 @@ echo 'dist/s_all run started...'
 
 force=
 reconf=0
+errmode=0
+errfound=0
+# Some tests just shouldn't return an error. We exclude them here
+err_exclusions=('\./s_export')
 while :
 	do case "$1" in
 	-A)	# Reconfigure the library build.
@@ -22,6 +26,9 @@ while :
 		shift;;
 	-f)	# Force versions to be updated
 		force="-f"
+		shift;;
+	-E)	# Return an error code on failure
+		errmode=1
 		shift;;
 	*)
 		break;;
@@ -48,6 +55,9 @@ errchk()
 	echo "#######################"
 
 	rm -f $2
+	if ! [[ "${err_exclusions[@]}" =~ "$1" ]]; then
+		errfound=1
+	fi
 }
 
 run()
@@ -108,3 +118,6 @@ for f in `find . -name ${t_pfx}\*`; do
 done
 
 echo 'dist/s_all run finished'
+if test $errmode -ne 0; then
+	exit $errfound;
+fi
