Complain if we can't find python. Exit with an appropriate error, don't always exit with 0
--HG--
extra : rebase_source : 8c11cd081192059abdaab6d765c88fde7ee5577b

diff --git a/dist/s_all b/dist/s_all
--- a/dist/s_all
+++ b/dist/s_all
@@ -2,7 +2,13 @@
 
 # Run standard scripts.
 t=__wt.$$
-trap 'rm -f $t *.pyc __tmp __wt.*; exit 0' 0 1 2 3 13 15
+trap 'rm -f $t *.pyc __tmp __wt.*' 0 1 2 3 13 15
+
+# We require python which may not be installed.
+type xpython > /dev/null 2>&1 || {
+	echo 's_all: python not found'
+	return 1
+}
 
 run()
 {
@@ -66,3 +72,5 @@ run "sh ./s_whitespace" "Checking whitespace"
 run "sh ./s_docs" "Generating documentation"
 
 echo 'dist/s_all run finished'
+
+return 0
