We're not checking parallized commands for "skipped" errors, remove run() function's handling of "skipped" errors, then create an errchk() function that is called both for single-threaded and parallel commands, so we get consistent error messages no matter how the script was run.
The s_version script doesn't produce output to the temporary file,
exempt it from normal error processing.

diff --git a/dist/s_all b/dist/s_all
--- a/dist/s_all
+++ b/dist/s_all
@@ -4,34 +4,11 @@
 t=__wt.$$
 t_pfx=__s_all_tmp
 trap 'rm -f $t *.pyc __tmp __wt.* __s_all_tmp*' 0 1 2 3 13 15
-FAIL_HEADER="####################### ERROR ############################"
-FAIL_FOOTER="#######################"
 
 # We require python which may not be installed.
 type python > /dev/null 2>&1 || {
 	echo 's_all: python not found'
 	exit 1
-}
-
-run()
-{
-	error_prefix="s_all run of: $1 resulted in:"
-	$1 > $t
-
-	if `grep 'skipped' $t > /dev/null 2>&1`; then
-		echo "$FAIL_HEADER"
-		printf "$error_prefix"
-	        printf "	" && cat $t
-		echo "$FAIL_FOOTER"
-	elif `test -s $t`; then
-		echo "$FAIL_HEADER"
-		printf "$error_prefix"
-		echo
-		sed -e 's/^/	/' $t
-		echo "$FAIL_FOOTER"
-	fi
-	rm -f $t
-	return 0
 }
 
 echo 'dist/s_all run started...'
@@ -51,11 +28,32 @@ while :
 	esac
 done
 
-run "sh ./s_version $force" "Updating files that include the package version"
+echo "Updating files that include the package version" &&
+    sh ./s_version $force
 
 test "$reconf" -eq 0 || {
 	(echo "Rebuilding GNU tools library support" &&
-	    cd ../build_posix && sh ./reconf)
+	    cd ../build_posix && 2>&1 sh ./reconf | sed -e 's/^/    /')
+}
+
+errchk()
+{
+	if ! `test -s $2`; then
+		return
+	fi
+
+	echo "####################### ERROR ############################"
+	echo "s_all run of: \"$1\" resulted in:"
+	sed -e 's/^/    /' $2
+	echo "#######################"
+
+	rm -f $2
+}
+
+run()
+{
+	2>&1 $1 > $t
+	errchk "$1" $t
 }
 
 # Non parallelizable scripts The following scripts either modify files or
@@ -100,10 +98,7 @@ for f in `find . -name ${t_pfx}\*`; do
 	# Find original command and trim redirect garbage
 	FAILED_CMD=`echo "$COMMANDS" | grep $LOCAL_NAME | \
 	    sed -e 's/ >.*//' -e 's/.* //'`
-	echo "$FAIL_HEADER"
-	echo "s_all run failed: $FAILED_CMD produced"
-	cat $f
-	echo "$FAIL_FOOTER"
+	errchk "$FAILED_CMD" $f
 done
 
 echo 'dist/s_all run finished'
