Make s_symbols portable to at least OS X.

diff --git a/dist/s_symbols b/dist/s_symbols
--- a/dist/s_symbols
+++ b/dist/s_symbols
@@ -5,13 +5,21 @@
 t=__a.c
 trap 'rm -f $t; exit 0' 0 1 2 3 13 15
 
-# We require GNU nm which may not be installed.  Be silent on this error
-# there's no need to annoy people.
-type nm > /dev/null 2>&1 &&
-    nm --version | grep 'GNU nm' > /dev/null 2>&1 || {
-	echo 'skipped: GNU nm not found'
-	return 0
-}
+case `uname` in
+Darwin)
+	NM='nm -gUo $f | egrep " T | D " | sed "s/ _/ /"'
+	;;
+*)
+	# We require GNU nm which may not be installed.  Be silent on this error
+	# there's no need to annoy people.
+	type nm > /dev/null 2>&1 &&
+	    (nm --version | grep 'GNU nm') > /dev/null 2>&1 || {
+		echo 'skipped: GNU nm not found'
+		exit 0
+	}
+	NM='nm --extern-only --defined-only --print-file-name $f'
+	;;
+esac
 
 # This check would normally be done after the library is built, but this way
 # we don't forget about a symbol during development.   Check the previously
@@ -19,11 +27,11 @@ type nm > /dev/null 2>&1 &&
 f=../build_posix/libwiredtiger.a
 test -f $f || {
 	echo "skipped: libwiredtiger.a not found"
-	return 0
+	exit 0
 }
 
 (cat s_symbols.list &&
-nm --extern-only --defined-only --print-file-name $f |
+eval $NM |
 sed 's/.* //' |
 egrep -v '^__wt') |
 sort |
