Import wiredtiger: 41818169e75bc7c3b00abea82d5aff9fbcb242ce from branch mongodb-master
ref: 57c7711623..41818169e7
for: 6.3.0-rc0

WT-10302 Convert tabs to spaces in dist/ files

diff --git a/src/third_party/wiredtiger/dist/s_all b/src/third_party/wiredtiger/dist/s_all
--- a/src/third_party/wiredtiger/dist/s_all
+++ b/src/third_party/wiredtiger/dist/s_all
@@ -7,8 +7,8 @@ trap 'rm -f $t *.pyc __tmp __wt.* __s_all_tmp*' 0 1 2 3 13 15
 
 # We require python which may not be installed.
 type python > /dev/null 2>&1 || {
-	echo 's_all: python not found'
-	exit 1
+    echo 's_all: python not found'
+    exit 1
 }
 
 echo 'dist/s_all run started...'
@@ -18,24 +18,25 @@ force=
 reconf=0
 errmode=0
 errfound=0
+
 while :
-	do case "$1" in
-	-A)	# Reconfigure the library build.
-		reconf=1
-		shift;;
-	-E)	# Return an error code on failure
-		errmode=1
-		shift;;
-	-f)	# Force versions to be updated
-		force="-f"
-		shift;;
-	-F) # Run fast.
+    do case "$1" in
+    -A)    # Reconfigure the library build.
+        reconf=1
+        shift;;
+    -E)    # Return an error code on failure
+        errmode=1
+        shift;;
+    -f)    # Force versions to be updated
+        force="-f"
+        shift;;
+    -F) # Run fast.
         echo "dist/s_all running in fast mode..."
-		fast=0
-		shift;;
-	*)
-		break;;
-	esac
+        fast=0
+        shift;;
+    *)
+        break;;
+    esac
 done
 
 echo "Updating files that include the package version" &&
@@ -43,38 +44,38 @@ echo "Updating files that include the package version" &&
 
 errchk()
 {
-	if ! `test -s $2`; then
-		return
-	fi
+    if ! `test -s $2`; then
+        return
+    fi
 
-	# Return if evergreen validate runs sucessfully.
-	if echo "$1" | grep -q evergreen && [ "$(cat "$2")" = "../test/evergreen.yml is valid" ] ; then
-		rm -f "$2"
-		return
-	fi
+    # Return if evergreen validate runs sucessfully.
+    if echo "$1" | grep -q evergreen && [ "$(cat "$2")" = "../test/evergreen.yml is valid" ] ; then
+        rm -f "$2"
+        return
+    fi
 
-	echo "####################### MESSAGE ############################"
-	echo "s_all run of: \"$1\" resulted in:"
-	sed -e 's/^/    /' $2
-	echo "#######################"
+    echo "####################### MESSAGE ############################"
+    echo "s_all run of: \"$1\" resulted in:"
+    sed -e 's/^/    /' $2
+    echo "#######################"
 
-	# If the test was skipped, ignore the failure.
-	if ! `grep "$1.*skipped" $2 > /dev/null`; then
-	    errfound=1;
-	fi
+    # If the test was skipped, ignore the failure.
+    if ! `grep "$1.*skipped" $2 > /dev/null`; then
+        errfound=1;
+    fi
 
-	# Ignore errors if the script is marked warning-only
-	if [ "$3" = "--warning-only" ]; then
-		errfound=0;
-	fi
+    # Ignore errors if the script is marked warning-only
+    if [ "$3" = "--warning-only" ]; then
+        errfound=0;
+    fi
 
-	rm -f $2
+    rm -f $2
 }
 
 run()
 {
-	2>&1 $1 > $t
-	errchk "$1" $t "$2"
+    2>&1 $1 > $t
+    errchk "$1" $t "$2"
 }
 
 # Non parallelizable scripts. The following scripts either modify files or
@@ -101,7 +102,7 @@ run "python test_tag.py"
 # The s_mentions script requires bash.
 run "./s_mentions" "--warning-only"
 if [ $(command -v evergreen) ] && [ -f ~/.evergreen.yml ]; then
-	run "evergreen validate -p wiredtiger ../test/evergreen.yml"
+    run "evergreen validate -p wiredtiger ../test/evergreen.yml"
 fi
 
 COMMANDS="
@@ -129,22 +130,22 @@ COMMANDS="
 xp=""
 echo date | xargs -P 20 >/dev/null 2>&1
 if test $? -eq 0; then
-	xp="-P 20"
+    xp="-P 20"
 fi
 echo "$COMMANDS" | xargs $xp -I{} /bin/sh -c {}
 
 for f in `find . -name ${t_pfx}\*`; do
-	if `test -s $f`; then
-		LOCAL_NAME=`basename $f`
-		# Find original command and trim redirect garbage
-		FAILED_CMD=`echo "$COMMANDS" | grep $LOCAL_NAME | \
-		    sed -e 's/ >.*//' -e 's/.* //'`
-		errchk "$FAILED_CMD" $f
-	fi
+    if `test -s $f`; then
+        LOCAL_NAME=`basename $f`
+        # Find original command and trim redirect garbage
+        FAILED_CMD=`echo "$COMMANDS" | grep $LOCAL_NAME | \
+            sed -e 's/ >.*//' -e 's/.* //'`
+        errchk "$FAILED_CMD" $f
+    fi
 done
 
 echo 'dist/s_all run finished'
 if test $errmode -ne 0; then
-	exit $errfound;
+    exit $errfound;
 fi
 exit 0
diff --git a/src/third_party/wiredtiger/dist/s_docs b/src/third_party/wiredtiger/dist/s_docs
--- a/src/third_party/wiredtiger/dist/s_docs
+++ b/src/third_party/wiredtiger/dist/s_docs
@@ -9,8 +9,8 @@ test -n "$WT_RELEASE_BUILD" && exit 0
 
 # We require doxygen which may not be installed.
 type doxygen > /dev/null 2>&1 || {
-	echo "$0 skipped: doxygen not found"
-	exit 0
+    echo "$0 skipped: doxygen not found"
+    exit 0
 }
 
 # Don't create Python bytecode files, we don't run this regularly and it gets flagged by git as an
@@ -23,188 +23,188 @@ e=0
 
 wtperf_config()
 {
-	# The Linux ed command writes line numbers to stderr, redirect both
-	# stdout and stderr to keep things quiet.
-	#
-	# The OS X cpp program injects line number output in the middle of lines
-	# and doesn't stringify #XXX entries; use the -E option to the compiler
-	# instead.
-	cat ../bench/wtperf/wtperf_opt.i |
-	${CC:-cc} -E -DOPT_DEFINE_DOXYGEN - | python wtperf_config.py > $t
-	(echo '/START_AUTO_GENERATED_WTPERF_CONFIGURATION/+3,/STOP_AUTO_GENERATED_WTPERF_CONFIGURATION/-1d'
-	 echo 'i'
-	 echo ''
-	 echo '.'
-	 echo ".r $t"
-	 echo 'a'
-	 echo ''
-	 echo '.'
-	 echo 'w'
-	 echo 'q') | ed ../src/docs/wtperf.dox 1>/dev/null 2>/dev/null
+    # The Linux ed command writes line numbers to stderr, redirect both
+    # stdout and stderr to keep things quiet.
+    #
+    # The OS X cpp program injects line number output in the middle of lines
+    # and doesn't stringify #XXX entries; use the -E option to the compiler
+    # instead.
+    cat ../bench/wtperf/wtperf_opt.i |
+    ${CC:-cc} -E -DOPT_DEFINE_DOXYGEN - | python wtperf_config.py > $t
+    (echo '/START_AUTO_GENERATED_WTPERF_CONFIGURATION/+3,/STOP_AUTO_GENERATED_WTPERF_CONFIGURATION/-1d'
+     echo 'i'
+     echo ''
+     echo '.'
+     echo ".r $t"
+     echo 'a'
+     echo ''
+     echo '.'
+     echo 'w'
+     echo 'q') | ed ../src/docs/wtperf.dox 1>/dev/null 2>/dev/null
 }
 
 glossarychk()
 {
-	(cd ../src/docs && grep '^<tr><td>' arch-glossary.dox | cut -d'>' -f3 | sed -e 's/<.*//') > $t
-	sort -f $t > $t2
-	if ! diff $t $t2; then
-		echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
-		echo "arch-glossary.dox entries out of order"
-		echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
-		e=1
-	fi
+    (cd ../src/docs && grep '^<tr><td>' arch-glossary.dox | cut -d'>' -f3 | sed -e 's/<.*//') > $t
+    sort -f $t > $t2
+    if ! diff $t $t2; then
+        echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
+        echo "arch-glossary.dox entries out of order"
+        echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
+        e=1
+    fi
 }
 
 structurechk()
 {
-	# sections are a global name space for doxygen, and must be uniquely
-	# named or you can get the wrong results.  For example, if you have
-	# "@section foo ABC" and "@section foo DEF", they will both appear as
-	# "ABC" or "DEF".
-	(cd ../src/docs &&
-	sed -n 's/@section \([^ ]*\)/\1/p' *.dox | sort | uniq -d) > $t
-	test -s $t && {
-		echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
-		echo '@section references that are not uniquely named'
-		sed -e 's/^/	/' < $t
-		echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
-		e=1
-	}
-	# we want a simple tree structure for navigation, otherwise
-	# clicking in the navigation tree can jump to a different point in
-	# the tree
-	(cd ../src/docs &&
-	sed -n 's/@subpage \([^ ]*\)/\1/p' *.dox | sort | uniq -d) > $t
-	test -s $t && {
-		echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
-		echo 'multiple @subpage references for the same page'
-		sed -e 's/^/	/' < $t
-		echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
-		e=1
-	}
+    # sections are a global name space for doxygen, and must be uniquely
+    # named or you can get the wrong results.  For example, if you have
+    # "@section foo ABC" and "@section foo DEF", they will both appear as
+    # "ABC" or "DEF".
+    (cd ../src/docs &&
+    sed -n 's/@section \([^ ]*\)/\1/p' *.dox | sort | uniq -d) > $t
+    test -s $t && {
+        echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
+        echo '@section references that are not uniquely named'
+        sed -e 's/^/	/' < $t
+        echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
+        e=1
+    }
+    # we want a simple tree structure for navigation, otherwise
+    # clicking in the navigation tree can jump to a different point in
+    # the tree
+    (cd ../src/docs &&
+    sed -n 's/@subpage \([^ ]*\)/\1/p' *.dox | sort | uniq -d) > $t
+    test -s $t && {
+        echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
+        echo 'multiple @subpage references for the same page'
+        sed -e 's/^/	/' < $t
+        echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
+        e=1
+    }
 }
 
 spellchk()
 {
-	# If aspell has been installed, run a spell check.
-	type aspell > /dev/null 2>&1 || return
+    # If aspell has been installed, run a spell check.
+    type aspell > /dev/null 2>&1 || return
 
-	(cd ../src/docs &&
-	# - Separate quoted newlines "line\nline" so "nline" is not reported.
-	# - Specifically ignore anything tagged @sic.
-	# - Specifically hide certain valid uses of the strings "curprev",
-	#   "curnext", "dsk", and "vrfy" so we can refer to the source files
-	#   and their function names in the architecture docs without making
-	#   "vrfy" and "dsk" legal spelling words.
-	sed \
-		-e 's/\("[^"]*\)\\n\([^"]*"\)/\1 \2/' \
-		-e 's/[@\\]sic  *\([^ ]*\) //g' \
-		-e 's/bt_curnext\.c/filename.c/g' \
-		-e 's/bt_curprev\.c/filename.c/g' \
-		-e 's/bt_vrfy\.c/filename.c/g' \
-		-e 's/bt_vrfy_dsk\.c/filename.c/g' \
-		-e 's/__verify_dsk_/__verify_disk_/g' \
-		-e 's/__wt_dsk_/__wt_disk_/g' \
-		-e 's/__wt_verify_dsk/__wt_verify_disk/g' \
-	   *.dox | tee yogbert | \
-	aspell --encoding=iso-8859-1 --lang=en_US --personal=./spell.ok list) |
-	sort -u > $t
-	test -s $t && {
-		echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
-		echo 'Documentation spelling notes'
-		echo 'Update src/docs/spell.ok to remove warnings.'
-		sed -e 's/^/	/' < $t
-		echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
-		e=1
-	}
+    (cd ../src/docs &&
+    # - Separate quoted newlines "line\nline" so "nline" is not reported.
+    # - Specifically ignore anything tagged @sic.
+    # - Specifically hide certain valid uses of the strings "curprev",
+    #   "curnext", "dsk", and "vrfy" so we can refer to the source files
+    #   and their function names in the architecture docs without making
+    #   "vrfy" and "dsk" legal spelling words.
+    sed \
+        -e 's/\("[^"]*\)\\n\([^"]*"\)/\1 \2/' \
+        -e 's/[@\\]sic  *\([^ ]*\) //g' \
+        -e 's/bt_curnext\.c/filename.c/g' \
+        -e 's/bt_curprev\.c/filename.c/g' \
+        -e 's/bt_vrfy\.c/filename.c/g' \
+        -e 's/bt_vrfy_dsk\.c/filename.c/g' \
+        -e 's/__verify_dsk_/__verify_disk_/g' \
+        -e 's/__wt_dsk_/__wt_disk_/g' \
+        -e 's/__wt_verify_dsk/__wt_verify_disk/g' \
+       *.dox | tee yogbert | \
+    aspell --encoding=iso-8859-1 --lang=en_US --personal=./spell.ok list) |
+    sort -u > $t
+    test -s $t && {
+        echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
+        echo 'Documentation spelling notes'
+        echo 'Update src/docs/spell.ok to remove warnings.'
+        sed -e 's/^/	/' < $t
+        echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
+        e=1
+    }
 }
 
 valid_build()
 {
-	# Complain if there are pages we don't reference directly.
-	sed -n '/<table.*directory/,/\/table/p' < ../docs/pages.html | \
-	    grep href > /dev/null && {
-		echo 'Unreferenced page: see docs/pages.html for the list.'
-		e=1
-	}
+    # Complain if there are pages we don't reference directly.
+    sed -n '/<table.*directory/,/\/table/p' < ../docs/pages.html | \
+        grep href > /dev/null && {
+        echo 'Unreferenced page: see docs/pages.html for the list.'
+        e=1
+    }
 
-	classf=`ls ../docs/struct___* 2>/dev/null`
-	for c in $classf; do
-		echo "$c: Add class to PREDEFINED in src/docs/$doxyfile, then remove docs/*.{html,js} and rebuild"
-	done
+    classf=`ls ../docs/struct___* 2>/dev/null`
+    for c in $classf; do
+        echo "$c: Add class to PREDEFINED in src/docs/$doxyfile, then remove docs/*.{html,js} and rebuild"
+    done
 
-	# Complain if \c markdown isn't right.
-	grep '=</code>(' ../docs/*.html > $t
-	test -s $t && {
-	    echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
-	    echo "Some <code> markup fragments are not correctly quoted, the output switched into"
-	    echo "typewrite format and then switched out of typewrite format before the fragment"
-	    echo "was complete. Probably a \\\c command that didn't span a parenthesis character."
-	    echo
-	    cat $t
-	    echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
-	    e=1
-	}
+    # Complain if \c markdown isn't right.
+    grep '=</code>(' ../docs/*.html > $t
+    test -s $t && {
+        echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
+        echo "Some <code> markup fragments are not correctly quoted, the output switched into"
+        echo "typewrite format and then switched out of typewrite format before the fragment"
+        echo "was complete. Probably a \\\c command that didn't span a parenthesis character."
+        echo
+        cat $t
+        echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
+        e=1
+    }
 }
 
 check_docs_data()
 {
-	python docs.py > $t
-	test -s $t && {
-		echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
-		echo 'Documentation data errors in docs_data.py'
-		sed -e 's/^/	/' < $t
-		echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
-		e=1
-	}
+    python docs.py > $t
+    test -s $t && {
+        echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
+        echo 'Documentation data errors in docs_data.py'
+        sed -e 's/^/	/' < $t
+        echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
+        e=1
+    }
 }
 
 build()
 {
-	# Build from scratch on demand.
-	[ "$1" -eq 0 ] || (cd .. && rm -rf docs && mkdir docs)
+    # Build from scratch on demand.
+    [ "$1" -eq 0 ] || (cd .. && rm -rf docs && mkdir docs)
 
-	# Run doxygen to generate warnings for the base HTML documentation.
-	#
-	# We omit Python because warnings are expected there (the code generated
-	# by swig does not have named arguments, but we want to document them
-	# as if they do.
-	(cd ../src/docs &&
-	    (eval cat $doxyfile $filter ; cat <<EOF
+    # Run doxygen to generate warnings for the base HTML documentation.
+    #
+    # We omit Python because warnings are expected there (the code generated
+    # by swig does not have named arguments, but we want to document them
+    # as if they do.
+    (cd ../src/docs &&
+        (eval cat $doxyfile $filter ; cat <<EOF
 QUIET=YES
 EOF
 ) | doxygen -
-	test -s doxygen.log && cat doxygen.log) > $t 2>&1
-	test -s $t && {
-		cat $t
-		e=1
-	}
+    test -s doxygen.log && cat doxygen.log) > $t 2>&1
+    test -s $t && {
+        cat $t
+        e=1
+    }
 
-	# Copy any needed javascript
-	cp ../src/docs/js/* ../docs/
+    # Copy any needed javascript
+    cp ../src/docs/js/* ../docs/
 
-	# Fix up bad links doxygen generates in navtree.js
-	(cd ../docs &&
-	    sed -i~ -e 's,/\.html,/,' -e 's,\.html\.html,.html,' navtree.js &&
-	    rm -f navtree.js~)
+    # Fix up bad links doxygen generates in navtree.js
+    (cd ../docs &&
+        sed -i~ -e 's,/\.html,/,' -e 's,\.html\.html,.html,' navtree.js &&
+        rm -f navtree.js~)
 
-	# Any cmapx files that are generated by plantuml need to be referred to
-	CMAPX=`find ../src/docs/ -type f -name "*.cmapx" 2>/dev/null`
-	if [ "$CMAPX" != '' ]; then
-		(cd ../docs
-		for f in $CMAPX; do
-			b=`echo $f | sed -e 's:.*/::' -e 's/.cmapx$//'`
-			for html in `grep -l $b.png *.html`; do
-				# There's an image in this HTML file that has a map file
-				# generated by plantuml.  Refer to the map by its name
-				# and insert the contents of the map into the HTML source.
-				sed -e "/<img.*=\"$b[.]png\"/s/\(\"$b[.]png\"\)/\1 usemap=\"#${b}_map\"/" \
-				    -e "/<img.*=\"$b[.]png\"/r $f" $html > $html.NEW
-				mv $html.NEW $html
-			done
-		done
-		)
-	fi
+    # Any cmapx files that are generated by plantuml need to be referred to
+    CMAPX=`find ../src/docs/ -type f -name "*.cmapx" 2>/dev/null`
+    if [ "$CMAPX" != '' ]; then
+        (cd ../docs
+        for f in $CMAPX; do
+            b=`echo $f | sed -e 's:.*/::' -e 's/.cmapx$//'`
+            for html in `grep -l $b.png *.html`; do
+                # There's an image in this HTML file that has a map file
+                # generated by plantuml.  Refer to the map by its name
+                # and insert the contents of the map into the HTML source.
+                sed -e "/<img.*=\"$b[.]png\"/s/\(\"$b[.]png\"\)/\1 usemap=\"#${b}_map\"/" \
+                    -e "/<img.*=\"$b[.]png\"/r $f" $html > $html.NEW
+                mv $html.NEW $html
+            done
+        done
+        )
+    fi
 }
 
 # Do not build the documentation if doxygen version is not compatible.
@@ -222,31 +222,31 @@ additional_languages=1
 filter="|sed '/PROJECT_BRIEF/s,=.*,=\"$WIREDTIGER_VERSION\",'"
 filter="$filter| sed '/PROJECT_NUMBER/s,=.*,=\"Version $WIREDTIGER_VERSION\",'"
 while :
-	do case "$1" in
-	-a)	# Build from scratch
-		clean=1
-		shift;;
-	-l)	# Generate the top-level landing page in ../docs/top
-		filter="$filter| sed '/GENERATE_MAN/s,=.*,=NO,';"
-		filter="$filter cat top/$doxyfile"
-		additional_languages=0
-		shift;;
-	-p)	# Generate PDFs
-		filter="$filter| sed '/GENERATE_LATEX/s,=.*,=YES,'"
-		shift;;
-	-t)	# Include the TODO list
-		filter="$filter| sed '/GENERATE_TODOLIST/s,=.*,=YES,'"
-		shift;;
-	-v)	# Override the version with <slug> <version string>
-		filter="$filter| sed '/HTML_HEADER/s,=.*,= style/header-web.html,'"
-		shift
-		filter="$filter| sed '/PROJECT_BRIEF/s,=.*,=\"$1\",'"
-		shift
-		filter="$filter| sed '/PROJECT_NUMBER/s,=.*,=\"$1\",'"
-		shift;;
-	*)
-		break;;
-	esac
+    do case "$1" in
+    -a)    # Build from scratch
+        clean=1
+        shift;;
+    -l)    # Generate the top-level landing page in ../docs/top
+        filter="$filter| sed '/GENERATE_MAN/s,=.*,=NO,';"
+        filter="$filter cat top/$doxyfile"
+        additional_languages=0
+        shift;;
+    -p)    # Generate PDFs
+        filter="$filter| sed '/GENERATE_LATEX/s,=.*,=YES,'"
+        shift;;
+    -t)    # Include the TODO list
+        filter="$filter| sed '/GENERATE_TODOLIST/s,=.*,=YES,'"
+        shift;;
+    -v)    # Override the version with <slug> <version string>
+        filter="$filter| sed '/HTML_HEADER/s,=.*,= style/header-web.html,'"
+        shift
+        filter="$filter| sed '/PROJECT_BRIEF/s,=.*,=\"$1\",'"
+        shift
+        filter="$filter| sed '/PROJECT_NUMBER/s,=.*,=\"$1\",'"
+        shift;;
+    *)
+        break;;
+    esac
 done
 
 # Generate the list of wtperf configuration options.
diff --git a/src/third_party/wiredtiger/dist/s_export b/src/third_party/wiredtiger/dist/s_export
--- a/src/third_party/wiredtiger/dist/s_export
+++ b/src/third_party/wiredtiger/dist/s_export
@@ -7,37 +7,37 @@ trap 'rm -f $t' 0 1 2 3 13 15
 
 case `uname` in
 Darwin)
-	NM='nm -gUo $f | egrep " T | D " | sed "s/ _/ /"'
-	;;
+    NM='nm -gUo $f | egrep " T | D " | sed "s/ _/ /"'
+    ;;
 *)
-	# We require GNU nm, which may not be installed.
-	type nm > /dev/null 2>&1 &&
-	    (nm --version | grep 'GNU nm') > /dev/null 2>&1 || {
-	    echo "$0 skipped: GNU nm not found"
-	    exit 0
-	}
-	NM='nm --extern-only --defined-only --print-file-name $f | egrep -v "__bss_start|_edata|_end|_fini|_init"'
-	;;
+    # We require GNU nm, which may not be installed.
+    type nm > /dev/null 2>&1 &&
+        (nm --version | grep 'GNU nm') > /dev/null 2>&1 || {
+        echo "$0 skipped: GNU nm not found"
+        exit 0
+    }
+    NM='nm --extern-only --defined-only --print-file-name $f | egrep -v "__bss_start|_edata|_end|_fini|_init"'
+    ;;
 esac
 
 check()
 {
-	(sed -e '/^#/d' s_export.list &&
-	eval $NM |
-	sed 's/.* //' |
-	egrep -v '^__wt') |
-	sort |
-	uniq -u |
-	egrep -v \
-	    'lz4_extension_init|snappy_extension_init|zlib_extension_init|zstd_extension_init' > $t
+    (sed -e '/^#/d' s_export.list &&
+    eval $NM |
+    sed 's/.* //' |
+    egrep -v '^__wt') |
+    sort |
+    uniq -u |
+    egrep -v \
+        'lz4_extension_init|snappy_extension_init|zlib_extension_init|zstd_extension_init' > $t
 
-	test -s $t && {
-		echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
-		echo 'unexpected external symbols in the WiredTiger library '"$f"
-		echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
-		cat $t
-		exit 1
-	}
+    test -s $t && {
+        echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
+        echo 'unexpected external symbols in the WiredTiger library '"$f"
+        echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
+        cat $t
+        exit 1
+    }
 }
 
 # This check would normally be done after the library is built, but this way
@@ -53,14 +53,14 @@ check()
 
 found=0
 for f in $(find .. -name "libwiredtiger.*" -print); do
-	case "$f" in
-	    *.a|*.so|*.dylib)
-		check "$f"
-		found=1
-	        ;;
-	    *)
-		;;
-	esac
+    case "$f" in
+        *.a|*.so|*.dylib)
+        check "$f"
+        found=1
+            ;;
+        *)
+        ;;
+    esac
 done
 
 if [ $found = 0 ]; then
diff --git a/src/third_party/wiredtiger/dist/s_string b/src/third_party/wiredtiger/dist/s_string
--- a/src/third_party/wiredtiger/dist/s_string
+++ b/src/third_party/wiredtiger/dist/s_string
@@ -11,37 +11,37 @@ export LC_ALL
 
 # If aspell has not been installed, quit
 type aspell > /dev/null 2>&1 || {
-	echo "$0 skipped: aspell not found"
-	exit 0
+    echo "$0 skipped: aspell not found"
+    exit 0
 }
 
 # replace:
-#	Create a replacement list of spelling words. This is here because the
+#    Create a replacement list of spelling words. This is here because the
 # words we ignore changes over time and it's worth periodically collapsing
 # the list. Don't it too often, the list is correct for many different aspell
 # catalogs and generating a shorter list on any single system will break other
 # systems.
 replace() {
-	aspell --mode=ccpp --lang=en_US list < ../$1 |
-	sort -u |
-	comm -12 /dev/stdin s_string.ok
+    aspell --mode=ccpp --lang=en_US list < ../$1 |
+    sort -u |
+    comm -12 /dev/stdin s_string.ok
 }
 
 # check:
-#	Check the spelling of an individual file.
+#    Check the spelling of an individual file.
 check() {
-	# Strip out git hashes, which are seven character hex strings.
-	# Strip out double quote char literals ('"'), they confuse aspell.
-	# Strip out calls to __wt_getopt so the option lists don't have to be spelling words.
-	# Strip out C-style hex constants.
-	sed -e 's/ [0-9a-f]\{7\} / /g' -e "s/'\"'//g" -e 's/__wt_getopt([^()]*)//' -e 's/0x[[:xdigit:]]\{1,\}/ /g' ../$2 |
-	aspell --lang=en_US $1 list |
-	sort -u |
-	comm -23 /dev/stdin s_string.ok > $t
-	test -s $t && {
-		echo "==== $2"
-		cat $t
-	}
+    # Strip out git hashes, which are seven character hex strings.
+    # Strip out double quote char literals ('"'), they confuse aspell.
+    # Strip out calls to __wt_getopt so the option lists don't have to be spelling words.
+    # Strip out C-style hex constants.
+    sed -e 's/ [0-9a-f]\{7\} / /g' -e "s/'\"'//g" -e 's/__wt_getopt([^()]*)//' -e 's/0x[[:xdigit:]]\{1,\}/ /g' ../$2 |
+    aspell --lang=en_US $1 list |
+    sort -u |
+    comm -23 /dev/stdin s_string.ok > $t
+    test -s $t && {
+        echo "==== $2"
+        cat $t
+    }
 }
 
 # List of files to spellchk.
@@ -53,26 +53,26 @@ l=`(cd .. &&
 
 usage()
 {
-	echo 'usage: s_string [-r]' >&2
-	exit 1
+    echo 'usage: s_string [-r]' >&2
+    exit 1
 }
 while :
-	do case "$1" in
-	-r)			# -r builds replacement list of OK words
-		for f in $l; do
-			replace $f
-		done | sort -u > $t
-		cp $t s_string.ok
-		shift;;
-	*)
-		test "$#" -eq 0 || usage
-		break;;
-	esac
+    do case "$1" in
+    -r)            # -r builds replacement list of OK words
+        for f in $l; do
+            replace $f
+        done | sort -u > $t
+        cp $t s_string.ok
+        shift;;
+    *)
+        test "$#" -eq 0 || usage
+        break;;
+    esac
 done
 
 # Check source files.
 for f in $l; do
-	check "--mode=ccpp" $f
+    check "--mode=ccpp" $f
 done
 
 exit 0
diff --git a/src/third_party/wiredtiger/dist/s_style b/src/third_party/wiredtiger/dist/s_style
--- a/src/third_party/wiredtiger/dist/s_style
+++ b/src/third_party/wiredtiger/dist/s_style
@@ -8,7 +8,7 @@ trap 'rm -f $t' 0 1 2 3 13 15
 xp=""
 echo date | xargs -P 20 >/dev/null 2>&1
 if test $? -eq 0; then
-	xp="-P 20"
+    xp="-P 20"
 fi
 
 # s_style is applied to every source file by default. It has a fast mode where it only runs against
@@ -29,220 +29,220 @@ fi
 if [ "$single_file" -ne 1 ]; then
     cd ..
     eval $search_str |
-	sed -e '/Makefile.in/d' \
-	    -e '/test\/3rdparty/d' \
-	    -e '/test\/checksum\/power8/d' \
-	    -e '/checksum\/zseries/d' |
-	xargs $xp -n 1 -I{} sh ./dist/s_style {}
+    sed -e '/Makefile.in/d' \
+        -e '/test\/3rdparty/d' \
+        -e '/test\/checksum\/power8/d' \
+        -e '/checksum\/zseries/d' |
+    xargs $xp -n 1 -I{} sh ./dist/s_style {}
 else
-	# General style correction and cleanup for a single file
-	f=$1
-	fname=`basename $f`
-	t=__wt_s_style.$fname.$$
+    # General style correction and cleanup for a single file
+    f=$1
+    fname=`basename $f`
+    t=__wt_s_style.$fname.$$
 
-	if [ ! -e $f ]; then
-		echo "$0 error $1 does not exist"
-		exit 1;
-	fi
+    if [ ! -e $f ]; then
+        echo "$0 error $1 does not exist"
+        exit 1;
+    fi
 
-	# Ignore styling errors of external libraries.
-	if expr "$f" : 'src/' > /dev/null &&
-	  ! expr "$f" : 'src/os_win/' > /dev/null &&
-	  ! expr "$f" : 'src/docs/' > /dev/null &&
-	  ! expr "$f" : 'src/tags' > /dev/null &&
-	  ! expr "$f" : 'src/.*/hash_city.*' > /dev/null &&
-	  ! expr "$f" : 'src/.*/huffman.*' > /dev/null &&
-	  ! expr "$f" : 'src/checksum.*' > /dev/null; then
+    # Ignore styling errors of external libraries.
+    if expr "$f" : 'src/' > /dev/null &&
+      ! expr "$f" : 'src/os_win/' > /dev/null &&
+      ! expr "$f" : 'src/docs/' > /dev/null &&
+      ! expr "$f" : 'src/tags' > /dev/null &&
+      ! expr "$f" : 'src/.*/hash_city.*' > /dev/null &&
+      ! expr "$f" : 'src/.*/huffman.*' > /dev/null &&
+      ! expr "$f" : 'src/checksum.*' > /dev/null; then
 
-		# Camel case style is not allowed.
-		if egrep -r -n '\b[a-z]+[A-Z]' $f | egrep -v ':[     ]+\*|"|UNCHECKED_STRING'; then
-			echo "$f: Styling requires variables that use underscores to separate parts of a name instead of camel casing.";
-		fi
-		
-		# Return values should be wrapped in parentheses.
-		egrep -r -n '^[^*/"]*[[:space:]]*return [^(]' $f > $t;
-		test -s $t && {
-			echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
-			echo 'Add parentheses to return values indicated below in file '"$f"
-			echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
-			cat $t
-		}
-	fi
+        # Camel case style is not allowed.
+        if egrep -r -n '\b[a-z]+[A-Z]' $f | egrep -v ':[     ]+\*|"|UNCHECKED_STRING'; then
+            echo "$f: Styling requires variables that use underscores to separate parts of a name instead of camel casing.";
+        fi
 
-	# Remove non-ascii characters and substitute some expressions with accepted version.
-	tr -cd '[:alnum:][:space:][:punct:]' < $f |
-	sed -e '/for /!s/;;$/;/' \
-	    -e 's/(EOPNOTSUPP)/(ENOTSUP)/' \
-	    -e 's/(unsigned)/(u_int)/' \
-	    -e 's/hazard reference/hazard pointer/' >$t
+        # Return values should be wrapped in parentheses.
+        egrep -r -n '^[^*/"]*[[:space:]]*return [^(]' $f > $t;
+        test -s $t && {
+            echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
+            echo 'Add parentheses to return values indicated below in file '"$f"
+            echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
+            cat $t
+        }
+    fi
 
-	cmp $t $f > /dev/null 2>&1 || (echo "modifying $f" && cp $t $f)
+    # Remove non-ascii characters and substitute some expressions with accepted version.
+    tr -cd '[:alnum:][:space:][:punct:]' < $f |
+    sed -e '/for /!s/;;$/;/' \
+        -e 's/(EOPNOTSUPP)/(ENOTSUP)/' \
+        -e 's/(unsigned)/(u_int)/' \
+        -e 's/hazard reference/hazard pointer/' >$t
 
-	# Finding paired typos in the comments of different file types and excluding invalid edge cases.
-	if [ "${fname##*.}" = "py" ]; then
-		egrep '#.*[[:space:]]\b([a-zA-Z]+)[[:space:]]\b\1[[:space:]\.]' $f > $t
-	elif [ "${fname##*.}" = "c" ] || [ "${fname##*.}" = "h" ]; then
-		egrep '/?\*.*[[:space:]]\b([a-zA-Z]+)[[:space:]]\b\1[[:space:]\.]' $f | egrep -v -e "@" -e "long long" > $t
-	else
-		egrep '[[:space:]]\b([a-zA-Z]+)[[:space:]]\b\1[[:space:]\.]' $f | egrep -v -e "@" -e "^\(" > $t
-	fi
+    cmp $t $f > /dev/null 2>&1 || (echo "modifying $f" && cp $t $f)
 
-	test -s $t && {
-		echo "paired typo"
-		echo "============================"
-		echo $f
-		cat $t
-	}
+    # Finding paired typos in the comments of different file types and excluding invalid edge cases.
+    if [ "${fname##*.}" = "py" ]; then
+        egrep '#.*[[:space:]]\b([a-zA-Z]+)[[:space:]]\b\1[[:space:]\.]' $f > $t
+    elif [ "${fname##*.}" = "c" ] || [ "${fname##*.}" = "h" ]; then
+        egrep '/?\*.*[[:space:]]\b([a-zA-Z]+)[[:space:]]\b\1[[:space:]\.]' $f | egrep -v -e "@" -e "long long" > $t
+    else
+        egrep '[[:space:]]\b([a-zA-Z]+)[[:space:]]\b\1[[:space:]\.]' $f | egrep -v -e "@" -e "^\(" > $t
+    fi
 
-	extension="${fname##*.}"
-	if [ "x$extension" = "xdox" ]; then
-		exit 0;
-	fi
+    test -s $t && {
+        echo "paired typo"
+        echo "============================"
+        echo $f
+        cat $t
+    }
 
-	if grep "^[^}]*while (0);" $f > $t; then
-		echo "$f: while (0) has trailing semi-colon"
-		cat $t
-	fi
+    extension="${fname##*.}"
+    if [ "x$extension" = "xdox" ]; then
+        exit 0;
+    fi
 
-	if grep WT_DEADLOCK $f | grep -v '#define.WT_DEADLOCK' > $t; then
-		echo "$f: WT_DEADLOCK deprecated in favor of WT_ROLLBACK"
-		cat $t
-	fi
+    if grep "^[^}]*while (0);" $f > $t; then
+        echo "$f: while (0) has trailing semi-colon"
+        cat $t
+    fi
 
-	if grep 'sizeof(WT_UPDATE)' $f > $t; then
-		echo "$f: Use WT_UPDATE_SIZE rather than sizeof(WT_UPDATE)"
-		cat $t
-	fi
+    if grep WT_DEADLOCK $f | grep -v '#define.WT_DEADLOCK' > $t; then
+        echo "$f: WT_DEADLOCK deprecated in favor of WT_ROLLBACK"
+        cat $t
+    fi
 
-	if ! expr "$f" : 'examples/c/.*' > /dev/null &&
-	   ! expr "$f" : 'ext/.*' > /dev/null &&
-	   ! expr "$f" : 'src/include/wiredtiger_ext\.h' > /dev/null &&
-	   ! expr "$f" : 'src/txn/txn_ext\.c' > /dev/null &&
-	   grep WT_TXN_ISO_ $f; then
-		echo "$f: WT_TXN_ISO_XXX constants only for the extension API"
-		cat $t
-	fi
+    if grep 'sizeof(WT_UPDATE)' $f > $t; then
+        echo "$f: Use WT_UPDATE_SIZE rather than sizeof(WT_UPDATE)"
+        cat $t
+    fi
 
-	if ! expr "$f" : 'src/include/queue\.h' > /dev/null &&
-	    egrep 'STAILQ_|SLIST_|\bLIST_' $f ; then
-		echo "$f: use TAILQ for all lists"
-	fi
+    if ! expr "$f" : 'examples/c/.*' > /dev/null &&
+       ! expr "$f" : 'ext/.*' > /dev/null &&
+       ! expr "$f" : 'src/include/wiredtiger_ext\.h' > /dev/null &&
+       ! expr "$f" : 'src/txn/txn_ext\.c' > /dev/null &&
+       grep WT_TXN_ISO_ $f; then
+        echo "$f: WT_TXN_ISO_XXX constants only for the extension API"
+        cat $t
+    fi
 
-	if ! expr "$f" : 'src/include/extern.h' > /dev/null &&
-	   ! expr "$f" : 'src/include/extern_posix.h' > /dev/null &&
-	   ! expr "$f" : 'src/include/extern_win.h' > /dev/null &&
-	   ! expr "$f" : 'src/include/os.h' > /dev/null &&
-	   ! expr "$f" : 'src/os_common/.*' > /dev/null &&
-	   ! expr "$f" : 'src/os_posix/.*' > /dev/null &&
-	   ! expr "$f" : 'src/os_win/.*' > /dev/null &&
-	    grep '__wt_errno' $f > $t; then
-		echo "$f: upper-level code should not call __wt_errno"
-		cat $t
-	fi
+    if ! expr "$f" : 'src/include/queue\.h' > /dev/null &&
+        egrep 'STAILQ_|SLIST_|\bLIST_' $f ; then
+        echo "$f: use TAILQ for all lists"
+    fi
 
-	if ! expr "$f" : 'examples/c/.*' > /dev/null &&
-	   ! expr "$f" : 'src/include/os.h' > /dev/null &&
-	    egrep "%[0-9]*zu" $f | grep -v 'SIZET_FMT' > $t; then
-		echo "$f: %zu needs to be fixed for Windows"
-		cat $t
-	fi
+    if ! expr "$f" : 'src/include/extern.h' > /dev/null &&
+       ! expr "$f" : 'src/include/extern_posix.h' > /dev/null &&
+       ! expr "$f" : 'src/include/extern_win.h' > /dev/null &&
+       ! expr "$f" : 'src/include/os.h' > /dev/null &&
+       ! expr "$f" : 'src/os_common/.*' > /dev/null &&
+       ! expr "$f" : 'src/os_posix/.*' > /dev/null &&
+       ! expr "$f" : 'src/os_win/.*' > /dev/null &&
+        grep '__wt_errno' $f > $t; then
+        echo "$f: upper-level code should not call __wt_errno"
+        cat $t
+    fi
 
-	egrep -w 'off_t' $f > $t
-	test -s $t && {
-		echo "$f: off_t type declaration, use wt_off_t"
-		cat $t
-	}
+    if ! expr "$f" : 'examples/c/.*' > /dev/null &&
+       ! expr "$f" : 'src/include/os.h' > /dev/null &&
+        egrep "%[0-9]*zu" $f | grep -v 'SIZET_FMT' > $t; then
+        echo "$f: %zu needs to be fixed for Windows"
+        cat $t
+    fi
 
-	if ! expr "$f" : 'src/include/misc.h' > /dev/null &&
-	    grep '[[:space:]]qsort(' $f > $t; then
-		echo "$f: qsort call, use WiredTiger __wt_qsort instead"
-		cat $t
-	fi
+    egrep -w 'off_t' $f > $t
+    test -s $t && {
+        echo "$f: off_t type declaration, use wt_off_t"
+        cat $t
+    }
 
-	if ! expr "$f" : 'src/.*/os_setvbuf.c' > /dev/null &&
-	    egrep -w 'setvbuf' $f > $t; then
-		echo "$f: setvbuf call, use WiredTiger library replacements"
-		cat $t
-	fi
+    if ! expr "$f" : 'src/include/misc.h' > /dev/null &&
+        grep '[[:space:]]qsort(' $f > $t; then
+        echo "$f: qsort call, use WiredTiger __wt_qsort instead"
+        cat $t
+    fi
 
-	if ! expr "$f" : 'examples/c/*' > /dev/null &&
-	   ! expr "$f" : 'bench/*' > /dev/null &&
-	   ! expr "$f" : '.*cxx' > /dev/null &&
-	   ! expr "$f" : '.*cpp' > /dev/null &&
-	   ! expr "$f" : 'ext/*' > /dev/null &&
-	   ! expr "$f" : 'src/os_posix/os_snprintf.c' > /dev/null &&
-	    egrep '[^a-z_]snprintf\(|[^a-z_]vsnprintf\(' $f > $t; then
-		echo "$f: snprintf call, use WiredTiger library replacements"
-		cat $t
-	fi
+    if ! expr "$f" : 'src/.*/os_setvbuf.c' > /dev/null &&
+        egrep -w 'setvbuf' $f > $t; then
+        echo "$f: setvbuf call, use WiredTiger library replacements"
+        cat $t
+    fi
 
-	# If we don't have matching pack-begin and pack-end calls, we don't get
-	# an error, we just get a Windows performance regression. Using awk and
-	# not wc to ensure there's no whitespace in the assignment.
-	egrep WT_PACKED_STRUCT $f > $t
-	cnt=`awk 'BEGIN { line = 0 } { ++line } END { print line }' < $t`
-	test `expr "$cnt" % 2` -ne 0 && {
-		echo "$f: mismatched WT_PACKED_STRUCT_BEGIN/END lines"
-		cat $t
-	}
+    if ! expr "$f" : 'examples/c/*' > /dev/null &&
+       ! expr "$f" : 'bench/*' > /dev/null &&
+       ! expr "$f" : '.*cxx' > /dev/null &&
+       ! expr "$f" : '.*cpp' > /dev/null &&
+       ! expr "$f" : 'ext/*' > /dev/null &&
+       ! expr "$f" : 'src/os_posix/os_snprintf.c' > /dev/null &&
+        egrep '[^a-z_]snprintf\(|[^a-z_]vsnprintf\(' $f > $t; then
+        echo "$f: snprintf call, use WiredTiger library replacements"
+        cat $t
+    fi
 
-	# Direct calls to functions we're not supposed to use in the library.
-	# We don't check for all of them, just a few of the common ones.
-	if ! expr "$f" : 'bench/.*' > /dev/null &&
-	   ! expr "$f" : 'examples/.*' > /dev/null &&
-	   ! expr "$f" : 'ext/.*' > /dev/null &&
-	   ! expr "$f" : 'test/.*' > /dev/null &&
-	   ! expr "$f" : '.*/utilities/.*' > /dev/null; then
-		if ! expr "$f" : '.*/os_alloc.c' > /dev/null &&
-		     egrep '[[:space:]]free[(]|[[:space:]]strdup[(]|[[:space:]]strndup[(]|[[:space:]]malloc[(]|[[:space:]]calloc[(]|[[:space:]]realloc[(]|[[:space:]]sprintf[(]' $f > $t; then
-			test -s $t && {
-				echo "$f: call to illegal function"
-				cat $t
-			}
-		fi
-		if ! expr "$f" : '.*/os_strtouq.c' > /dev/null &&
-		     egrep '[[:space:]]strtouq[(]' $f > $t; then
-			test -s $t && {
-				echo "$f: call to illegal function"
-				cat $t
-			}
-		fi
-		if egrep '[[:space:]]exit[(]' $f > $t; then
-			test -s $t && {
-				echo "$f: call to illegal function"
-				cat $t
-			}
-		fi
-	fi
+    # If we don't have matching pack-begin and pack-end calls, we don't get
+    # an error, we just get a Windows performance regression. Using awk and
+    # not wc to ensure there's no whitespace in the assignment.
+    egrep WT_PACKED_STRUCT $f > $t
+    cnt=`awk 'BEGIN { line = 0 } { ++line } END { print line }' < $t`
+    test `expr "$cnt" % 2` -ne 0 && {
+        echo "$f: mismatched WT_PACKED_STRUCT_BEGIN/END lines"
+        cat $t
+    }
 
-	# Declaration of an integer return variable.
-	if ! expr "$f" : 'bench/.*' > /dev/null &&
-	   ! expr "$f" : 'examples/.*' > /dev/null &&
-	   ! expr "$f" : 'test/.*' > /dev/null &&
-	   ! expr "$f" : 'ext/.*' > /dev/null; then
-	   # This regex can return false positives on functions that take ret as
-	   # an argument. Filter out matches that contain brackets.
-		egrep -w ret $f | egrep 'int.*[, ]ret[,;]' | egrep -v '[()]' > $t
-		test -s $t && {
-			echo "$f: explicit declaration of \"ret\""
-			cat $t
-		}
-	fi
+    # Direct calls to functions we're not supposed to use in the library.
+    # We don't check for all of them, just a few of the common ones.
+    if ! expr "$f" : 'bench/.*' > /dev/null &&
+       ! expr "$f" : 'examples/.*' > /dev/null &&
+       ! expr "$f" : 'ext/.*' > /dev/null &&
+       ! expr "$f" : 'test/.*' > /dev/null &&
+       ! expr "$f" : '.*/utilities/.*' > /dev/null; then
+        if ! expr "$f" : '.*/os_alloc.c' > /dev/null &&
+             egrep '[[:space:]]free[(]|[[:space:]]strdup[(]|[[:space:]]strndup[(]|[[:space:]]malloc[(]|[[:space:]]calloc[(]|[[:space:]]realloc[(]|[[:space:]]sprintf[(]' $f > $t; then
+            test -s $t && {
+                echo "$f: call to illegal function"
+                cat $t
+            }
+        fi
+        if ! expr "$f" : '.*/os_strtouq.c' > /dev/null &&
+             egrep '[[:space:]]strtouq[(]' $f > $t; then
+            test -s $t && {
+                echo "$f: call to illegal function"
+                cat $t
+            }
+        fi
+        if egrep '[[:space:]]exit[(]' $f > $t; then
+            test -s $t && {
+                echo "$f: call to illegal function"
+                cat $t
+            }
+        fi
+    fi
 
-	# Use of ctype functions that sign extend their arguments.
-	if ! expr "$f" : 'bench/.*' > /dev/null &&
-	   ! expr "$f" : 'test/csuite/.*' > /dev/null &&
-	   ! expr "$f" : 'examples/.*' > /dev/null &&
-	   ! expr "$f" : 'ext/.*' > /dev/null &&
-	   ! expr "$f" : '.*py' > /dev/null &&
-	   ! expr "$f" : 'src/include/ctype.i' > /dev/null; then
-		if egrep '(#include.*["</]ctype.h[">]|\b(is(alnum|alpha|cntrl|digit|graph|lower|print|punct|space|upper|xdigit)|to(lower|toupper))\()' $f > $t; then
-			test -s $t && {
-				echo "$f: direct use of ctype.h functions, instead of ctype.i equivalents"
-				cat $t
-			}
-		fi
-	fi
+    # Declaration of an integer return variable.
+    if ! expr "$f" : 'bench/.*' > /dev/null &&
+       ! expr "$f" : 'examples/.*' > /dev/null &&
+       ! expr "$f" : 'test/.*' > /dev/null &&
+       ! expr "$f" : 'ext/.*' > /dev/null; then
+       # This regex can return false positives on functions that take ret as
+       # an argument. Filter out matches that contain brackets.
+        egrep -w ret $f | egrep 'int.*[, ]ret[,;]' | egrep -v '[()]' > $t
+        test -s $t && {
+            echo "$f: explicit declaration of \"ret\""
+            cat $t
+        }
+    fi
+
+    # Use of ctype functions that sign extend their arguments.
+    if ! expr "$f" : 'bench/.*' > /dev/null &&
+       ! expr "$f" : 'test/csuite/.*' > /dev/null &&
+       ! expr "$f" : 'examples/.*' > /dev/null &&
+       ! expr "$f" : 'ext/.*' > /dev/null &&
+       ! expr "$f" : '.*py' > /dev/null &&
+       ! expr "$f" : 'src/include/ctype.i' > /dev/null; then
+        if egrep '(#include.*["</]ctype.h[">]|\b(is(alnum|alpha|cntrl|digit|graph|lower|print|punct|space|upper|xdigit)|to(lower|toupper))\()' $f > $t; then
+            test -s $t && {
+                echo "$f: direct use of ctype.h functions, instead of ctype.i equivalents"
+                cat $t
+            }
+        fi
+    fi
 fi
 
 exit 0
diff --git a/src/third_party/wiredtiger/dist/s_tags b/src/third_party/wiredtiger/dist/s_tags
--- a/src/third_party/wiredtiger/dist/s_tags
+++ b/src/third_party/wiredtiger/dist/s_tags
@@ -8,22 +8,22 @@ test -n "$WT_RELEASE_BUILD" && exit 0
 
 # We have to be in the dist directory to run.
 test -f s_tags || {
-	echo "s_tags requires dist be the current working directory"
-	exit 1
+    echo "s_tags requires dist be the current working directory"
+    exit 1
 }
 
 # We require ctags which may not be installed.
 type ctags > /dev/null 2>&1 || {
-	echo "$0 skipped: ctags not found"
-	exit 0
+    echo "$0 skipped: ctags not found"
+    exit 0
 }
 
 # Test to see what flags this ctags binary supports.
 flags=""
 for i in -d -t -w --language-force=C '-I WT_GCC_FUNC_ATTRIBUTE+'; do
-	if ctags $i ../src/conn/api_strerror.c 2>/dev/null; then
-		flags="$i $flags"
-	fi
+    if ctags $i ../src/conn/api_strerror.c 2>/dev/null; then
+        flags="$i $flags"
+    fi
 done
 
 # If it exists, generate a tags file for the build directory. The user can have
@@ -42,17 +42,17 @@ ctags $flags ../include/*.in `find .. -name '*.[ch]'` 2>/dev/null)
 # at the right level.
 link_tag()
 {
-	if test -e ../include/tags; then
-		rm -f tags && ln -s ../include/tags .
-	fi
+    if test -e ../include/tags; then
+        rm -f tags && ln -s ../include/tags .
+    fi
 }
 
 # Link to the tags file from standard build and source directories.
 dirs="`python -c 'import dist; dist.print_source_dirs()'` ../src/os_win"
 for i in $dirs; do
-	expr "$i" : ".*/include" > /dev/null && continue
+    expr "$i" : ".*/include" > /dev/null && continue
 
-	(cd $i && link_tag)
+    (cd $i && link_tag)
 done
 
 exit 0
