7.0 WT Changes

diff --git a/src/third_party/wiredtiger/dist/s_all b/src/third_party/wiredtiger/dist/s_all
--- a/src/third_party/wiredtiger/dist/s_all
+++ b/src/third_party/wiredtiger/dist/s_all
@@ -7,30 +7,36 @@ trap 'rm -f $t *.pyc __tmp __wt.* __s_all_tmp*' 0 1 2 3 13 15
 
 # We require python which may not be installed.
 type python > /dev/null 2>&1 || {
-	echo 's_all: python not found'
-	exit 1
+    echo 's_all: python not found'
+    exit 1
 }
 
 echo 'dist/s_all run started...'
 
+fast=""
 force=
 reconf=0
 errmode=0
 errfound=0
+
 while :
-	do case "$1" in
-	-A)	# Reconfigure the library build.
-		reconf=1
-		shift;;
-	-E)	# Return an error code on failure
-		errmode=1
-		shift;;
-	-f)	# Force versions to be updated
-		force="-f"
-		shift;;
-	*)
-		break;;
-	esac
+    do case "$1" in
+    -A)    # Reconfigure the library build.
+        reconf=1
+        shift;;
+    -E)    # Return an error code on failure
+        errmode=1
+        shift;;
+    -f)    # Force versions to be updated
+        force="-f"
+        shift;;
+    -F) # Run fast.
+        echo "dist/s_all running in fast mode..."
+        fast="-F"
+        shift;;
+    *)
+        break;;
+    esac
 done
 
 echo "Updating files that include the package version" &&
@@ -38,41 +44,30 @@ echo "Updating files that include the package version" &&
 
 errchk()
 {
-	if ! `test -s $2`; then
-		return
-	fi
+    if ! `test -s $2`; then
+        return
+    fi
 
-	# Return if evergreen validate runs sucessfully.
-	if echo "$1" | grep -q evergreen && [ "$(cat "$2")" = "../test/evergreen.yml is valid" ] ; then
-		rm -f "$2"
-		return
-	fi
+    echo "####################### MESSAGE ############################"
+    echo "s_all run of: \"$1\" resulted in:"
+    sed -e 's/^/    /' $2
+    echo "#######################"
 
-	echo "####################### MESSAGE ############################"
-	echo "s_all run of: \"$1\" resulted in:"
-	sed -e 's/^/    /' $2
-	echo "#######################"
+    # If the test was skipped or marked warning only, ignore the failure.
+    if [ ! `grep "$1.*skipped" $2 > /dev/null` ] && [ ! "$3" = "--warning-only" ] ; then
+        errfound=1;
+    fi
 
-	# If the test was skipped, ignore the failure.
-	if ! `grep "$1.*skipped" $2 > /dev/null`; then
-	    errfound=1;
-	fi
-
-	# Ignore errors if the script is marked warning-only
-	if [ "$3" = "--warning-only" ]; then
-		errfound=0;
-	fi
-
-	rm -f $2
+    rm -f $2
 }
 
 run()
 {
-	2>&1 $1 > $t
-	errchk "$1" $t "$2"
+    2>&1 $1 > $t
+    errchk "$1" $t "$2"
 }
 
-# Non parallelizable scripts The following scripts either modify files or
+# Non parallelizable scripts. The following scripts either modify files or
 # already parallelize internally.
 run "sh ./s_readme $force"
 run "sh ./s_install $force"
@@ -83,24 +78,23 @@ run "python log.py"
 run "python stat.py"
 run "python verbose.py"
 run "sh ./s_copyright"
-run "sh ./s_style"
-run "./s_clang-format"
+run "sh ./s_style ${fast}"
+run "./s_clang_format ${fast}"
 run "python prototypes.py"
 run "sh ./s_typedef -b"
 run "python test_tag.py"
 # The s_mentions script requires bash.
 run "./s_mentions" "--warning-only"
-if command -v evergreen > /dev/null; then
-	run "evergreen validate ../test/evergreen.yml"
-fi
 
 COMMANDS="
 2>&1 ./s_define > ${t_pfx}s_define
 2>&1 ./s_docs > ${t_pfx}s_docs
 2>&1 ./s_evergreen > ${t_pfx}s_evergreen
+2>&1 ./s_evergreen_validate ${fast} > ${t_pfx}s_evergreen_validate
 2>&1 ./s_export > ${t_pfx}s_export
+2>&1 ./s_free > ${t_pfx}s_free
 2>&1 ./s_funcs > ${t_pfx}s_funcs
-2>&1 ./s_function > ${t_pfx}s_function
+2>&1 ./s_function ${fast} > ${t_pfx}s_function
 2>&1 ./s_getopt > ${t_pfx}s_getopt
 2>&1 ./s_lang > ${t_pfx}s_lang
 2>&1 ./s_longlines > ${t_pfx}s_longlines
@@ -111,29 +105,34 @@ COMMANDS="
 2>&1 ./s_typedef -c > ${t_pfx}s_typedef_c
 2>&1 ./s_void > ${t_pfx}s_void
 2>&1 ./s_whitespace > ${t_pfx}s_whitespace
-2>&1 python function.py > ${t_pfx}py_function
-2>&1 python style.py > ${t_pfx}py_style"
+2>&1 python3 function.py > ${t_pfx}py_function
+2>&1 python3 style.py > ${t_pfx}py_style
+2>&1 python3 comment_style.py ${fast} > ${t_pfx}py_comment_style
+2>&1 python3 type_to_str.py > ${t_pfx}py_type_to_str
+" # the closing quote needs to be on a separate line, or the wrong command is run.
 
 # Parallelize if possible.
 xp=""
 echo date | xargs -P 20 >/dev/null 2>&1
 if test $? -eq 0; then
-	xp="-P 20"
+    xp="-P 20"
 fi
 echo "$COMMANDS" | xargs $xp -I{} /bin/sh -c {}
 
-for f in `find . -name ${t_pfx}\*`; do
-	if `test -s $f`; then
-		LOCAL_NAME=`basename $f`
-		# Find original command and trim redirect garbage
-		FAILED_CMD=`echo "$COMMANDS" | grep $LOCAL_NAME | \
-		    sed -e 's/ >.*//' -e 's/.* //'`
-		errchk "$FAILED_CMD" $f
-	fi
-done
+# For each command check if an output file has been generated. If it has, report the contents and
+# the command used to populate it.
+while read -r line ; do
+    outputfile=$(echo "$line" | sed -e 's/.* > //')
+    if test -s "$outputfile" ; then
+        check=$(echo "$line" | sed -e 's/ >.*//' -e 's/2>&1 //')
+        errchk "$check" "$outputfile"
+    fi
+done <<EOT
+"$COMMANDS"
+EOT
 
-echo 'dist/s_all run finished'
+echo "dist/s_all run finished. Error? $errfound"
 if test $errmode -ne 0; then
-	exit $errfound;
+    exit $errfound;
 fi
 exit 0
diff --git a/src/third_party/wiredtiger/dist/s_docs_plantuml b/src/third_party/wiredtiger/dist/s_docs_plantuml
--- a/src/third_party/wiredtiger/dist/s_docs_plantuml
+++ b/src/third_party/wiredtiger/dist/s_docs_plantuml
@@ -13,41 +13,41 @@ PLANTUML_URL="https://downloads.sourceforge.net/project/plantuml/plantuml.jar?r=
 
 # We require java which may not be installed.
 type java > /dev/null 2>&1 || {
-	echo "$0 skipped: java not found"
-	exit 0
+    echo "$0 skipped: java not found"
+    exit 0
 }
 
 download_plantuml=0
 while :
-	do case "$1" in
-	-d)	# Download plantuml if not already there
-		download_plantuml=1
-		shift;;
-	*)
-		break;;
-	esac
+    do case "$1" in
+    -d)    # Download plantuml if not already there
+        download_plantuml=1
+        shift;;
+    *)
+        break;;
+    esac
 done
 
 # plantuml is needed, check if already downloaded, else download if suggested
 # by an argument
 test -f "../dist/plantuml.jar" || {
-	echo 'dist/plantuml.jar not found. '
-	if [ $download_plantuml -eq 1 ]
-	then
-		echo 'Downloading plantuml:'
-		curl -Li $PLANTUML_URL -o ../dist/plantuml.jar
-	else
-		echo 'plantuml can be downloaded from:'
-		echo 'https://sourceforge.net/projects/plantuml/files/plantuml.jar/download'
-		echo 'To download automatically pass -d argument to the script'
-		exit 1
-	fi
+    echo 'dist/plantuml.jar not found. '
+    if [ $download_plantuml -eq 1 ]
+    then
+        echo 'Downloading plantuml:'
+        curl -Li $PLANTUML_URL -o ../dist/plantuml.jar
+    else
+        echo 'plantuml can be downloaded from:'
+        echo 'https://sourceforge.net/projects/plantuml/files/plantuml.jar/download'
+        echo 'To download automatically pass -d argument to the script'
+        exit 1
+    fi
 }
 
 # Check plantuml works as expected
 java -jar ../dist/plantuml.jar -testdot > /dev/null || {
-	echo 'error: plantuml installation check failed'
-	exit 1
+    echo 'error: plantuml installation check failed'
+    exit 1
 }
 
 # Generate PlantUML docs. This command looks for plantuml template code embedded
diff --git a/src/third_party/wiredtiger/dist/s_evergreen b/src/third_party/wiredtiger/dist/s_evergreen
--- a/src/third_party/wiredtiger/dist/s_evergreen
+++ b/src/third_party/wiredtiger/dist/s_evergreen
@@ -11,14 +11,14 @@ ${program} check >$t 2>&1
 e=$?
 
 test -s $t && {
-	echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
-	echo "$0: $program check"
-	cat $t
-	echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
+    echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
+    echo "$0: $program check"
+    cat $t
+    echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
 
-	# Don't exit non-zero unless the python script did, the script
-	# requires python modules that are commonly not installed, and
-	# in that case it exits 0. Post the complaint, but don't fail.
-	exit $e
+    # Don't exit non-zero unless the python script did, the script
+    # requires python modules that are commonly not installed, and
+    # in that case it exits 0. Post the complaint, but don't fail.
+    exit $e
 }
 exit 0
diff --git a/src/third_party/wiredtiger/dist/s_string b/src/third_party/wiredtiger/dist/s_string
--- a/src/third_party/wiredtiger/dist/s_string
+++ b/src/third_party/wiredtiger/dist/s_string
@@ -11,72 +11,87 @@ export LC_ALL
 
 # If aspell has not been installed, quit
 type aspell > /dev/null 2>&1 || {
-	echo "$0 skipped: aspell not found"
-	exit 0
+    echo "$0 skipped: aspell not found"
+    exit 0
 }
 
 # replace:
-#	Create a replacement list of spelling words. This is here because the
+#    Create a replacement list of spelling words. This is here because the
 # words we ignore changes over time and it's worth periodically collapsing
 # the list. Don't it too often, the list is correct for many different aspell
 # catalogs and generating a shorter list on any single system will break other
 # systems.
 replace() {
-	aspell --mode=ccpp --lang=en_US list < ../$1 |
-	sort -u |
-	comm -12 /dev/stdin s_string.ok
+    aspell --mode=ccpp --lang=en_US list < ../$1 |
+    sort -u |
+    comm -12 /dev/stdin s_string.ok
 }
 
 # check:
-#	Check the spelling of an individual file.
+#    Check the spelling of an individual file.
 check() {
-	# Strip out git hashes, which are seven character hex strings.
-	# Strip out double quote char literals ('"'), they confuse aspell.
-	# Strip out calls to __wt_getopt so the option lists don't have to be spelling words.
-	# Strip out C-style hex constants.
-	sed -e 's/ [0-9a-f]\{7\} / /g' -e "s/'\"'//g" -e 's/__wt_getopt([^()]*)//' -e 's/0x[[:xdigit:]]\{1,\}/ /g' ../$2 |
-	aspell --lang=en_US $1 list |
-	sort -u |
-	comm -23 /dev/stdin s_string.ok > $t
-	test -s $t && {
-		echo "==== $2"
-		cat $t
-	}
+    # Strip out git hashes, which are seven character hex strings.
+    # Strip out double quote char literals ('"'), they confuse aspell.
+    # Strip out calls to __wt_getopt so the option lists don't have to be spelling words.
+    # Strip out C-style hex constants.
+    sed -e 's/ [0-9a-f]\{7\} / /g' -e "s/'\"'//g" -e 's/__wt_getopt([^()]*)//' -e 's/0x[[:xdigit:]]\{1,\}/ /g' ../$2 |
+    aspell --lang=en_US $1 list |
+    sort -u |
+    comm -23 /dev/stdin s_string.ok > $t
+    test -s $t && {
+        echo "==== $2"
+        cat $t
+    }
 }
 
 # List of files to spellchk.
-l=`(cd .. &&
+l=$(cd .. &&
     find bench examples ext src test -name '*.[chsy]' &&
-    find src -name '*.in' && find test -name '*.cxx' && find test -name '*.cpp')`
+    find src -name '*.in' &&
+    find test -name '*.cpp')
 
 usage()
 {
-	echo 'usage: s_string [-r]' >&2
-	exit 1
+    echo 'usage: s_string [-r]' >&2
+    exit 1
 }
+
+exit_val=0
 while :
-	do case "$1" in
-	-r)			# -r builds replacement list of OK words
-		for f in $l; do
-			replace $f
-		done | sort -u > $t
-		cp $t s_string.ok
-		shift;;
-	*)
-		test "$#" -eq 0 || usage
-		break;;
-	esac
+    do case "$1" in
+    -r)            # -r builds replacement list of OK words
+        for f in $l; do
+            replace $f
+        done | sort -u > $t
+
+        # Between aspell versions 0.60.7-20110707 and 0.60.8 the following program names have been
+        # added to the dictionary and are no longer considered spelling errors. This means
+        # that building a replacement list of words with the newer version of aspell will omit them
+        # from s_string.ok, and subsequently running s_string with older aspell version will
+        # report spelling errors. Manually whitelist these names to address this.
+        prog_names="AWS AWS's MongoDB MONGODB PostgreSQL sanitizer sanitizers"
+        for name in $prog_names; do
+            echo $name >> $t
+        done
+        sort -u -o $t $t
+
+	if ! diff $t s_string.ok >/dev/null 2>&1; then
+            echo "The string.ok list will be updated."
+            cp $t s_string.ok
+            exit_val=1
+        else
+            echo "No need to update the string.ok list."
+        fi
+        shift;;
+    *)
+        test "$#" -eq 0 || usage
+        break;;
+    esac
 done
 
 # Check source files.
 for f in $l; do
-	check "--mode=ccpp" $f
+    check "--mode=ccpp" $f
 done
 
-l="NEWS"
-# Check other files.
-for f in $l; do
-	check "" $f
-done
-
-exit 0
+exit $exit_val
