Import wiredtiger: 0724d88d2527bda48d0cf284237f19f01d6bf7e6 from branch mongodb-4.2
ref: 91e1466e1d..0724d88d25
for: 4.2.16

WT-6568       Fix split generation use
WT-6926       Update WiredTiger source code to include 2021 copyright notices
WT-7135       Additional checks to detect when writing corrupted metadata
WT-7437       Upgrade documentation to doxygen 1.8.17
WT-7675       Query last ckpt timestamp changes without taking checkpoint
WT-7721       Update test-format to reopen an existing database with different config
WT-7776       Add a hard limit on the number of modify updates before we instantiate a complete update
WT-7871       Remove comment that is no longer true

diff --git a/src/third_party/wiredtiger/dist/s_all b/src/third_party/wiredtiger/dist/s_all
--- a/src/third_party/wiredtiger/dist/s_all
+++ b/src/third_party/wiredtiger/dist/s_all
@@ -22,11 +22,11 @@ while :
 	-A)	# Reconfigure the library build.
 		reconf=1
 		shift;;
-	-f)	# Force versions to be updated
-		force="-f"
-		shift;;
 	-E)	# Return an error code on failure
 		errmode=1
+		shift;;
+	-f)	# Force versions to be updated
+		force="-f"
 		shift;;
 	*)
 		break;;
@@ -52,15 +52,12 @@ errchk()
 	sed -e 's/^/    /' $2
 	echo "#######################"
 
-	rm -f $2
+	# If the test was skipped, ignore the failure.
+	if ! `grep "$1.*skipped" $2 > /dev/null`; then
+	    errfound=1;
+	fi
 
-	# Some tests shouldn't return an error, we exclude them here.
-	case "$1" in
-	*s_export|*s_tags)
-		;;
-	*)
-		errfound=1;;
-	esac
+	rm -f $2
 }
 
 run()
