Import wiredtiger: f34a5afbb1d807ac90627555c3452fdec750b592 from branch mongodb-4.4
ref: 7374df6c34..f34a5afbb1
for: 4.4.7

WT-6737       Add explicit checkpoints in test_hs14 to improve predictability
WT-7228       Do not call next if we don't find the key in the history store
WT-7319       Implement a checkpoint_manager class that creates checkpoints at configurable intervals
WT-7320       Add the ability to check database size to the test framework
WT-7437       Upgrade documentation to doxygen 1.8.17
WT-7480       Cleanup thread_contexts in the test framework
WT-7514       Let tiered subsystem open files on behalf of block manager
WT-7523       Test to verify multiple prepared updates either commit/rollback
WT-7528       Fix WT_SESSION alter returns EBUSY
WT-7531       Treat update restore eviction as a progress
WT-7535       Complete CMake Windows support
WT-7577       Add sync configuration to flush_tier
WT-7579       Disable prefix testing in compatibility test due to snapshot isolation search mismatch
WT-7588       Make tiered object id numbers 32 bits
WT-7594       Use key_consistent mode on format TS runs
WT-7625       Updating throttle configuration to be more user friendly in testing framework
WT-7633       Switch doc-update Evergreen task to newer Ubuntu 20.04 distro
WT-7634       Disable man page generation in Doxygen
WT-7642       Fix insert search flag in history store cursor key order check
WT-7643       Update checkpoint decode tool for tiered storage
WT-7651       Add synchronization for flush_tier calls
WT-7656       Destroy tiered condvar after thread is joined

diff --git a/src/third_party/wiredtiger/dist/s_docs b/src/third_party/wiredtiger/dist/s_docs
--- a/src/third_party/wiredtiger/dist/s_docs
+++ b/src/third_party/wiredtiger/dist/s_docs
@@ -1,4 +1,4 @@
-#! /bin/sh
+#! /bin/bash
 
 t=__wt.$$
 trap 'rm -f $t' 0 1 2 3 13 15
@@ -8,7 +8,12 @@ test -n "$WT_RELEASE_BUILD" && exit 0
 
 # We require doxygen which may not be installed.
 type doxygen > /dev/null 2>&1 || {
-	echo 'skipped: doxygen not found'
+	echo "$0 skipped: doxygen not found"
+	exit 0
+}
+v=`(echo "1.8.17" && doxygen --version) | sort -V | head -1`
+test "$v" = "1.8.17" || {
+	echo "$0 skipped: unsupported version of doxygen"
 	exit 0
 }
 
@@ -194,21 +199,6 @@ EOF
 		done
 		)
 	fi
-
-	# Fixup the man pages generated by Doxygen. We want the command line
-	# documentation to be the main man page, but also install a man page
-	# for the WiredTiger header into the library section.
-	[ "$additional_languages" -eq 1 ] &&
-	(cd ../docs && mkdir -p man/man1 &&
-	    mv man/man3/command_line.3 man/man1/wt.1 &&
-	    sed -i~ -e 's/command_line/wt/g' man/man1/wt.1 &&
-	    sed -i~ -e 's/Version Version/Version/g' man/man1/wt.1 &&
-	    rm -f man/man1/wt.1~ &&
-	    mv man/man3/basic_api.3 man/ && rm -f man/man3/* &&
-	    mv man/basic_api.3 man/man3/wiredtiger.3 &&
-	    sed -i~ -e 's/basic_api/WiredTiger/g' man/man3/wiredtiger.3 &&
-	    sed -i~ -e 's/Version Version/Version/g' man/man3/wiredtiger.3 &&
-	    rm -f man/man3/wiredtiger.3~)
 }
 
 clean=0
