Import wiredtiger: 509f9db55e5288e864564cccbb5822fe8b3c9fd3 from branch mongodb-5.0
ref: 989de21a3d..509f9db55e
for: 4.9.0

WT-6714       Update API documentation for WT exposed APIs
WT-7070       Triage column store HS test failures
WT-7184       Prevent non-ASCII input in doc files
WT-7192       Fix failing assert when in-use dhandle can't be reopened

diff --git a/src/third_party/wiredtiger/dist/s_docs b/src/third_party/wiredtiger/dist/s_docs
--- a/src/third_party/wiredtiger/dist/s_docs
+++ b/src/third_party/wiredtiger/dist/s_docs
@@ -90,6 +90,20 @@ structurechk()
 	}
 }
 
+asciichk()
+{
+    # Make sure there are only ASCII characters in the input files.
+    # Odd characters can cause our Python filter to fail.
+    (cd ../src/docs && LC_ALL=C grep -n '[^[:print:]	]' *.dox | cat -v) > $t
+    test -s $t && {
+	echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
+	echo 'Non-ASCII content in src/docs/*.dox files is not allowed.'
+	sed -e 's/^/	/' < $t
+	echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
+	e=1
+    }
+}
+
 spellchk()
 {
 	# If aspell has been installed, run a spell check.
@@ -236,12 +250,17 @@ changelog
 wtperf_config
 
 # Spell and structure check the documentation.
+asciichk
 spellchk
 structurechk
 
 # Check the docs data input file.
 check_docs_data
 
+# Do not build the doc if we get warnings.
+if [ $e != 0 ]; then
+    exit $e
+fi
 # Build the documentation.
 build $clean
 
