Import wiredtiger: c5d050f4baaa48c4a29bd4b3c451f825690bcba1 from branch mongodb-master (#55942)
GitOrigin-RevId: 47c3183abdd18a446f10694a8637b974abc2b7f9

diff --git a/src/third_party/wiredtiger/dist/s_visibility_checks b/src/third_party/wiredtiger/dist/s_visibility_checks
--- a/src/third_party/wiredtiger/dist/s_visibility_checks
+++ b/src/third_party/wiredtiger/dist/s_visibility_checks
@@ -8,9 +8,9 @@ cd_top
 # It should never be - the "snap_min" visibility check should be used instead.
 found=`grep -rnI "txn_visible(.*addr.ta" src/`
 if [ ! -z "$found" ]; then
-	echo "Found invalid usage(s) of visibility check and a time aggregate window"
-	echo "$found"
-	exit 1
+    echo "Found invalid usage(s) of visibility check and a time aggregate window"
+    echo "$found"
+    exit 1
 fi
 
 exit 0
