SERVER-69994 Make spawnhost script more robust

diff --git a/buildscripts/setup_spawnhost_coredump b/buildscripts/setup_spawnhost_coredump
--- a/buildscripts/setup_spawnhost_coredump
+++ b/buildscripts/setup_spawnhost_coredump
@@ -10,6 +10,8 @@ case "${unameOut}" in
     *)          machine="UNKNOWN:${unameOut}"
 esac
 
+TOOLCHAIN_ROOT=/opt/mongodbtoolchain/v3  # TODO: Update to v4 after SERVER-62994.
+
 if [[ "${machine}" = "Cygwin" ]]; then
     out_dir="/cygdrive/c/setup_script_output.txt"
     desktop_dir="/cygdrive/c/Users/Administrator/Desktop"
@@ -20,35 +22,35 @@ if [[ "${machine}" = "Cygwin" ]]; then
 
         echo "----------------------"
         echo -e "\n=> Setting _NT_SOURCE_PATH environment variable for debuggers to pick up source files."
-        src_dir_hash=$(readlink -f /cygdrive/z/data/mci/source-*)
-        full_src_dir="${src_dir_hash}/src"
-        echo "Source Path: [${full_src_dir}]"
+        SRC_DIR_HASH=$(readlink -f /cygdrive/z/data/mci/source-*)
+        SRC_DIR="${SRC_DIR_HASH}/src"
+        echo "Source Path: [${SRC_DIR}]"
         set -x;
-        setx _NT_SOURCE_PATH "${full_src_dir}"
+        setx _NT_SOURCE_PATH "${SRC_DIR}"
         { set +x; } 2>/dev/null
 
         echo -e "\n=> Setting _NT_SYMBOL_PATH environment variable for debuggers to pick up the symbols."
-        sym_parent_dir=$(readlink -f /cygdrive/z/data/mci/artifacts-*dist_test_debug)
-        sym_dir=$(readlink -f ${sym_parent_dir}/debugsymbols-mongodb*zip)
-        sym_extracted_dir="${sym_parent_dir}/extracted_symbols"
-        full_sym_dir="${sym_extracted_dir}/dist-test/bin"
-        echo "Symbols Dir: [${full_sym_dir}]"
+        DBG_ARCHIVE_PARENT=$(readlink -f /cygdrive/z/data/mci/artifacts-*dist_test_debug)
+        DBG_ARCHIVE=$(readlink -f ${DBG_ARCHIVE_PARENT}/debugsymbols-mongodb*zip)
+        DBG_ARCHIVE_TARGET_PARENT="${DBG_ARCHIVE_PARENT}/extracted_symbols"
+        DBG_ARCHIVE_TARGET="${DBG_ARCHIVE_TARGET_PARENT}/dist-test/bin"
+        echo "Symbols Dir: [${DBG_ARCHIVE_TARGET}]"
 
         echo -e "\n=> Extracting Symbol files."
         set -x;
-        mkdir ${sym_extracted_dir}
-        unzip -n ${sym_dir} -d ${sym_extracted_dir}
-        setx _NT_SYMBOL_PATH "${full_sym_dir};srv*;"
+        mkdir ${DBG_ARCHIVE_TARGET_PARENT}
+        unzip -n ${sym_dir} -d ${DBG_ARCHIVE_TARGET}
+        setx _NT_SYMBOL_PATH "${DBG_ARCHIVE_TARGET};srv*;"
         { set +x; } 2>/dev/null
 
         echo -e "\n=> Extracting Core Dump to Desktop."
-        full_dump_dir=$(readlink -f /cygdrive/z/data/mci/artifacts-* | grep -v dist_test)
-        full_dump_parent_dir=$(readlink -f ${full_dump_dir}/mongo-coredumps*tgz)
-        extracted_dump_dir="${full_dump_dir}/extracted_dump"
+        COREDUMP_ARCHIVE_PARENT=$(readlink -f /cygdrive/z/data/mci/artifacts-* | grep -v dist_test)
+        COREDUMP_ARCHIVE=$(readlink -f ${COREDUMP_ARCHIVE_PARENT}/mongo-coredumps*tgz)
+        COREDUMP_ARCHIVE_TARGET="${COREDUMP_ARCHIVE_PARENT}/extracted_dump"
         set -x;
-        mkdir ${extracted_dump_dir}
-        tar -xzvf ${full_dump_parent_dir} -C ${extracted_dump_dir}
-        cp ${extracted_dump_dir}/* ${desktop_dir}
+        mkdir ${COREDUMP_ARCHIVE_TARGET}
+        tar -xzvf ${COREDUMP_ARCHIVE} -C ${COREDUMP_ARCHIVE_TARGET}
+        cp -r ${COREDUMP_ARCHIVE_TARGET}/* ${desktop_dir}
         { set +x; } 2>/dev/null
         echo "Copied to Desktop."
 
@@ -68,19 +70,22 @@ else
 cat ~/.setup_spawnhost_coredump_progress
 # Coredumps generated by a toolchain built mongodb can be problematic when examined with the system
 # gdb.
-alias gdb='/opt/mongodbtoolchain/v3/bin/gdb'
+alias gdb='${TOOLCHAIN_ROOT}/bin/gdb'
 # As per below, put the user into the appropriate directory. This is where gdb is expected to be
 # invoked from.
 cd debug
 echo "Debuggable binaries:"
-ls -l mongo* | grep -v debug$
+ls -l mongo* 2>/dev/null | grep -v debug$
+ls -l bin/ 2>/dev/null
+( ls -l mongo* &>/dev/null | grep -v debug$ || ls -l bin/ &>/dev/null ) || echo " [none]"
+
 for item in "mongo" "mongod" "mongos"; do
     echo "\${item} core dumps:"
-    ls -l dump_\${item}.*
+    ls -l dump_\${item}.* 2>/dev/null || echo " [none]"
 done
 
 echo "Core dumps from unknown processes (crashed processes typically found here):"
-ls -l dump_* | grep -v mongo
+ls -l dump_* 2>/dev/null | grep -v mongo || echo " [none]"
 
 echo
 echo "To examine a core dump, type 'gdb ./<binary> ./<core file>'"
@@ -100,40 +105,78 @@ fi' >> .bash_profile
     # As the name suggests, pretty printers. Primarily for boost::optional<T>
     git clone git@github.com:ruediger/Boost-Pretty-Printer.git &
 
+    archive_fail() {
+        echo "Error: archive [${1}] not found." >&2
+    }
+
     # Discover and unarchive necessary files and source code. This will put mongo binaries and their
     # partner .debug files in the same `debug/bin` directory. The `bin` directory will later be symbolic
     # linked into the top-level (`debug`) directory. Shared library files and their debug symbols will
     # be dumped into a `debug/lib` directory for tidiness. The mongo `<reporoot>/src/` directory is soft
     # linked as `debug/src`. The .gdbinit file assumes gdb is being run from the `debug` directory.
-    BIN_ARCHIVE=`ls /data/mci/artifacts-*archive_dist_test*/mongo-*.tgz`
-    tar --wildcards --strip-components=1 -xzf $BIN_ARCHIVE '*/bin/mongod' '*/bin/mongos' '*/bin/mongo' '*/bin/mongobridge' &
-    tar --wildcards --strip-components=1 -xzf $BIN_ARCHIVE '*/lib/*' &
-    DBG_ARCHIVE=`ls /data/mci/artifacts-*archive_dist_test_debug/debugsymbols-*.tgz`
-    # Support discovering split-dwarf files. Specifically, capture both <file>.debug and <file>.dwp
-    # files.
-    tar --wildcards --strip-components=1 -xzf $DBG_ARCHIVE '*/bin/mongod.d*' '*/bin/mongos.d*' '*/bin/mongo.d*' '*/bin/mongobridge.d*' &
-    tar --wildcards --strip-components=1 -xzf $DBG_ARCHIVE '*/lib/*' &
-    UNITTEST_ARCHIVE=`ls /data/mci/artifacts-*run_unittests/mongo-unittests-*.tgz`
-    tar --wildcards --strip-components=0 -xzf $UNITTEST_ARCHIVE 'bin/*' &
-    tar --wildcards -xzf $UNITTEST_ARCHIVE 'lib/*' &
+    BIN_ARCHIVE=$(ls /data/mci/artifacts-*archive_dist_test*/mongo-*.tgz 2>/dev/null)
+    if [[ -n $BIN_ARCHIVE ]]; then
+        # Have shell expand braces before passing the wildcard to tar.
+        bin_files_pattern=(\*/bin/mongo{d,s,,bridge})
+        tar --wildcards --strip-components=1 -xzf $BIN_ARCHIVE "${bin_files_pattern[@]}"
+        tar --wildcards --strip-components=1 -xzf $BIN_ARCHIVE '*/lib/*' &
+    else
+        archive_fail "bin"
+    fi
 
-    SRC_DIR=`find /data/mci/ -maxdepth 1 | grep source`
-    ln -s $SRC_DIR/.gdbinit .
-    ln -s $SRC_DIR/src src
-    ln -s $SRC_DIR/buildscripts buildscripts
+    DBG_ARCHIVE=$(ls /data/mci/artifacts-*archive_dist_test_debug/debugsymbols-*.tgz 2>/dev/null)
+    if [[ -n $DBG_ARCHIVE ]]; then
+        # Support discovering split-dwarf files. Specifically, capture both <file>.debug and <file>.dwp
+        # files.
+        # Have shell expand braces before passing the wildcard to tar.
+        dbg_files_pattern=(\*/bin/mongo{d,s,,bridge}.{debug,dwp})
+        tar --wildcards --strip-components=1 -xzf $DBG_ARCHIVE "${dbg_files_pattern[@]}" &
+        tar --wildcards --strip-components=1 -xzf $DBG_ARCHIVE '*/lib/*' &
+    else
+        archive_fail "debug"
+    fi
 
-    # Install pymongo to get the bson library for pretty-printers.
-    /opt/mongodbtoolchain/v3/bin/pip3 install -r $SRC_DIR/etc/pip/dev-requirements.txt &
+    UNITTEST_ARCHIVE=$(ls /data/mci/artifacts-*run_unittests/mongo-unittests-*.tgz 2>/dev/null)
+    if [[ -n $UNITTEST_ARCHIVE ]]; then
+        tar --wildcards --strip-components=0 -xzf $UNITTEST_ARCHIVE '*/bin/*' &
+        tar --wildcards -xzf $UNITTEST_ARCHIVE '*/lib/*' &
+    else
+        archive_fail "unittest"
+    fi
 
-    COREDUMP_ARCHIVE=`ls /data/mci/artifacts-*/mongo-coredumps-*.tgz`
-    tar -xzf $COREDUMP_ARCHIVE &
+    BENCHMARK_ARCHIVE=$(ls /data/mci/artifacts-*compile_upload_benchmarks/mongodb_mongo_*.tgz 2>/dev/null)
+    if [[ -n $BENCHMARK_ARCHIVE ]]; then
+        tar --wildcards --strip-components=2 -xzf $BENCHMARK_ARCHIVE '*/bin/*' &
+    else
+        archive_fail "benchmark"
+    fi
+
+    SRC_DIR=$(ls -d /data/mci/source-* 2>/dev/null)
+    if [[ -n $SRC_DIR ]]; then
+        ln -s ${SRC_DIR}/.gdbinit .
+        ln -s ${SRC_DIR}/src src
+        ln -s ${SRC_DIR}/buildscripts buildscripts
+
+        # Install pymongo to get the bson library for pretty-printers.
+        ${TOOLCHAIN_ROOT}/bin/pip3 install -r ${SRC_DIR}/etc/pip/dev-requirements.txt &
+    else
+        archive_fail "src"
+    fi
+
+    COREDUMP_ARCHIVE=$(ls /data/mci/artifacts-*/mongo-coredumps-*.tgz 2>/dev/null)
+    if [[ -n $COREDUMP_ARCHIVE ]]; then
+        tar -xzf $COREDUMP_ARCHIVE &
+    else
+        archive_fail "coredump"
+    fi
+
     echo "Waiting for background processes to complete."
     wait
 
     # Symbolic linking all of the executable files is sufficient for `gdb ./mongod ./dump_mongod.core`
     # to succeed. This inadvertantly also links in the ".debug" files which is unnecessary, but
     # harmless. gdb expects the .debug files to live adjacent to the physical binary.
-    ln -s bin/* ./
+    find bin -type f -perm -o=x -exec ln -s {} . \;
 
     cat >> ~/.gdbinit <<EOF
 set auto-load safe-path /
@@ -149,9 +192,8 @@ sys.path.insert(0, './Boost-Pretty-Printer')
 import boost
 boost.register_printers()
 end
+dir $HOME/debug
 EOF
-
-    echo "dir $HOME/debug" >> ~/.gdbinit
 
     # Empty out the progress script that warns users about the set script still running when users log in.
     echo "" > ~/.setup_spawnhost_coredump_progress
